#!/bin/sh

# Strict, secret-free output contract for the typed Control Plane deployer.
# This validator accepts only reviewed stage/result evidence.
set -eu
LC_ALL=C
export LC_ALL

ALLOWED_STAGES='CLOUD_FIRST_MIGRATION_FIRST CLOUD_FIRST_MIGRATION_IDEMPOTENT CLOUD_FIRST_MIGRATION_VERIFIED CLOUD_FIRST_ROUTE ACCOUNT_HOSTING_MIGRATION_FIRST ACCOUNT_HOSTING_MIGRATION_IDEMPOTENT ACCOUNT_HOSTING_MIGRATION_VERIFIED ACCOUNT_HOSTING_ROUTE HOSTING_OPERATOR_UNITS_READY AI_GOVERNANCE_ROUTE ACCOUNT_HOSTING_MIGRATION_FIRST ACCOUNT_HOSTING_MIGRATION_IDEMPOTENT ACCOUNT_HOSTING_MIGRATION_VERIFIED ACCOUNT_HOSTING_ROUTE HOSTING_OPERATOR_QUIESCED HOSTING_OPERATOR_UNITS_READY HOSTING_ROUTE ANYWHERE_EXECUTION_ROUTE ANYWHERE_MIGRATION_FIRST ANYWHERE_MIGRATION_IDEMPOTENT ANYWHERE_MIGRATION_VERIFIED ARTIFACT_STORAGE_READY ASSISTANT_MIGRATION_FIRST ASSISTANT_MIGRATION_IDEMPOTENT ASSISTANT_MIGRATION_VERIFIED ASSISTANT_ROUTE ATTACHMENT_STORAGE_READY AUTOMATION_MIGRATION_FIRST AUTOMATION_MIGRATION_IDEMPOTENT AUTOMATION_MIGRATION_VERIFIED AUTOMATION_ROUTE BACKUP_VERIFIED CENTRAL_PROJECT_MIGRATION_FIRST CENTRAL_PROJECT_MIGRATION_IDEMPOTENT CENTRAL_PROJECT_MIGRATION_VERIFIED CENTRAL_PROJECT_ROUTE CONTROL_ORIGIN_RENDER CONTROL_POINTER CONTROL_ROUTE COST_AWARE_AI_ROUTE COST_AWARE_MIGRATION_FIRST COST_AWARE_MIGRATION_IDEMPOTENT COST_AWARE_MIGRATION_VERIFIED FINAL_MIGRATION_FIRST FINAL_MIGRATION_IDEMPOTENT FINAL_MIGRATION_VERIFIED FINAL_PRODUCT_ROUTE FOUNDING_MEMORY_ROUTE FOUNDING_MIGRATION_FIRST FOUNDING_MIGRATION_IDEMPOTENT FOUNDING_MIGRATION_VERIFIED M3D_REGRESSION M3E_POST_SCHEMA_REGRESSION MIGRATION_FIRST_PASS MIGRATION_IDEMPOTENT MIGRATION_VERIFIED NATIVE_EXECUTOR_QUIESCED NATIVE_EXECUTOR_UNITS_READY NGINX_CONFIGURED NGINX_CUTOVER_INSTALL NGINX_CUTOVER_PREPARE OWNER_AUTH_COMPATIBILITY OWNER_AUTH_CONTROL OWNER_AUTH_EFFECTIVE_CONFIG OWNER_AUTH_LOGIN OWNER_AUTH_MIGRATION_FIRST OWNER_AUTH_MIGRATION_IDEMPOTENT OWNER_AUTH_PRESERVED OWNER_AUTH_PROVISION OWNER_AUTH_RUNTIME OWNER_AUTH_SESSION OWNER_AUTH_SURFACE OWNER_AUTH_VERIFIED OWNER_AUTH_WEB_SURFACE PHP_FPM_RELOAD PREMUTATION_READY PROJECTS_READY PROJECT_VAULT_RUNTIME_READY PROJECT_VAULT_SOURCE_SYNC PROJECT_VAULT_STORAGE_READY PROVIDER_CREDENTIAL_STORAGE_READY RELEASE_STAGED SELF_SERVICE_MIGRATION_FIRST SELF_SERVICE_MIGRATION_IDEMPOTENT SELF_SERVICE_MIGRATION_VERIFIED SELF_SERVICE_ROUTE SELF_SUFFICIENT_MIGRATION_FIRST SELF_SUFFICIENT_MIGRATION_IDEMPOTENT SELF_SUFFICIENT_MIGRATION_VERIFIED SERVICE_RELOAD TOPOLOGY_CLEANUP_ARCHIVE TOPOLOGY_CLEANUP_VERIFY UNIFIED_MIGRATION_FIRST UNIFIED_MIGRATION_IDEMPOTENT UNIFIED_MIGRATION_VERIFIED UNIFIED_ROUTE WEB_ACCESS_READY WEB_MANIFEST_VERIFIED WEB_POINTER_SWITCH WEB_RELEASE_COPY WEB_RELEASE_STAGED WORKSPACE_MIGRATION_FIRST WORKSPACE_MIGRATION_IDEMPOTENT WORKSPACE_MIGRATION_VERIFIED WORKSPACE_PRESERVED WORKSPACE_ROUTE'
ALLOWED_FAILURE_EXTRAS='NGINX_INCLUDE_PREPARE NGINX_INCLUDE_INSERT REMOTE_TRANSPORT REMOTE_RESULT_MISSING'

allowed_token() {
  list=$1
  value=$2
  case " $list " in *" $value "*) return 0 ;; *) return 1 ;; esac
}

reject() {
  echo 'M4 remote output contract rejected' >&2
  exit 1
}

while IFS= read -r line; do
  case "$line" in
    DEPLOY_STAGE=*)
      value=${line#DEPLOY_STAGE=}
      allowed_token "$ALLOWED_STAGES" "$value" || reject
      printf '%s\n' "$line"
      ;;
    DEPLOY_FAILED_AT=*)
      value=${line#DEPLOY_FAILED_AT=}
      allowed_token "$ALLOWED_STAGES $ALLOWED_FAILURE_EXTRAS" "$value" || reject
      printf '%s\n' "$line"
      ;;
    WEB_RELEASE_MANIFEST=PASS\ files=*)
      count=${line#WEB_RELEASE_MANIFEST=PASS files=}
      case "$count" in ''|0|0*|*[!0-9]*) reject ;; esac
      test "$count" -le 100 || reject
      printf '%s\n' "$line"
      ;;
    DEPLOY_DIAGNOSTIC=OWNER_AUTH_SURFACE_HTTP_[0-9][0-9][0-9]|DEPLOY_DIAGNOSTIC=OWNER_AUTH_LOGIN_HTTP_[0-9][0-9][0-9]|DEPLOY_DIAGNOSTIC=OWNER_AUTH_SURFACE_ATTEMPTS_[1-9]|DEPLOY_DIAGNOSTIC=OWNER_AUTH_SURFACE_ATTEMPTS_10|DEPLOY_DIAGNOSTIC=OWNER_AUTH_SURFACE_BASIC_CHALLENGE|DEPLOY_DIAGNOSTIC=OWNER_AUTH_LOGIN_BASIC_CHALLENGE|DEPLOY_RESULT=PASS|ROLLBACK=PASS|ROLLBACK=FAIL)
      printf '%s\n' "$line"
      ;;
    '') : ;;
    *) reject ;;
  esac
done
