import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = async (path: string) => readFile(new URL('../' + path, import.meta.url), 'utf8');
const json = async (path: string) => JSON.parse(await read(path));

test('M23 platform policy locks long-term ecosystem authorities', async () => {
  const p = await json('config/ecosystem-platform-policy.json');
  assert.equal(p.schemaVersion, 1);
  assert.equal(p.identity.platformAuthority, 'KRUART');
  assert.equal(p.identity.schoolAuthority, 'BAY_EXCUSE_X');
  assert.equal(p.identity.academicContextAuthority, 'BAY_EXCUSE_X');
  assert.equal(p.releaseContract.artifactFirst, true);
  assert.equal(p.releaseContract.buildOnceDeployExactArtifact, true);
  assert.equal(p.queueLifecycle.indefiniteQueuedStateForbidden, true);
  assert.equal(p.queueLifecycle.deadLetterRequired, true);
  assert.equal(p.backup.offServerMirrorRequired, true);
  assert.equal(p.eventBus.authority, 'AWH_DURABLE_OUTBOX');
  assert.equal(p.eventBus.directCrossProductDatabaseWritesForbidden, true);
  assert.equal(p.operationsCenter.defaultView, 'SUMMARY_FIRST_WITH_ATTENTION_FILTER');
});

test('ecosystem release contract covers product families and independent release tracks', async () => {
  const c = await json('config/ecosystem-release-contract.json');
  const policy = await json('config/ecosystem-platform-policy.json');
  const registry = await read('hub/src/HubUpdateTargetRegistry.php');
  const reposStart=registry.indexOf('public static function repositories');
  const tracksStart=registry.indexOf('public static function releaseTracks');
  assert.ok(reposStart>=0&&tracksStart>reposStart);
  const repositoryBlock=registry.slice(reposStart,tracksStart);
  const registryKeys=[...repositoryBlock.matchAll(/^\s*'([^']+)'=>\[/gm)].map((match)=>match[1]);
  assert.deepEqual(Object.keys(c.products).sort(), registryKeys.sort());
  for (const [key, row] of Object.entries(c.products as Record<string,{project:string}>)) {
    assert.equal(repositoryBlock.includes("'" + key + "'"), true);
    assert.ok(row.project.length > 0);
  }

  const expectedTracks=['awh','awh-agent','awh-line-gateway','bay-assessment','bay-computer-lab','bay-cooperative','bay-excuse-x','bay-hub','bay-learnlab','bay-pp','line-oa','school-website','vps-platform'];
  assert.deepEqual(Object.keys(c.releaseTracks).sort(), expectedTracks);
  assert.deepEqual([...policy.releaseTracks.tracks].sort(), expectedTracks);
  for(const key of expectedTracks){
    const track=c.releaseTracks[key];
    assert.equal(track.independentVersion,true);
    assert.equal(track.independentHistory,true);
    assert.equal(track.independentRollback,true);
    assert.equal(track.ownerApprovalRequired,true);
    assert.ok(typeof track.deploymentAdapter==='string'&&track.deploymentAdapter.length>0);
    assert.ok(typeof track.dataOwner==='string'&&track.dataOwner.length>0);
    assert.ok(typeof track.permissionScope==='string'&&track.permissionScope.length>0);
    assert.ok(typeof track.observabilityScope==='string'&&track.observabilityScope.length>0);
    assert.ok(['PRIMARY','ADVANCED'].includes(track.visibility));
  }
  assert.equal(c.releaseTracks['bay-hub'].visibility,'ADVANCED');
  for(const key of expectedTracks.filter((key)=>key!=='bay-hub')) assert.equal(c.releaseTracks[key].visibility,'PRIMARY');
  assert.notEqual(c.releaseTracks['vps-platform'].productionRef,c.releaseTracks.awh.productionRef);
  assert.equal(c.releaseTracks['awh-line-gateway'].sourceAuthority,'AWH_VAULT');
  assert.equal(c.releaseTracks['awh-line-gateway'].repository,null);
  assert.equal(c.releaseTracks['awh-line-gateway'].domain,'line.kruart.online');
  assert.equal(c.releaseTracks['awh-line-gateway'].healthPath,'/healthz');
  assert.equal(c.releaseTracks['awh-line-gateway'].webhookPath,'/webhook');
  assert.equal(c.releaseTracks['awh-line-gateway'].deploymentAdapter,'MANAGED_HOSTING');
  assert.equal(c.releaseTracks['line-oa'].repository,'bay-excuse-x');
  assert.equal(c.releaseTracks['line-oa'].packageTrack,'line-oa');
  assert.equal(c.releaseTracks['line-oa'].deploymentAdapter,'BAY_UPDATE_CENTER');
  assert.notEqual(c.releaseTracks['awh-line-gateway'].dataOwner,c.releaseTracks['line-oa'].dataOwner);
  assert.notEqual(c.releaseTracks['awh-line-gateway'].permissionScope,c.releaseTracks['line-oa'].permissionScope);
  assert.notEqual(c.releaseTracks['awh-line-gateway'].observabilityScope,c.releaseTracks['line-oa'].observabilityScope);
  assert.notEqual(c.releaseTracks['awh-line-gateway'].secretScope,c.releaseTracks['line-oa'].secretScope);
  assert.equal(c.releaseTracks['bay-cooperative'].packageTrack,'cooperative-center');
  assert.equal(c.releaseTracks['bay-pp'].packageTrack,'pp-center');
  assert.equal(c.releaseTracks['vps-platform'].visibility,'PRIMARY');
  assert.equal(c.releaseTracks['bay-cooperative'].visibility,'PRIMARY');
  assert.equal(c.releaseTracks['bay-pp'].visibility,'PRIMARY');
  assert.equal(c.rules.crossProjectWriteForbidden,true);
  assert.equal(c.rules.dependencyByContractOnly,true);
  assert.equal(c.rules.registryDrivenUpdateCenter,true);
  assert.equal(c.rules.updateCenterLayoutMutationForNewTrackForbidden,true);
  assert.deepEqual(c.requiredArtifactIdentity, ['product','version','sourceSha','artifactSha256','schemaVersion','builtAt']);
  assert.equal(c.rules.productionRebuildForbidden, true);
  assert.equal(c.rules.rollbackArtifactRequired, true);
  assert.equal(c.rules.releaseTrackIdentityRequired, true);
  assert.equal(c.rules.groupOrchestrationPreservesIndependentTargets,true);
  assert.equal(c.rules.implicitCrossTrackReleaseForbidden,true);
  assert.deepEqual(c.releaseGroups['line-oa'].targets,[
    {itemKey:'awh-line-gateway',releaseTrack:'awh-line-gateway'},
    {itemKey:'bay-excuse-line-oa',releaseTrack:'line-oa'},
  ]);
  assert.equal(c.releaseGroups['line-oa'].approvalMode,'SIGNED_IN_OWNER');
  assert.equal(c.releaseGroups['line-oa'].orchestration,'SEQUENTIAL_VERIFY_EACH');
  assert.equal(c.releaseGroups['line-oa'].historyScope,'PER_TARGET');
  assert.equal(c.releaseGroups['line-oa'].rollbackScope,'PER_TARGET');
  assert.deepEqual(c.releaseGroups['line-oa'].forbiddenImplicitTargets,['awh','vps-platform','bay-excuse-x']);
});

test('navigation contract v2 locks shared app shells, touch safety and framework-independent semantics', async () => {
  const c = await json('config/ecosystem-navigation-contract.json');
  const nav = await read('web/navigation.js');
  assert.equal(c.schemaVersion, 2);
  assert.equal(c.authority, 'KRUART_DESIGN_SYSTEM');
  assert.equal(c.productNavigationAuthority, 'config/kruart-experience-contract.json');
  assert.equal(c.rules.deadEndsForbidden, true);
  assert.equal(c.rules.singleNavigationManifestPerProduct, true);
  assert.equal(c.rules.appShellRequired, true);
  assert.equal(c.rules.frameworkIndependentContract, true);
  assert.equal(c.rules.visualRegressionRequired, true);
  assert.equal(c.rules.accessibilityGateRequired, true);
  assert.equal(c.rules.safeAreaRequired, true);
  assert.equal(c.rules.horizontalOverflowForbidden, true);
  assert.equal(c.rules.mobilePrimaryDestinationMax, 5);
  assert.deepEqual(c.rules.requiredEscapeActions, ['HOME','BACK_OR_PARENT']);
  assert.deepEqual(Object.keys(c.appShells).sort(), ['ADMIN_CONSOLE','PUBLIC_SITE','STUDENT_APP','TEACHER_OPERATIONAL']);
  for (const shell of Object.values(c.appShells) as Array<any>) assert.ok(shell.primaryDestinationMax <= 5);
  assert.equal(c.interaction.touchTargetPx, 44);
  assert.equal(c.interaction.primaryTouchTargetPx, 48);
  assert.equal(c.interaction.criticalTouchTargetPx, 52);
  assert.equal(c.interaction.focusNotObscured, true);
  assert.deepEqual(c.qa.canonicalViewportWidths, [390,430,820,1366,1440]);
  assert.equal(c.progressiveEnhancement.frameworkRewriteRequired, false);
  assert.equal(c.progressiveEnhancement.nativeLinksFirst, true);
  assert.match(nav, /installAwhBackNavigation/);
  assert.match(nav, /window\.history\.back/);
  assert.deepEqual(Object.keys(c.personas).sort(), ['ADMIN','STUDENT','TEACHER']);
});

test('platform hardening is wired to runtime rather than documentation only', async () => {
  const executor = await read('hub/bin/awh-native-executor.php');
  const bridge = await read('hub/src/HubOperatorBridgeService.php');
  const router = await read('hub/src/HubControlPlaneRouter.php');
  const bounded = await read('scripts/ops/bounded-deploy-mission.mjs');
  const deploy = await read('deploy/awh-control-plane/remote-deploy-control-plane.sh');
  const deployOrchestrator = await read('deploy/awh-control-plane/deploy-control-plane.sh');
  const health = await read('hub/src/HubEcosystemHealthService.php');
  const control = await read('hub/src/HubControlPlaneService.php');
  assert.match(executor, /HubExecutionLifecycleService/);
  assert.match(executor, /->reconcile\(/);
  assert.match(bridge, /HubExecutionLifecycleService/);
  assert.match(router, /identity\/academic-context/);
  assert.match(bounded, /--platform-hardening/);
  assert.match(bounded, /run-release-qa-isolated\.sh/);
  const qaRunner = await readFile('scripts/ops/run-release-qa-isolated.sh', 'utf8');
  assert.match(qaRunner, /git clone --quiet --shared --no-checkout "\$ROOT" "\$QA_ROOT"/);
  assert.doesNotMatch(qaRunner, /worktree add --detach/);
  assert.match(qaRunner, /\/opt\/awh-toolchain\/node\/bin/);
  assert.match(qaRunner, /npm ci --ignore-scripts --no-audit --no-fund --prefer-offline/);
  assert.match(qaRunner, /QA_EXACT_SHA_REUSE=PASS/);
  assert.match(qaRunner, /command -v sha256sum/);
  assert.match(qaRunner, /shasum -a 256/);
  assert.match(qaRunner, /openssl dgst -sha256/);
  assert.match(qaRunner, /AWH_RELEASE_QA_EVIDENCE_ROOT/);
  assert.match(qaRunner, /QA_FAILURE_EVIDENCE=/);
  assert.match(qaRunner, /AWH_QA_SINGLEFLIGHT_ROOT/);
  assert.doesNotMatch(qaRunner, /ln -s[^\n]*node_modules/);
  assert.doesNotMatch(qaRunner, /--property=Nice=/);
  assert.match(bounded, /MISSION_DEPENDENCIES=ISOLATED_QA/);
  assert.match(bounded, /MISSION_CANONICAL_MAIN_MOVED/);
  assert.match(deploy, /PLATFORM_HARDENING_MIGRATION_VERIFIED/);
  const platformStart=deploy.indexOf('if test "$PLATFORM_HARDENING" = 1; then\n  stage WORKSPACE_PRESERVED');
  const platformEnd=deploy.indexOf('elif test "$IDENTITY_CONVERGENCE" = 1; then',platformStart);
  const platformBlock=deploy.slice(platformStart,platformEnd);
  assert.ok(platformStart>=0&&platformEnd>platformStart,'VPS Platform deploy branch is present');
  assert.match(deploy,/validate_live_service_unit\(\)/);
  assert.match(deploy,/validate_live_timer_unit\(\)/);
  assert.match(deploy,/backup_live_unit\(\)/);
  assert.match(platformBlock,/validate_live_service_unit "\$EXECUTOR_SERVICE_UNIT".*awh-native-executor\.php.*strict/);
  assert.match(platformBlock,/validate_live_service_unit "\$HOSTING_SERVICE_UNIT".*awh-hosting-operator\.php.*full/);
  assert.match(platformBlock,/backup_live_unit "\$HOSTING_SERVICE_UNIT" "\$HOSTING_SERVICE_BACKUP"/);
  assert.doesNotMatch(platformBlock,/cmp -s "\$HOSTING_SERVICE_UNIT" "\$PREVIOUS_TARGET\/deploy\/systemd\/awh-hosting-operator\.service"/);
  assert.match(deploy, /PLATFORM_RUNTIME_READY/);
  assert.match(deploy, /OPERATOR_BRIDGE_RECONCILE/);
  assert.match(deploy, /sudo env AWH_RELEASE_ROOT="\$RELEASE" "\$RELEASE\/deploy\/operator-bridge\/install\.sh"/);
  assert.match(deploy, /sudo -u bayadmin test -w \/var\/lib\/awh-remote\/operator-staging/);
  assert.match(deploy, /OPERATOR_BRIDGE_READY/);
  assert.match(deploy, /HOSTING_IDENTITY_RECONCILE/);
  assert.match(deploy, /awh-hosting-identity@\*\.service/);
  assert.match(deploy, /awh-hosting-identity\.php/);
  assert.match(deploy, /systemctl reset-failed "\$identity_unit"/);
  assert.match(deploy, /HOSTING_IDENTITY_READY/);
  assert.ok(deploy.indexOf('stage HOSTING_IDENTITY_READY')<deploy.indexOf('stage EXECUTION_AUTHORITY_RELEASE'),'historical hosting identity failures reconcile before Platform authority is relinquished');
  assert.ok(deploy.indexOf('stage OPERATOR_BRIDGE_RECONCILE')>deploy.indexOf('stage SOURCE_DRIFT_VERIFIED'),'operator bridge reconciliation follows source-drift verification');
  assert.ok(deploy.indexOf('stage OPERATOR_BRIDGE_READY')<deploy.indexOf('stage EXECUTION_AUTHORITY_RELEASE'),'operator bridge reconciliation completes before the release authority is relinquished');
  assert.match(deploy, /platform_attempt=1[\s\S]*platform_attempt=\$\(\(platform_attempt \+ 1\)\)/);
  assert.match(deployOrchestrator, /EXTENSION_MODE_COUNT=\$\(\(AWH_CORE \+ ASSISTANT_WORKSTREAM/);
  assert.match(deployOrchestrator, /if test "\$EXTENSION_MODE_COUNT" -eq 0; then OWNER_LOGIN_PROOF_REQUIRED=1; fi/);
  assert.match(health, /'slo'/);
});

test('off-server backup reuses verified backup authority and verifies transport integrity', async () => {
  const exporter=await read('hub/bin/backup-export.php');
  const wrapper=await read('deploy/awh-backup/awh-backup-export');
  const pull=await read('deploy/offsite-backup/macos/awh-backup-pull.sh');
  const install=await read('deploy/offsite-backup/macos/install.sh');
  assert.match(exporter,/HubBackupService::latestMetadata/);
  assert.match(exporter,/HubBackupService::verify/);
  assert.match(exporter,/Requested backup is not the current verified snapshot/);
  assert.match(wrapper,/control-plane-current\/hub\/bin\/backup-export\.php/);
  assert.match(pull,/StrictHostKeyChecking=yes/);
  assert.match(pull,/shasum -a 256/);
  assert.match(pull,/AWH_OFFSITE_KEEP/);
  assert.match(pull,/\.pull\.lock/);
  assert.match(pull,/reason=already-running/);
  assert.match(pull,/shasum -a 256 "\$DEST\/\$file"/);
  assert.match(install,/com\.awh\.offsite-backup/);
  assert.match(install,/StartCalendarInterval/);
  assert.doesNotMatch(exporter+'\n'+pull,/password=|token=|private[_-]?key/i);
});
