<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/src/HubCapabilityRegistryService.php';
require_once dirname(__DIR__) . '/src/HubUpdateTargetRegistry.php';
function ep(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);}
$p=HubCapabilityRegistryService::executionPolicy();
ep(($p['version']??null)==='2.3-project-admission','project-admission execution policy version');
ep(($p['mode']??null)==='CONTEXT_ONLY'&&($p['enforcement']??null)==='ADVISORY','context is non-prescriptive');
ep(($p['sourceAuthorityRequiredForMutation']??false)===true&&($p['singleWriterMutationBoundary']??false)===true&&($p['mutationBoundary']??null)==='CONFLICTING_RESOURCE','integrity boundary remains enforced');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.platform.release','VPS')==='CANONICAL:DEPLOY:VPS_PLATFORM','platform release has host-global track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.core.release','VPS')==='CANONICAL:DEPLOY:AWH','AWH release has its own track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.learnlab.release','VPS')==='CANONICAL:DEPLOY:BAY_LEARNLAB','LearnLab release has its own track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.assessment.release','VPS')==='CANONICAL:DEPLOY:BAY_ASSESSMENT','Assessment release has its own track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('bay.remote_update.install','VPS',json_encode(['releaseTrack'=>'bay-excuse-core']))==='CANONICAL:DEPLOY:BAY_EXCUSE','BAY Core install keeps its own deploy track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('bay.remote_update.install','VPS',json_encode(['releaseTrack'=>'line-oa']))==='CANONICAL:DEPLOY:LINE_OA','LINE OA install keeps its own deploy track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('bay.remote_update.install','VPS',json_encode(['releaseTrack'=>'cooperative-center']))==='CANONICAL:DEPLOY:BAY_COOPERATIVE','Cooperative install keeps its own deploy track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('bay.remote_update.install','VPS',json_encode(['releaseTrack'=>'pp-center']))==='CANONICAL:DEPLOY:BAY_PP','PP install keeps its own deploy track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('bay.remote_update.install','VPS')==='CANONICAL:DEPLOY:PROJECT','legacy BAY install without track metadata remains fail-closed');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:BAY_EXCUSE','bay','CANONICAL:DEPLOY:LINE_OA','bay')===false,'BAY Core and LINE OA deploy tracks do not block each other');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:BAY_EXCUSE','bay','CANONICAL:DEPLOY:BAY_COOPERATIVE','bay')===false,'BAY Core and Cooperative deploy tracks do not block each other');
ep(HubCapabilityRegistryService::mutationResourceForExecution('source.promote','VPS')==='CANONICAL:SOURCE','source promotion remains canonical-source scoped');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:AWH','project-a','CANDIDATE','project-a')===false,'candidate mission does not block AWH deploy');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:AWH','project-a','CANONICAL:DEPLOY:BAY_LEARNLAB','project-b')===false,'different release tracks can deploy independently');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:VPS_PLATFORM','platform','CANONICAL:DEPLOY:AWH','project-a')===true,'platform deploy blocks another deploy while shared host runtime mutates');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:VPS_PLATFORM','platform','CANONICAL:SOURCE','project-a')===false,'exact-SHA platform deploy does not block canonical source promotion');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:SOURCE','project-a','CANONICAL:DEPLOY:VPS_PLATFORM','platform')===false,'canonical source may fast-forward while immutable platform target deploys');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:VPS_PLATFORM','platform','RESOURCE:RELEASE_STAGE','project-a')===true,'platform deploy blocks release staging that could change shared host release state');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:VPS_PLATFORM','platform','CANDIDATE','project-a')===false,'candidate work remains isolated while platform release runs');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:SOURCE','project-a','CANONICAL:DEPLOY:AWH','project-a')===false,'exact-SHA AWH deploy does not block later source promotion');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:SOURCE','project-a','CANONICAL:DEPLOY:BAY_LEARNLAB','project-b')===false,'different-project source promotion remains independent');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('RESOURCE:RELEASE_STAGE','project-a','CANONICAL:DEPLOY:AWH','project-a')===true,'same-project staging interlocks with deploy');
ep(HubCapabilityRegistryService::mutationResourceIsGlobal('CANONICAL:DEPLOY:VPS_PLATFORM')===true,'VPS Platform is host-global');
ep(HubCapabilityRegistryService::mutationResourceIsGlobal('CANONICAL:DEPLOY:AWH')===false,'AWH deploy is not host-global');
ep(HubCapabilityRegistryService::mutationResourcesConflict('CANONICAL:SOURCE','CANONICAL:SOURCE')===true,'same canonical resource serializes');
ep(HubCapabilityRegistryService::mutationResourcesConflict('CANONICAL:PROJECT','CANDIDATE')===true,'unknown canonical mutations fail closed');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['config/execution-policy.json','hub/src/HubControlPlaneService.php','web/updates.js'])==='vps-platform','Platform-owned change plus shared Update Center integration stays on VPS Platform track');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['web/app.js','hub/src/HubControlPlaneService.php'])==='awh','AWH-owned change plus shared Update Center integration stays on AWH track');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['config/execution-policy.json','web/app.js'])===null,'true mixed AWH and VPS Platform change-set is rejected');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['scripts/qa/test-singleflight.mjs','test/test-singleflight.test.mjs'])==='vps-platform','QA singleflight infrastructure is VPS Platform-owned');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['scripts/ops/run-release-qa-isolated.sh','test/bounded-deploy-mission.test.ts'])==='vps-platform','isolated release QA runner and mission contract are VPS Platform-owned');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['scripts/create-web-release-manifest.mjs','scripts/list-web-release-files.mjs','scripts/release/desktop-reuse-fallback.mjs','test/desktop-release-reuse.test.ts','test/desktop-reuse-fallback.test.ts'])==='vps-platform','desktop release packaging and verified reuse recovery are VPS Platform-owned infrastructure');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['deploy/awh-control-plane/remote-deploy-control-plane.sh','scripts/release/desktop-reuse-fallback.mjs','hub/src/HubCapabilityRegistryService.php'])==='vps-platform','platform deployment, desktop reuse recovery and execution authority remain one VPS Platform track');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['config/continuous-improvement-policy.json','config/kruart-engineering-eval.json','hub/src/HubVerificationIntelligence.php','hub/tests/verification-intelligence.php'])==='vps-platform','continuous improvement policy, classifier and eval authority are VPS Platform-owned');
ep(!isset($p['policyFamilies'])&&!isset($p['planBeforeCall'])&&!isset($p['quotaAware']),'retired owner-model fields are absent');
echo "AWH Execution Context: PASS\n";
