<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/src/HubCapabilityRegistryService.php';
require_once dirname(__DIR__) . '/src/HubUpdateTargetRegistry.php';
function ep(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);}
$p=HubCapabilityRegistryService::executionPolicy();
ep(($p['version']??null)==='2.3-project-admission','project-admission execution policy version');
ep(($p['mode']??null)==='CONTEXT_ONLY'&&($p['enforcement']??null)==='ADVISORY','context is non-prescriptive');
ep(($p['sourceAuthorityRequiredForMutation']??false)===true&&($p['singleWriterMutationBoundary']??false)===true&&($p['mutationBoundary']??null)==='CONFLICTING_RESOURCE','integrity boundary remains enforced');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.platform.release','VPS')==='CANONICAL:DEPLOY:VPS_PLATFORM','platform release has host-global track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.core.release','VPS')==='CANONICAL:DEPLOY:AWH','AWH release has its own track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.learnlab.release','VPS')==='CANONICAL:DEPLOY:BAY_LEARNLAB','LearnLab release has its own track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('system.assessment.release','VPS')==='CANONICAL:DEPLOY:BAY_ASSESSMENT','Assessment release has its own track');
ep(HubCapabilityRegistryService::mutationResourceForExecution('source.promote','VPS')==='CANONICAL:SOURCE','source promotion remains canonical-source scoped');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:AWH','project-a','CANDIDATE','project-a')===false,'candidate mission does not block AWH deploy');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:AWH','project-a','CANONICAL:DEPLOY:BAY_LEARNLAB','project-b')===false,'different release tracks can deploy independently');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:DEPLOY:VPS_PLATFORM','platform','CANONICAL:DEPLOY:AWH','project-a')===true,'platform deploy blocks another deploy while shared host runtime mutates');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:SOURCE','project-a','CANONICAL:DEPLOY:AWH','project-a')===true,'same-project source promotion interlocks with deploy');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('CANONICAL:SOURCE','project-a','CANONICAL:DEPLOY:BAY_LEARNLAB','project-b')===false,'different-project source promotion remains independent');
ep(HubCapabilityRegistryService::mutationResourcesConflictForProjects('RESOURCE:RELEASE_STAGE','project-a','CANONICAL:DEPLOY:AWH','project-a')===true,'same-project staging interlocks with deploy');
ep(HubCapabilityRegistryService::mutationResourceIsGlobal('CANONICAL:DEPLOY:VPS_PLATFORM')===true,'VPS Platform is host-global');
ep(HubCapabilityRegistryService::mutationResourceIsGlobal('CANONICAL:DEPLOY:AWH')===false,'AWH deploy is not host-global');
ep(HubCapabilityRegistryService::mutationResourcesConflict('CANONICAL:SOURCE','CANONICAL:SOURCE')===true,'same canonical resource serializes');
ep(HubCapabilityRegistryService::mutationResourcesConflict('CANONICAL:PROJECT','CANDIDATE')===true,'unknown canonical mutations fail closed');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['config/execution-policy.json','hub/src/HubControlPlaneService.php','web/updates.js'])==='vps-platform','Platform-owned change plus shared Update Center integration stays on VPS Platform track');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['web/app.js','hub/src/HubControlPlaneService.php'])==='awh','AWH-owned change plus shared Update Center integration stays on AWH track');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['config/execution-policy.json','web/app.js'])===null,'true mixed AWH and VPS Platform change-set is rejected');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['scripts/qa/test-singleflight.mjs','test/test-singleflight.test.mjs'])==='vps-platform','QA singleflight infrastructure is VPS Platform-owned');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['scripts/ops/run-release-qa-isolated.sh','test/bounded-deploy-mission.test.ts'])==='vps-platform','isolated release QA runner and mission contract are VPS Platform-owned');
ep(HubUpdateTargetRegistry::releaseTrackForPaths('awh',['config/continuous-improvement-policy.json','config/kruart-engineering-eval.json','hub/src/HubVerificationIntelligence.php','hub/tests/verification-intelligence.php'])==='vps-platform','continuous improvement policy, classifier and eval authority are VPS Platform-owned');
ep(!isset($p['policyFamilies'])&&!isset($p['planBeforeCall'])&&!isset($p['quotaAware']),'retired owner-model fields are absent');
echo "AWH Execution Context: PASS\n";
