<?php

declare(strict_types=1);

foreach (['HubSchemaMigration','HubEnrollmentApiMigration','HubControlPlaneMigration','HubOwnerAuthMigration','HubAssistantWorkstreamMigration','HubWorkspaceContinuityMigration','HubUnifiedWorkspaceMigration','HubFinalProductMigration','HubFoundingMemoryMigration','HubSelfServiceMigration','HubCentralProjectAuthorityMigration','HubAnywhereExecutionMigration','HubCostAwareAiMigration','HubAutomationMigration','HubSelfSufficientAiMigration','HubAiGovernanceService','HubAiQualificationService','HubAiProviderAdapter','HubOpenAiProviderAdapter','HubProviderCredentialStore','HubNativeAgentService','HubEnrollmentService'] as $class) require_once dirname(__DIR__) . '/src/' . $class . '.php';
function m16_assert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function m16_uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
function m16_clean(string $root):void{if(!is_dir($root))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$x=$f->getPathname();$f->isDir()&&!$f->isLink()?@rmdir($x):@unlink($x);}@rmdir($root);}
function m16_expect(string $code,callable $fn,string $message):void{try{$fn();}catch(Throwable $e){$actual=property_exists($e,'codeName')?$e->codeName:'';m16_assert($actual===$code,$message.': '.$actual);return;}throw new RuntimeException($message.': accepted');}
function m16_route_context(PDO $pdo,string $owner,string $project,string $capability,string $at):array{$task=m16_uuid();$execution=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,:goal,'QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$task,'user'=>$owner,'project'=>$project,'goal'=>'M16 '.$capability,'key'=>'m16-'.substr(hash('sha256',$task),0,24),'at'=>$at]);$pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS',:capability,'QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$execution,'task'=>$task,'project'=>$project,'capability'=>$capability,'at'=>$at]);return [$task,$execution];}
if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){fwrite(STDOUT,"AWH M16 Self-Sufficient AI: SKIP pdo_sqlite unavailable\n");exit(77);}
$root=sys_get_temp_dir().'/awh-m16-'.bin2hex(random_bytes(6));$base=dirname(__DIR__);$now='2026-08-29T01:45:00+00:00';
$owner='223b45c0-23e1-408d-ae0f-ac5eca7f6900';$project='113b45c0-23e1-408d-ae0f-ac5eca7f6900';
try{
 mkdir($root,0700,true);$db=$root.'/awh.sqlite';$pdo=new PDO('sqlite:'.$db,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec(file_get_contents($base.'/schema.sql'));
 foreach(['enrollment_rate_limits','device_project_memberships','device_tokens','pairing_projects','pairing_codes','user_project_memberships','device_enrollments','owner_bootstrap','hub_users'] as $table)$pdo->exec('DROP TABLE IF EXISTS '.$table);
 $pdo->prepare('INSERT INTO projects(project_id,name,type,created_at,source_revision,observed_at,provenance) VALUES(:id,:name,:type,:at,NULL,:at,:p)')->execute(['id'=>$project,'name'=>'M16 Project','type'=>'php','at'=>$now,'p'=>'m16-fixture']);
 m16_assert(HubSchemaMigration::apply($db,$base.'/migrations/001_m3e_enrollment.sql',$now,false,$base.'/schema.sql')==='applied','M3E');
 m16_assert(HubEnrollmentApiMigration::apply($db,$base.'/migrations/002_m3e2_enrollment_api.sql',$now)==='applied','M3E2');HubEnrollmentService::openExisting($db)->initializeOwner($owner,'Art',[$project],$now);
 $chain=[[HubControlPlaneMigration::class,'003_m4_control_plane.sql'],[HubOwnerAuthMigration::class,'004_owner_auth.sql'],[HubAssistantWorkstreamMigration::class,'005_assistant_workstream.sql'],[HubWorkspaceContinuityMigration::class,'006_workspace_continuity.sql'],[HubUnifiedWorkspaceMigration::class,'007_unified_workspace.sql'],[HubFinalProductMigration::class,'008_final_product.sql'],[HubFoundingMemoryMigration::class,'009_founding_memory.sql'],[HubSelfServiceMigration::class,'010_self_service.sql'],[HubCentralProjectAuthorityMigration::class,'011_central_project_authority.sql'],[HubAnywhereExecutionMigration::class,'012_anywhere_execution_fabric.sql'],[HubCostAwareAiMigration::class,'013_cost_aware_ai.sql'],[HubAutomationMigration::class,'014_automations.sql']];
 foreach($chain as [$migration,$sql])m16_assert($migration::apply($db,$base.'/migrations/'.$sql,$now)==='applied',$sql);
 $canonicalBefore=[];foreach(['projects','control_conversations','control_memory_records','control_tasks','control_task_executions','control_artifacts','control_approvals','control_workers','control_automations'] as $table)$canonicalBefore[$table]=(int)$pdo->query("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='$table'")->fetchColumn();
 m16_assert(HubSelfSufficientAiMigration::apply($db,$base.'/migrations/015_self_sufficient_ai.sql',$now)==='applied','M16 migration');m16_assert(HubSelfSufficientAiMigration::apply($db,$base.'/migrations/015_self_sufficient_ai.sql',$now)==='already-applied','M16 idempotence');
 m16_assert((int)$pdo->query('PRAGMA user_version')->fetchColumn()===16,'M16 version');m16_assert($pdo->query('PRAGMA foreign_key_check')->fetchAll()===[],'M16 foreign keys');m16_assert($pdo->query('PRAGMA integrity_check')->fetchColumn()==='ok','M16 integrity');
 foreach($canonicalBefore as $table=>$present)m16_assert((int)$pdo->query("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='$table'")->fetchColumn()===$present,'canonical authority preserved '.$table);
 m16_assert((int)$pdo->query("SELECT COUNT(*) FROM control_ai_models WHERE provider_id='openai' AND lifecycle='PRODUCTION'")->fetchColumn()>=3,'grandfathered production models');
 $task=m16_uuid();$execution=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,'M16 route test','QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$task,'user'=>$owner,'project'=>$project,'key'=>'m16-'.substr(hash('sha256',$task),0,24),'at'=>$now]);
 $pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS','agent.conversation','QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$execution,'task'=>$task,'project'=>$project,'at'=>$now]);
 $governance=new HubAiGovernanceService($pdo);$catalog=$governance->catalog();m16_assert(count($catalog['models'])>=3,'catalog visible');
 foreach(['project.read','project.search','project.mutate.assisted'] as $capability){[$aliasTask,$aliasExecution]=m16_route_context($pdo,$owner,$project,$capability,$now);$aliasRoute=$governance->selectModel($owner,$project,$aliasExecution,$aliasTask,'openai',$capability,'INTERNAL','BALANCED',['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],2000,600,1000000,['routing'=>'m16-alias-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now);$decision=$pdo->prepare('SELECT required_capability FROM control_ai_route_decisions WHERE route_id=:route');$decision->execute(['route'=>$aliasRoute['routeId']]);m16_assert(($decision->fetchColumn()??null)===$capability,'canonical capability preserved '.$capability);m16_assert($aliasRoute['providerId']==='openai','bounded provider capability alias '.$capability);}
 [$crossTask,$crossExecution]=m16_route_context($pdo,$owner,$project,'project.read',$now);$crossRoute=$governance->selectAcrossProviders($owner,$project,$crossExecution,$crossTask,['openai'],'project.read','INTERNAL','BALANCED',['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],2000,600,1000000,['routing'=>'m16-alias-cross-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now);m16_assert($crossRoute['providerId']==='openai','cross-provider bounded capability alias');
 foreach(['project.mutate.text','artifact.object'] as $capability){[$closedTask,$closedExecution]=m16_route_context($pdo,$owner,$project,$capability,$now);m16_expect('AI_ROUTE_UNAVAILABLE',fn()=>$governance->selectModel($owner,$project,$closedExecution,$closedTask,'openai',$capability,'INTERNAL','BALANCED',[],2000,600,1000000,['routing'=>'m16-alias-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now),'unregistered capability remains fail closed '.$capability);}
 $route=$governance->selectModel($owner,$project,$execution,$task,'openai','agent.conversation','INTERNAL','BALANCED',['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],2000,600,1000000,['routing'=>'m16-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now);m16_assert($route['providerId']==='openai'&&is_string($route['modelId']),'route selected');
 $outcome=$governance->recordOutcome($route['routeId'],'PASSED','PASS',0,850,$route['estimatedMicrounits'],false,false,[],'2026-08-29T01:46:00+00:00');m16_assert($outcome['savedMicrounits']>=0,'savings evidence');m16_assert($governance->savingsSummary($owner,$project)['successfulOrAttemptedTasks']===1,'savings summary');
 $selected=$route['modelId'];$pdo->prepare("INSERT INTO control_ai_model_health(provider_id,model_id,window_started_at,attempts,successes,timeouts,rate_limits,malformed_responses,tool_failures,total_latency_ms,total_cost_microunits,circuit_state,circuit_until,updated_at) VALUES('openai',:model,:at,5,0,3,2,0,0,5000,0,'OPEN',:until,:at) ON CONFLICT(provider_id,model_id) DO UPDATE SET circuit_state='OPEN',circuit_until=:until,attempts=5,successes=0,timeouts=3,rate_limits=2,updated_at=:at")->execute(['model'=>$selected,'at'=>$now,'until'=>'2026-08-29T02:00:00+00:00']);
 $task2=m16_uuid();$execution2=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,'fallback','QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$task2,'user'=>$owner,'project'=>$project,'key'=>'m16-'.substr(hash('sha256',$task2),0,24),'at'=>$now]);$pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS','agent.conversation','QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$execution2,'task'=>$task2,'project'=>$project,'at'=>$now]);
 $fallback=$governance->selectModel($owner,$project,$execution2,$task2,'openai','agent.conversation','INTERNAL','BALANCED',['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],2000,600,1000000,['routing'=>'m16-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now);m16_assert($fallback['modelId']!==$selected,'open circuit model excluded');
 $qualification=new HubAiQualificationService($pdo);$qualification->registerProvider('fixture-ai','Fixture AI','API','METERED','INTERNAL',[],$now);$qualification->registerModel('fixture-ai','fixture-model','Fixture Model',['text','tool-calling'],70,75,20,'INTERNAL',[],$now);
 $qualification->recordQualification('fixture-ai','fixture-model','awh-core','v0','legacy-failure',4000,false,900,300,3000,null,hash('sha256','legacy-failure'),[],'2026-08-29T01:40:00+00:00');
 foreach([['thai-chat',8500],['tool-json',9000],['coding-debug',8800]] as [$taskType,$score])$qualification->recordQualification('fixture-ai','fixture-model','awh-core','v1',$taskType,$score,true,400,100,null,9500,hash('sha256',$taskType),[],$now);
 $promoted=$qualification->promoteModel('fixture-ai','fixture-model','PRODUCTION',$now);m16_assert($promoted['lifecycle']==='production'&&$promoted['qualification']['passingTaskTypes']===3,'qualified model promoted');
 $qualification->registerModel('fixture-ai','unqualified-model','Unqualified Model',['text'],50,50,50,'INTERNAL',[],$now);$qualification->recordQualification('fixture-ai','unqualified-model','awh-core','v1','thai-chat',5000,false,500,100,2000,null,hash('sha256','fail'),[],$now);m16_expect('AI_PROMOTION_EVIDENCE_REQUIRED',fn()=>$qualification->promoteModel('fixture-ai','unqualified-model','PRODUCTION',$now),'unqualified production blocked');
 $pdo->prepare("INSERT INTO control_execution_provider_capabilities(provider_id,capability,version,cost_rank,quality_rank,latency_rank,enabled,observed_at,expires_at,metadata_json) VALUES('fixture-ai','agent.conversation','v1',10,85,20,1,:at,NULL,'{}')")->execute(['at'=>$now]);
 $rate=m16_uuid();$pdo->prepare("INSERT INTO control_provider_model_rates(rate_id,provider_id,model,service_tier,accounting_currency,input_microunits_per_million,cached_input_microunits_per_million,cache_write_microunits_per_million,output_microunits_per_million,provider_currency,provider_input_microunits_per_million,provider_cached_input_microunits_per_million,provider_cache_write_microunits_per_million,provider_output_microunits_per_million,fx_microunits_thb_per_usd,effective_at,observed_at,source_uri,source_label,active,metadata_json) VALUES(:id,'fixture-ai','fixture-model','DEFAULT','THB',100,0,0,200,'THB',100,0,0,200,1000000,:at,:at,'fixture://rate','fixture',1,'{}')")->execute(['id'=>$rate,'at'=>$now]);
 $taskMulti=m16_uuid();$executionMulti=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,'multi provider','QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$taskMulti,'user'=>$owner,'project'=>$project,'key'=>'m16-'.substr(hash('sha256',$taskMulti),0,24),'at'=>$now]);$pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS','agent.conversation','QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$executionMulti,'task'=>$taskMulti,'project'=>$project,'at'=>$now]);
 $multi=$governance->selectAcrossProviders($owner,$project,$executionMulti,$taskMulti,['openai','fixture-ai'],'agent.conversation','INTERNAL','SAVER',['fixture-ai:fixture-model'],2000,600,1000000,['routing'=>'m16-multi-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now);m16_assert($multi['providerId']==='fixture-ai'&&$multi['modelId']==='fixture-model','cross-provider qualified route');m16_expect('AI_ROUTE_CONTEXT_INVALID',fn()=>$governance->selectAcrossProviders($owner,$project,$executionMulti,$taskMulti,['fixture-ai'],'project.mutate','INTERNAL','SAVER',[],100,100,1000,[],$now),'execution capability mismatch blocked');
 $pdo->prepare("INSERT INTO control_provider_policies(provider_id,enabled,model_fast,model_balanced,model_strong,monthly_budget_microunits,warning_microunits,input_microunits_per_million,output_microunits_per_million,routing_strategy,pricing_mode,service_tier,updated_by_user_id,updated_at) VALUES('fixture-ai',1,'fixture-model','fixture-model','fixture-model',1000000,800000,1,1,'SAVER','CATALOG','DEFAULT',:owner,:at)")->execute(['owner'=>$owner,'at'=>$now]);
 $runtimeRoot=$root.'/runtime-provider-credentials';mkdir($runtimeRoot,0700,true);$fixtureStore=new HubProviderCredentialStore($runtimeRoot,'fixture-ai');$fixtureStore->replace('fixture-runtime-secret-12345');
 $openaiRuntimeStore=new HubProviderCredentialStore($runtimeRoot,'openai');$openaiRuntimeStore->replace('sk-'.str_repeat('P',30));
 $setFailoverHealth=static function()use($pdo,$now,$owner):void{$openaiPolicy=$pdo->prepare("INSERT INTO control_provider_policies(provider_id,enabled,model_fast,model_balanced,model_strong,monthly_budget_microunits,warning_microunits,input_microunits_per_million,output_microunits_per_million,routing_strategy,pricing_mode,service_tier,updated_by_user_id,updated_at) VALUES('openai',1,'gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol',1000000,800000,1,1,'BALANCED','CATALOG','DEFAULT',:owner,:at) ON CONFLICT(provider_id) DO UPDATE SET enabled=1,routing_strategy='BALANCED',updated_by_user_id=:owner,updated_at=:at");$openaiPolicy->execute(['owner'=>$owner,'at'=>$now]);$pdo->exec("UPDATE control_provider_model_rates SET input_microunits_per_million=100000000,output_microunits_per_million=100000000,provider_input_microunits_per_million=100000000,provider_output_microunits_per_million=100000000 WHERE provider_id='fixture-ai' AND model='fixture-model' AND active=1");foreach(['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'] as $model){$h=$pdo->prepare("INSERT INTO control_ai_model_health(provider_id,model_id,window_started_at,attempts,successes,timeouts,rate_limits,malformed_responses,tool_failures,total_latency_ms,total_cost_microunits,circuit_state,circuit_until,updated_at) VALUES('openai',:model,:at,10,10,0,0,0,0,1000,0,'CLOSED',NULL,:at) ON CONFLICT(provider_id,model_id) DO UPDATE SET attempts=10,successes=10,timeouts=0,rate_limits=0,malformed_responses=0,tool_failures=0,circuit_state='CLOSED',circuit_until=NULL,updated_at=:at");$h->execute(['model'=>$model,'at'=>$now]);}$h=$pdo->prepare("INSERT INTO control_ai_model_health(provider_id,model_id,window_started_at,attempts,successes,timeouts,rate_limits,malformed_responses,tool_failures,total_latency_ms,total_cost_microunits,circuit_state,circuit_until,updated_at) VALUES('fixture-ai','fixture-model',:at,10,0,0,0,0,0,1000,0,'CLOSED',NULL,:at) ON CONFLICT(provider_id,model_id) DO UPDATE SET attempts=10,successes=0,timeouts=0,rate_limits=0,malformed_responses=0,tool_failures=0,circuit_state='CLOSED',circuit_until=NULL,updated_at=:at");$h->execute(['at'=>$now]);};
 $setFailoverHealth();[$failTask,$failExecution]=m16_route_context($pdo,$owner,$project,'agent.conversation',$now);$failConversation=m16_uuid();$failMessage=m16_uuid();$pdo->prepare('INSERT INTO control_conversations(conversation_id,user_id,project_id,created_at,updated_at,last_task_id) VALUES(:id,:user,:project,:at,:at,NULL)')->execute(['id'=>$failConversation,'user'=>$owner,'project'=>$project,'at'=>$now]);$pdo->prepare("INSERT INTO control_conversation_messages(message_id,conversation_id,task_id,message_kind,sequence_no,body,idempotency_key,source_event_id,metadata_json,created_at) VALUES(:id,:conversation,NULL,'USER',1,'bounded provider failover',NULL,NULL,NULL,:at)")->execute(['id'=>$failMessage,'conversation'=>$failConversation,'at'=>$now]);
 $rateLimitPrimary=new class implements HubAiProviderAdapter{public int $calls=0;public function providerId():string{return 'openai';}public function call(array $payload,string $credential):array{$this->calls++;if($credential!=='sk-'.str_repeat('P',30))throw new RuntimeException('wrong openai fixture credential');throw new HubAiProviderAdapterException('fixture rate limit','PROVIDER_RATE_LIMITED',['provider'=>'openai','operation'=>'responses','category'=>'rate_limit','retryable'=>true,'retryAfterSeconds'=>120]);}};
 $failoverSecondary=new class implements HubAiProviderAdapter{public int $calls=0;public function providerId():string{return 'fixture-ai';}public function call(array $payload,string $credential):array{$this->calls++;if(($payload['model']??null)!=='fixture-model'||$credential!=='fixture-runtime-secret-12345')throw new RuntimeException('wrong fallback fixture dispatch');return ['output_text'=>'fallback provider completed','usage'=>['input_tokens'=>80,'output_tokens'=>18]];}};
 $failoverAgent=new HubNativeAgentService($pdo,null,null,$openaiRuntimeStore,$rateLimitPrimary,[$failoverSecondary],['fixture-ai'=>$fixtureStore]);$executionCountBefore=(int)$pdo->query("SELECT COUNT(*) FROM control_task_executions WHERE task_id='$failTask'")->fetchColumn();$failoverResult=$failoverAgent->respond($owner,$project,$failConversation,$failMessage,'งานทั่วไปแบบสมดุล',[],[],$now,[],['executionId'=>$failExecution,'taskId'=>$failTask,'capability'=>'agent.conversation','dataClassification'=>'INTERNAL','routingPolicyVersion'=>'p2-failover-v1']);m16_assert(($failoverResult['provider']??null)==='fixture-ai'&&($failoverResult['summary']??null)==='fallback provider completed'&&($failoverResult['providerAttempts']??null)===2&&($failoverResult['failoverUsed']??null)===true,'retryable provider pressure fails over exactly once');m16_assert($rateLimitPrimary->calls===1&&$failoverSecondary->calls===1,'bounded failover calls primary and one alternate exactly once');m16_assert((int)$pdo->query("SELECT COUNT(*) FROM control_task_executions WHERE task_id='$failTask'")->fetchColumn()===$executionCountBefore,'provider failover never creates a shadow execution');
 $failUsage=$pdo->prepare('SELECT provider_id,status,COUNT(*) AS n FROM control_provider_usage WHERE message_id=:message GROUP BY provider_id,status ORDER BY provider_id,status');$failUsage->execute(['message'=>$failMessage]);$failUsageRows=$failUsage->fetchAll();m16_assert(count($failUsageRows)===2&&array_column($failUsageRows,'provider_id')===['fixture-ai','openai'],'failover keeps per-provider usage evidence');m16_assert((int)$pdo->query("SELECT COUNT(*) FROM control_ai_route_decisions WHERE execution_id='$failExecution'")->fetchColumn()===2,'failover records exactly two governance route decisions on the same execution');$failOutcome=$pdo->query("SELECT o.status FROM control_ai_outcomes o JOIN control_ai_route_decisions r ON r.route_id=o.route_id WHERE r.execution_id='$failExecution' ORDER BY o.status")->fetchAll(PDO::FETCH_COLUMN);m16_assert($failOutcome===['FAILED','PASSED'],'failover preserves failed and successful governance outcomes');
 $setFailoverHealth();[$authTask,$authExecution]=m16_route_context($pdo,$owner,$project,'agent.conversation',$now);$authConversation=m16_uuid();$authMessage=m16_uuid();$pdo->prepare('INSERT INTO control_conversations(conversation_id,user_id,project_id,created_at,updated_at,last_task_id) VALUES(:id,:user,:project,:at,:at,NULL)')->execute(['id'=>$authConversation,'user'=>$owner,'project'=>$project,'at'=>$now]);$pdo->prepare("INSERT INTO control_conversation_messages(message_id,conversation_id,task_id,message_kind,sequence_no,body,idempotency_key,source_event_id,metadata_json,created_at) VALUES(:id,:conversation,NULL,'USER',1,'auth must not fail over',NULL,NULL,NULL,:at)")->execute(['id'=>$authMessage,'conversation'=>$authConversation,'at'=>$now]);$authPrimary=new class implements HubAiProviderAdapter{public int $calls=0;public function providerId():string{return 'openai';}public function call(array $payload,string $credential):array{$this->calls++;throw new HubAiProviderAdapterException('fixture auth failure','PROVIDER_AUTH_FAILED',['provider'=>'openai','operation'=>'responses','category'=>'auth','retryable'=>false]);}};$authSecondary=new class implements HubAiProviderAdapter{public int $calls=0;public function providerId():string{return 'fixture-ai';}public function call(array $payload,string $credential):array{$this->calls++;return ['output_text'=>'must not run','usage'=>['input_tokens'=>1,'output_tokens'=>1]];}};$authAgent=new HubNativeAgentService($pdo,null,null,$openaiRuntimeStore,$authPrimary,[$authSecondary],['fixture-ai'=>$fixtureStore]);m16_expect('PROVIDER_AUTH_FAILED',fn()=>$authAgent->respond($owner,$project,$authConversation,$authMessage,'งานทั่วไปแบบสมดุล',[],[],$now,[],['executionId'=>$authExecution,'taskId'=>$authTask,'capability'=>'agent.conversation','dataClassification'=>'INTERNAL','routingPolicyVersion'=>'p2-auth-v1']),'auth failure never provider-failovers');m16_assert($authPrimary->calls===1&&$authSecondary->calls===0,'auth failure stops before alternate provider dispatch');m16_assert((int)$pdo->query("SELECT COUNT(*) FROM control_ai_route_decisions WHERE execution_id='$authExecution'")->fetchColumn()===1,'auth failure retains one governance route decision only');
 $setFailoverHealth();[$toolFailTask,$toolFailExecution]=m16_route_context($pdo,$owner,$project,'agent.conversation',$now);$toolFailPrimary=new class implements HubAiProviderAdapter{public int $calls=0;public function providerId():string{return 'openai';}public function call(array $payload,string $credential):array{$this->calls++;throw new HubAiProviderAdapterException('fixture rate limit','PROVIDER_RATE_LIMITED',['provider'=>'openai','operation'=>'responses','category'=>'rate_limit','retryable'=>true]);}};$toolFailSecondary=new class implements HubAiProviderAdapter{public int $calls=0;public function providerId():string{return 'fixture-ai';}public function call(array $payload,string $credential):array{$this->calls++;return ['output_text'=>'must not run','usage'=>['input_tokens'=>1,'output_tokens'=>1]];}};$toolNoFailoverAgent=new HubNativeAgentService($pdo,null,null,$openaiRuntimeStore,$toolFailPrimary,[$toolFailSecondary],['fixture-ai'=>$fixtureStore]);m16_expect('PROVIDER_RATE_LIMITED',fn()=>$toolNoFailoverAgent->respondWithTools($owner,$project,null,null,'read one bounded source file',[],[],[],[['type'=>'function','name'=>'project_read_text','description'=>'Read one bounded fixture file.','parameters'=>['type'=>'object','additionalProperties'=>false,'properties'=>['path'=>['type'=>'string']],'required'=>['path']]]],static fn(string $name,array $arguments):array=>['tool'=>$name],$now,['executionId'=>$toolFailExecution,'taskId'=>$toolFailTask,'capability'=>'agent.conversation','dataClassification'=>'INTERNAL','routingPolicyVersion'=>'p2-tool-v1']),'tool loop does not cross-provider replay after dispatch failure');m16_assert($toolFailPrimary->calls===1&&$toolFailSecondary->calls===0,'tool loop leaves transient failure to durable retry policy rather than cross-provider replay');
 $toolAdapter=new class implements HubAiProviderAdapter { public int $calls=0; public array $payloads=[]; public function providerId():string{return 'fixture-ai';} public function call(array $payload,string $credential):array{$this->payloads[]=$payload;$this->calls++;if($credential!=='fixture-runtime-secret-12345')throw new RuntimeException('wrong tool fixture credential');if($this->calls===1)return ['id'=>'resp-1234','output'=>[['type'=>'function_call','call_id'=>'call-1234','name'=>'project_read_text','arguments'=>'{"path":"TASKS.md"}']],'usage'=>['input_tokens'=>100,'output_tokens'=>20]];return ['id'=>'resp-5678','output_text'=>'tool loop passed','usage'=>['input_tokens'=>120,'output_tokens'=>25]];} };
 $toolAgent=new HubNativeAgentService($pdo,null,'fixture-runtime-secret-12345',$fixtureStore,$toolAdapter);$toolResult=$toolAgent->respondWithTools($owner,$project,null,null,'read one bounded source file',[],[],['source'=>'fixture'],[['type'=>'function','name'=>'project_read_text','description'=>'Read one bounded fixture file.','parameters'=>['type'=>'object','additionalProperties'=>false,'properties'=>['path'=>['type'=>'string']],'required'=>['path']]]],static fn(string $name,array $arguments):array=>['tool'=>$name,'path'=>(string)($arguments['path']??'')],$now,['executionId'=>$executionMulti,'taskId'=>$taskMulti,'capability'=>'agent.conversation','dataClassification'=>'INTERNAL','retryCount'=>0,'routingPolicyVersion'=>'m16-tool-test','promptPolicyVersion'=>'native-v1','toolPolicyVersion'=>'bounded-v1']);m16_assert(($toolResult['summary']??null)==='tool loop passed'&&count($toolAdapter->payloads)===2,'Responses tool loop completes through fixture adapter');foreach($toolAdapter->payloads as $payload)m16_assert(!array_key_exists('max_tool_calls',$payload),'Responses payload excludes unsupported max_tool_calls');
 $fakeAdapter=new class implements HubAiProviderAdapter { public function providerId():string{return 'fixture-ai';} public function call(array $payload,string $credential):array{if(($payload['model']??null)!=='fixture-model'||$credential!=='fixture-runtime-secret-12345')throw new RuntimeException('wrong fixture dispatch');return ['output_text'=>'fixture provider executed','usage'=>['input_tokens'=>100,'output_tokens'=>20]];} };
 $agent=new HubNativeAgentService($pdo,static function(array $payload,string $key):array{throw new RuntimeException('primary provider must not execute when fixture provider wins');},'sk-'.str_repeat('x',32),null,null,[$fakeAdapter],['fixture-ai'=>$fixtureStore]);
 $pdo->exec("UPDATE control_ai_provider_profiles SET current_availability='UNAVAILABLE' WHERE provider_id='openai'");
 $conversation=m16_uuid();$message=m16_uuid();$pdo->prepare('INSERT INTO control_conversations(conversation_id,user_id,project_id,created_at,updated_at,last_task_id) VALUES(:id,:user,:project,:at,:at,NULL)')->execute(['id'=>$conversation,'user'=>$owner,'project'=>$project,'at'=>$now]);$pdo->prepare("INSERT INTO control_conversation_messages(message_id,conversation_id,task_id,message_kind,sequence_no,body,idempotency_key,source_event_id,metadata_json,created_at) VALUES(:id,:conversation,NULL,'USER',1,'provider fabric',NULL,NULL,NULL,:at)")->execute(['id'=>$message,'conversation'=>$conversation,'at'=>$now]);
 $runtime=$agent->respond($owner,$project,$conversation,$message,'งานทั่วไปที่ควรประหยัด',[],[],$now,[],['executionId'=>$executionMulti,'taskId'=>$taskMulti,'capability'=>'agent.conversation','dataClassification'=>'INTERNAL','routingPolicyVersion'=>'m16-runtime-test']);m16_assert(($runtime['provider']??null)==='fixture-ai'&&($runtime['model']??null)==='fixture-model'&&($runtime['summary']??null)==='fixture provider executed','selected provider executes through native agent');
 $runtimeUsage=$pdo->prepare('SELECT provider_id,model FROM control_provider_usage WHERE message_id=:message ORDER BY created_at DESC LIMIT 1');$runtimeUsage->execute(['message'=>$message]);$runtimeRow=$runtimeUsage->fetch();m16_assert(is_array($runtimeRow)&&$runtimeRow['provider_id']==='fixture-ai'&&$runtimeRow['model']==='fixture-model','usage evidence binds selected runtime provider');
 $policy=m16_uuid();$pdo->prepare("INSERT INTO control_ai_budget_policies(policy_id,scope_kind,scope_ref,mode,daily_microunits,monthly_microunits,max_task_microunits,max_retry_microunits,max_retries,hard_limit,enabled,updated_by_user_id,updated_at,metadata_json) VALUES(:id,'GLOBAL','*','SAVER',0,0,1,0,1,1,1,:owner,:at,'{}')")->execute(['id'=>$policy,'owner'=>$owner,'at'=>$now]);
 $task3=m16_uuid();$execution3=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,'budget','QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$task3,'user'=>$owner,'project'=>$project,'key'=>'m16-'.substr(hash('sha256',$task3),0,24),'at'=>$now]);$pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS','agent.conversation','QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$execution3,'task'=>$task3,'project'=>$project,'at'=>$now]);
 m16_expect('AI_BUDGET_TASK_LIMIT',fn()=>$governance->selectModel($owner,$project,$execution3,$task3,'openai','agent.conversation','INTERNAL','SAVER',[],100000,5000,1000000,['routing'=>'m16-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now),'hard task budget');
 $credRoot=$root.'/credentials';mkdir($credRoot,0700,true);$openai=new HubProviderCredentialStore($credRoot);$openai->replace('sk-'.str_repeat('A',30));m16_assert($openai->read()==='sk-'.str_repeat('A',30),'OpenAI compatibility credential');$other=new HubProviderCredentialStore($credRoot,'gemini');$other->replace('opaque-provider-secret-12345');m16_assert($other->read()==='opaque-provider-secret-12345'&&is_file($credRoot.'/gemini.key'),'provider keyed credential');m16_expect('PROVIDER_CREDENTIAL_STORE_INVALID',fn()=>new HubProviderCredentialStore($credRoot,'../bad'),'provider path injection rejected');
 fwrite(STDOUT,"AWH M16 Self-Sufficient AI: PASS\n");
}finally{m16_clean($root);}
