<?php

declare(strict_types=1);

foreach (['HubSchemaMigration','HubEnrollmentApiMigration','HubControlPlaneMigration','HubOwnerAuthMigration','HubAssistantWorkstreamMigration','HubWorkspaceContinuityMigration','HubUnifiedWorkspaceMigration','HubFinalProductMigration','HubFoundingMemoryMigration','HubSelfServiceMigration','HubCentralProjectAuthorityMigration','HubAnywhereExecutionMigration','HubCostAwareAiMigration','HubAutomationMigration','HubSelfSufficientAiMigration','HubAiGovernanceService','HubProviderCredentialStore','HubEnrollmentService'] as $class) require_once dirname(__DIR__) . '/src/' . $class . '.php';
function m16_assert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function m16_uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
function m16_clean(string $root):void{if(!is_dir($root))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$x=$f->getPathname();$f->isDir()&&!$f->isLink()?@rmdir($x):@unlink($x);}@rmdir($root);}
function m16_expect(string $code,callable $fn,string $message):void{try{$fn();}catch(Throwable $e){$actual=property_exists($e,'codeName')?$e->codeName:'';m16_assert($actual===$code,$message.': '.$actual);return;}throw new RuntimeException($message.': accepted');}
if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){fwrite(STDOUT,"AWH M16 Self-Sufficient AI: SKIP pdo_sqlite unavailable\n");exit(77);}
$root=sys_get_temp_dir().'/awh-m16-'.bin2hex(random_bytes(6));$base=dirname(__DIR__);$now='2026-08-29T01:45:00+00:00';
$owner='223b45c0-23e1-408d-ae0f-ac5eca7f6900';$project='113b45c0-23e1-408d-ae0f-ac5eca7f6900';
try{
 mkdir($root,0700,true);$db=$root.'/awh.sqlite';$pdo=new PDO('sqlite:'.$db,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec(file_get_contents($base.'/schema.sql'));
 foreach(['enrollment_rate_limits','device_project_memberships','device_tokens','pairing_projects','pairing_codes','user_project_memberships','device_enrollments','owner_bootstrap','hub_users'] as $table)$pdo->exec('DROP TABLE IF EXISTS '.$table);
 $pdo->prepare('INSERT INTO projects(project_id,name,type,created_at,source_revision,observed_at,provenance) VALUES(:id,:name,:type,:at,NULL,:at,:p)')->execute(['id'=>$project,'name'=>'M16 Project','type'=>'php','at'=>$now,'p'=>'m16-fixture']);
 m16_assert(HubSchemaMigration::apply($db,$base.'/migrations/001_m3e_enrollment.sql',$now,false,$base.'/schema.sql')==='applied','M3E');
 m16_assert(HubEnrollmentApiMigration::apply($db,$base.'/migrations/002_m3e2_enrollment_api.sql',$now)==='applied','M3E2');HubEnrollmentService::openExisting($db)->initializeOwner($owner,'Art',[$project],$now);
 $chain=[[HubControlPlaneMigration::class,'003_m4_control_plane.sql'],[HubOwnerAuthMigration::class,'004_owner_auth.sql'],[HubAssistantWorkstreamMigration::class,'005_assistant_workstream.sql'],[HubWorkspaceContinuityMigration::class,'006_workspace_continuity.sql'],[HubUnifiedWorkspaceMigration::class,'007_unified_workspace.sql'],[HubFinalProductMigration::class,'008_final_product.sql'],[HubFoundingMemoryMigration::class,'009_founding_memory.sql'],[HubSelfServiceMigration::class,'010_self_service.sql'],[HubCentralProjectAuthorityMigration::class,'011_central_project_authority.sql'],[HubAnywhereExecutionMigration::class,'012_anywhere_execution_fabric.sql'],[HubCostAwareAiMigration::class,'013_cost_aware_ai.sql'],[HubAutomationMigration::class,'014_automations.sql']];
 foreach($chain as [$migration,$sql])m16_assert($migration::apply($db,$base.'/migrations/'.$sql,$now)==='applied',$sql);
 $canonicalBefore=[];foreach(['projects','control_conversations','control_memory_records','control_tasks','control_task_executions','control_artifacts','control_approvals','control_workers','control_automations'] as $table)$canonicalBefore[$table]=(int)$pdo->query("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='$table'")->fetchColumn();
 m16_assert(HubSelfSufficientAiMigration::apply($db,$base.'/migrations/015_self_sufficient_ai.sql',$now)==='applied','M16 migration');m16_assert(HubSelfSufficientAiMigration::apply($db,$base.'/migrations/015_self_sufficient_ai.sql',$now)==='already-applied','M16 idempotence');
 m16_assert((int)$pdo->query('PRAGMA user_version')->fetchColumn()===16,'M16 version');m16_assert($pdo->query('PRAGMA foreign_key_check')->fetchAll()===[],'M16 foreign keys');m16_assert($pdo->query('PRAGMA integrity_check')->fetchColumn()==='ok','M16 integrity');
 foreach($canonicalBefore as $table=>$present)m16_assert((int)$pdo->query("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='$table'")->fetchColumn()===$present,'canonical authority preserved '.$table);
 m16_assert((int)$pdo->query("SELECT COUNT(*) FROM control_ai_models WHERE provider_id='openai' AND lifecycle='PRODUCTION'")->fetchColumn()>=3,'grandfathered production models');
 $task=m16_uuid();$execution=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,'M16 route test','QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$task,'user'=>$owner,'project'=>$project,'key'=>'m16-'.substr(hash('sha256',$task),0,24),'at'=>$now]);
 $pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS','agent.conversation','QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$execution,'task'=>$task,'project'=>$project,'at'=>$now]);
 $governance=new HubAiGovernanceService($pdo);$catalog=$governance->catalog();m16_assert(count($catalog['models'])>=3,'catalog visible');
 $route=$governance->selectModel($owner,$project,$execution,$task,'openai','agent.conversation','INTERNAL','BALANCED',['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],2000,600,1000000,['routing'=>'m16-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now);m16_assert($route['providerId']==='openai'&&is_string($route['modelId']),'route selected');
 $outcome=$governance->recordOutcome($route['routeId'],'PASSED','PASS',0,850,$route['estimatedMicrounits'],false,false,[],'2026-08-29T01:46:00+00:00');m16_assert($outcome['savedMicrounits']>=0,'savings evidence');m16_assert($governance->savingsSummary($owner,$project)['successfulOrAttemptedTasks']===1,'savings summary');
 $selected=$route['modelId'];$pdo->prepare("INSERT INTO control_ai_model_health(provider_id,model_id,window_started_at,attempts,successes,timeouts,rate_limits,malformed_responses,tool_failures,total_latency_ms,total_cost_microunits,circuit_state,circuit_until,updated_at) VALUES('openai',:model,:at,5,0,3,2,0,0,5000,0,'OPEN',:until,:at) ON CONFLICT(provider_id,model_id) DO UPDATE SET circuit_state='OPEN',circuit_until=:until,attempts=5,successes=0,timeouts=3,rate_limits=2,updated_at=:at")->execute(['model'=>$selected,'at'=>$now,'until'=>'2026-08-29T02:00:00+00:00']);
 $task2=m16_uuid();$execution2=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,'fallback','QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$task2,'user'=>$owner,'project'=>$project,'key'=>'m16-'.substr(hash('sha256',$task2),0,24),'at'=>$now]);$pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS','agent.conversation','QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$execution2,'task'=>$task2,'project'=>$project,'at'=>$now]);
 $fallback=$governance->selectModel($owner,$project,$execution2,$task2,'openai','agent.conversation','INTERNAL','BALANCED',['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],2000,600,1000000,['routing'=>'m16-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now);m16_assert($fallback['modelId']!==$selected,'open circuit model excluded');
 $policy=m16_uuid();$pdo->prepare("INSERT INTO control_ai_budget_policies(policy_id,scope_kind,scope_ref,mode,daily_microunits,monthly_microunits,max_task_microunits,max_retry_microunits,max_retries,hard_limit,enabled,updated_by_user_id,updated_at,metadata_json) VALUES(:id,'GLOBAL','*','SAVER',0,0,1,0,1,1,1,:owner,:at,'{}')")->execute(['id'=>$policy,'owner'=>$owner,'at'=>$now]);
 $task3=m16_uuid();$execution3=m16_uuid();$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:id,:user,:project,'budget','QUEUED',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['id'=>$task3,'user'=>$owner,'project'=>$project,'key'=>'m16-'.substr(hash('sha256',$task3),0,24),'at'=>$now]);$pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:id,:task,:project,NULL,'VPS','agent.conversation','QUEUED',NULL,NULL,0,NULL,'{}',NULL,:at,:at)")->execute(['id'=>$execution3,'task'=>$task3,'project'=>$project,'at'=>$now]);
 m16_expect('AI_BUDGET_TASK_LIMIT',fn()=>$governance->selectModel($owner,$project,$execution3,$task3,'openai','agent.conversation','INTERNAL','SAVER',[],100000,5000,1000000,['routing'=>'m16-test','prompt'=>'prompt-test','tool'=>'tool-test'],$now),'hard task budget');
 $credRoot=$root.'/credentials';mkdir($credRoot,0700,true);$openai=new HubProviderCredentialStore($credRoot);$openai->replace('sk-'.str_repeat('A',30));m16_assert($openai->read()==='sk-'.str_repeat('A',30),'OpenAI compatibility credential');$other=new HubProviderCredentialStore($credRoot,'gemini');$other->replace('opaque-provider-secret-12345');m16_assert($other->read()==='opaque-provider-secret-12345'&&is_file($credRoot.'/gemini.key'),'provider keyed credential');m16_expect('PROVIDER_CREDENTIAL_STORE_INVALID',fn()=>new HubProviderCredentialStore($credRoot,'../bad'),'provider path injection rejected');
 fwrite(STDOUT,"AWH M16 Self-Sufficient AI: PASS\n");
}finally{m16_clean($root);}
