<?php

declare(strict_types=1);

foreach (['HubSchemaMigration','HubEnrollmentApiMigration','HubControlPlaneMigration','HubOwnerAuthMigration','HubAssistantWorkstreamMigration','HubWorkspaceContinuityMigration','HubUnifiedWorkspaceMigration','HubFinalProductMigration','HubFoundingMemoryMigration','HubSelfServiceMigration','HubCentralProjectAuthorityMigration','HubAnywhereExecutionMigration','HubEnrollmentService','HubOwnerAuthService','HubArtifactStore','HubControlPlaneService','HubControlPlaneRouter'] as $class) require_once dirname(__DIR__) . '/src/' . $class . '.php';

function m17_assert(bool $value, string $message): void { if (!$value) throw new RuntimeException($message); }
function m17_uuid(): string { $bytes = random_bytes(16); $bytes[6] = chr((ord($bytes[6]) & 15) | 64); $bytes[8] = chr((ord($bytes[8]) & 63) | 128); return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($bytes), 4)); }
function m17_clean(string $root): void { if (!is_dir($root)) return; $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST); foreach ($it as $file) { $path = $file->getPathname(); $file->isDir() && !$file->isLink() ? @rmdir($path) : @unlink($path); } @rmdir($root); }
function m17_json(array $value): string { return json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR); }
function m17_browser(string $session, string $csrf, string $type = 'application/json'): array { return ['CONTENT_TYPE' => $type, 'HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $session . '; awh_csrf=' . $csrf, 'HTTP_X_AWH_CSRF' => $csrf, 'HTTP_SEC_FETCH_SITE' => 'same-origin']; }
function m17_control(HubControlPlaneService $control, string $method, string $uri, array $server, array $payload): array { return HubControlPlaneRouter::dispatch($method, $uri, $server, $control, m17_json($payload)); }

if (!in_array('sqlite', PDO::getAvailableDrivers(), true)) { fwrite(STDOUT, "AWH M17 product verticals: SKIP pdo_sqlite unavailable\n"); exit(77); }

$root = sys_get_temp_dir() . '/awh-m17-' . bin2hex(random_bytes(6)); $base = dirname(__DIR__); $now = '2026-08-30T06:00:00+00:00'; $db = $root . '/awh.sqlite';
$artifactRoot = $root . '/artifacts'; $vaultRoot = $root . '/vault'; $workspaceRoot = $root . '/workspaces'; $owner = '223b45c0-23e1-408d-ae0f-ac5eca7f6900'; $project = '113b45c0-23e1-408d-ae0f-ac5eca7f6900'; $password = 'm17-owner-' . bin2hex(random_bytes(12));
putenv('AWH_CONTROL_ORIGIN=https://awh.test'); putenv('AWH_ARTIFACT_ROOT=' . $artifactRoot); putenv('AWH_PROJECT_VAULT_ROOT=' . $vaultRoot); putenv('AWH_TASK_WORKSPACE_ROOT=' . $workspaceRoot);
try {
    mkdir($root, 0700, true); foreach ([$artifactRoot, $vaultRoot, $workspaceRoot] as $directory) mkdir($directory, 0700, true);
    $pdo = new PDO('sqlite:' . $db, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]); $pdo->exec('PRAGMA foreign_keys = ON'); $pdo->exec(file_get_contents($base . '/schema.sql'));
    foreach (['enrollment_rate_limits','device_project_memberships','device_tokens','pairing_projects','pairing_codes','user_project_memberships','device_enrollments','owner_bootstrap','hub_users'] as $table) $pdo->exec('DROP TABLE IF EXISTS ' . $table);
    $pdo->prepare('INSERT INTO projects(project_id,name,type,created_at,source_revision,observed_at,provenance) VALUES(:id,:name,:type,:at,NULL,:at,:provenance)')->execute(['id' => $project, 'name' => 'M17 School', 'type' => 'school', 'at' => $now, 'provenance' => 'm17-fixture']);
    m17_assert(HubSchemaMigration::apply($db, $base . '/migrations/001_m3e_enrollment.sql', $now, false, $base . '/schema.sql') === 'applied', 'M3E');
    m17_assert(HubEnrollmentApiMigration::apply($db, $base . '/migrations/002_m3e2_enrollment_api.sql', $now) === 'applied', 'M3E2');
    HubEnrollmentService::openExisting($db)->initializeOwner($owner, 'Art Owner', [$project], $now);
    foreach ([[HubControlPlaneMigration::class, '003_m4_control_plane.sql'], [HubOwnerAuthMigration::class, '004_owner_auth.sql'], [HubAssistantWorkstreamMigration::class, '005_assistant_workstream.sql'], [HubWorkspaceContinuityMigration::class, '006_workspace_continuity.sql'], [HubUnifiedWorkspaceMigration::class, '007_unified_workspace.sql'], [HubFinalProductMigration::class, '008_final_product.sql'], [HubFoundingMemoryMigration::class, '009_founding_memory.sql'], [HubSelfServiceMigration::class, '010_self_service.sql'], [HubCentralProjectAuthorityMigration::class, '011_central_project_authority.sql'], [HubAnywhereExecutionMigration::class, '012_anywhere_execution_fabric.sql']] as [$migration, $sql]) m17_assert($migration::apply($db, $base . '/migrations/' . $sql, $now) === 'applied', $sql);
    $auth = HubOwnerAuthService::openExisting($db); $auth->provisionInitial('art', $password, $now); $session = $auth->login('art', $password, true, 'm17-browser', $now); $control = HubControlPlaneService::openExisting($db); $browser = m17_browser($session['sessionToken'], $session['csrfToken']);

    $document = m17_control($control, 'POST', '/api/v1/control/school/documents', $browser, ['schemaVersion' => 1, 'projectId' => $project, 'subject' => 'ขออนุมัติจัดกิจกรรมวันวิทยาศาสตร์', 'details' => 'ขออนุมัติจัดกิจกรรมเพื่อส่งเสริมการเรียนรู้ของนักเรียน โดยรายละเอียดงบประมาณจะกรอกตามข้อมูลจริง', 'idempotencyKey' => 'm17-document-0001']);
    m17_assert($document['status'] === 201, 'school document route accepts valid input'); $documentBody = json_decode($document['body'], true, 32, JSON_THROW_ON_ERROR); m17_assert(($documentBody['task']['state'] ?? null) === 'COMPLETED', 'school document task completes'); m17_assert(($documentBody['pipeline']['classification'] ?? null) === 'MEMORANDUM_REQUEST', 'document classification is durable'); m17_assert(($documentBody['pipeline']['templateId'] ?? null) === 'school-memorandum-v1', 'document template is durable');
    $documentArtifact = $documentBody['artifact']['artifactId'] ?? null; m17_assert(is_string($documentArtifact), 'school document creates canonical artifact'); $download = HubControlPlaneRouter::dispatch('GET', '/api/v1/control/artifacts/' . $documentArtifact . '/download', ['HTTP_COOKIE' => '__Host-awh_control_session=' . $session['sessionToken'], 'HTTP_SEC_FETCH_SITE' => 'same-origin'], $control, ''); m17_assert($download['status'] === 200 && isset($download['streamPath']), 'school document artifact downloads'); $documentHtml = (string) file_get_contents($download['streamPath']); m17_assert(str_contains($documentHtml, 'บันทึกข้อความ') && str_contains($documentHtml, 'ขออนุมัติจัดกิจกรรมวันวิทยาศาสตร์') && str_contains($documentHtml, 'ยังไม่ได้ระบุ'), 'school document is printable and never invents unknown fields');
    $duplicate = m17_control($control, 'POST', '/api/v1/control/school/documents', $browser, ['schemaVersion' => 1, 'projectId' => $project, 'subject' => 'ขออนุมัติจัดกิจกรรมวันวิทยาศาสตร์', 'details' => 'ขออนุมัติจัดกิจกรรมเพื่อส่งเสริมการเรียนรู้ของนักเรียน โดยรายละเอียดงบประมาณจะกรอกตามข้อมูลจริง', 'idempotencyKey' => 'm17-document-0001']); $duplicateBody = json_decode($duplicate['body'], true, 32, JSON_THROW_ON_ERROR); m17_assert($duplicate['status'] === 201 && ($duplicateBody['idempotent'] ?? false) === true && is_string($duplicateBody['artifact']['downloadUrl'] ?? null), 'school document is idempotent with artifact read-back');

    $conversation = m17_control($control, 'POST', '/api/v1/control/conversations/new', $browser, ['schemaVersion' => 2, 'projectId' => $project, 'title' => 'Universal Command']);
    $conversationBody = json_decode($conversation['body'], true, 32, JSON_THROW_ON_ERROR); $conversationId = $conversationBody['conversation']['conversationId'] ?? null; m17_assert($conversation['status'] === 201 && is_string($conversationId), 'universal command conversation is ready');
    $chatDocument = m17_control($control, 'POST', '/api/v1/control/conversations', $browser, ['schemaVersion' => 3, 'projectId' => $project, 'conversationId' => $conversationId, 'message' => 'สร้างบันทึกข้อความขอเบิกค่าน้ำมันไปราชการ', 'attachmentIds' => [], 'idempotencyKey' => 'm17-chat-document-0001']);
    $chatDocumentBody = json_decode($chatDocument['body'], true, 32, JSON_THROW_ON_ERROR); $chatTasks = $chatDocumentBody['tasks'] ?? []; $chatArtifacts = $chatDocumentBody['artifacts'] ?? []; $chatMessages = $chatDocumentBody['messages'] ?? [];
    m17_assert($chatDocument['status'] === 201 && count($chatTasks) === 1 && ($chatTasks[0]['state'] ?? null) === 'COMPLETED', 'document command routes to completed canonical task without Project Vault');
    m17_assert(count($chatArtifacts) === 1 && ($chatArtifacts[0]['kind'] ?? null) === 'school-document', 'document command returns its artifact in the same conversation');
    m17_assert(count(array_filter($chatMessages, static fn(array $message): bool => ($message['kind'] ?? null) === 'result' && str_contains((string)($message['body'] ?? ''), 'สร้างบันทึกข้อความให้แล้ว'))) === 1, 'document command returns a human-readable result in chat');
    $chatExecution = $pdo->query("SELECT executor_kind, required_capability, state, vault_revision_id FROM control_task_executions WHERE task_id='" . str_replace("'", "''", (string)$chatTasks[0]['taskId']) . "'")->fetch();
    m17_assert(is_array($chatExecution) && $chatExecution['executor_kind'] === 'VPS' && $chatExecution['required_capability'] === 'artifact.object' && $chatExecution['state'] === 'COMPLETED' && $chatExecution['vault_revision_id'] === null, 'document intent is routed before source engineering and never requires Vault');

    $factory = m17_control($control, 'POST', '/api/v1/control/project-factory', $browser, ['schemaVersion' => 1, 'name' => 'เว็บไซต์สหกรณ์โรงเรียน M17', 'objective' => 'ให้ครูและนักเรียนดูข่าวสาร รายการสินค้า และข้อมูลการดำเนินงานของสหกรณ์ได้จากมือถือ', 'type' => 'school-website', 'idempotencyKey' => 'm17-factory-0001']);
    m17_assert($factory['status'] === 201, 'project factory route accepts valid input'); $factoryBody = json_decode($factory['body'], true, 32, JSON_THROW_ON_ERROR); $factoryProject = $factoryBody['project']['projectId'] ?? null; m17_assert(is_string($factoryProject) && $factoryProject !== $project, 'project factory creates a canonical project'); m17_assert(($factoryBody['factory']['task']['state'] ?? null) === 'COMPLETED', 'project factory task completes'); m17_assert(($factoryBody['factory']['pipeline']['mode'] ?? null) === 'PROJECT_FACTORY_SCHOOL_WEBSITE', 'project factory pipeline is durable'); m17_assert(($factoryBody['factory']['pipeline']['preview'] ?? null) === 'READY' && ($factoryBody['factory']['pipeline']['validation'] ?? null) === 'PASS' && ($factoryBody['factory']['pipeline']['releaseReadiness'] ?? null) === 'OWNER_APPROVAL', 'project factory must produce a validated preview without faking deployment'); $factoryArtifact = $factoryBody['factory']['artifact']['artifactId'] ?? null; m17_assert(is_string($factoryArtifact) && ($factoryBody['factory']['artifact']['kind'] ?? null) === 'project-preview', 'project factory creates a canonical preview artifact');
    $factoryDuplicate = m17_control($control, 'POST', '/api/v1/control/project-factory', $browser, ['schemaVersion' => 1, 'name' => 'เว็บไซต์สหกรณ์โรงเรียน M17', 'objective' => 'ให้ครูและนักเรียนดูข่าวสาร รายการสินค้า และข้อมูลการดำเนินงานของสหกรณ์ได้จากมือถือ', 'type' => 'school-website', 'idempotencyKey' => 'm17-factory-0001']); $factoryDuplicateBody = json_decode($factoryDuplicate['body'], true, 32, JSON_THROW_ON_ERROR); m17_assert($factoryDuplicate['status'] === 201 && ($factoryDuplicateBody['idempotent'] ?? false) === true && ($factoryDuplicateBody['project']['projectId'] ?? null) === $factoryProject && is_string($factoryDuplicateBody['factory']['artifact']['downloadUrl'] ?? null), 'project factory is idempotent with artifact read-back');
    $factoryDownload = HubControlPlaneRouter::dispatch('GET', '/api/v1/control/artifacts/' . $factoryArtifact . '/download', ['HTTP_COOKIE' => '__Host-awh_control_session=' . $session['sessionToken'], 'HTTP_SEC_FETCH_SITE' => 'same-origin'], $control, ''); $factoryHtml = (string) file_get_contents($factoryDownload['streamPath']); m17_assert($factoryDownload['status'] === 200 && str_contains($factoryHtml, 'data-awh-project-preview="1"') && str_contains($factoryHtml, '<meta name="viewport"') && str_contains($factoryHtml, 'เว็บไซต์สหกรณ์โรงเรียน M17') && str_contains($factoryHtml, 'ข่าวสารสหกรณ์') && str_contains($factoryHtml, 'Build Studio phases') && str_contains($factoryHtml, 'ยังไม่ได้ deploy'), 'project factory preview is mobile-ready, usable and truthful');
    m17_assert((int) $pdo->query('SELECT COUNT(*) FROM control_tasks')->fetchColumn() === 3, 'document chat and product verticals use one canonical task authority'); m17_assert((int) $pdo->query('SELECT COUNT(*) FROM control_task_executions')->fetchColumn() === 3, 'document chat and product verticals use one canonical execution authority'); m17_assert((int) $pdo->query('SELECT COUNT(*) FROM control_artifacts')->fetchColumn() === 3 && (int) $pdo->query('SELECT COUNT(*) FROM control_artifact_objects')->fetchColumn() === 3, 'document chat and product verticals use one canonical artifact authority'); $capabilities = $pdo->query('SELECT required_capability FROM control_task_executions ORDER BY execution_id')->fetchAll(PDO::FETCH_COLUMN); m17_assert($capabilities === ['artifact.object', 'artifact.object', 'artifact.object'], 'generated executions use catalog-safe capability identities'); m17_assert((int) $pdo->query('SELECT COUNT(*) FROM control_execution_envelopes')->fetchColumn() === 3, 'generated executions have one capability envelope each'); m17_assert($pdo->query('PRAGMA integrity_check')->fetchColumn() === 'ok' && $pdo->query('PRAGMA foreign_key_check')->fetchAll() === [], 'M17 vertical slices preserve DB integrity/FK');
    fwrite(STDOUT, "AWH M17 product verticals: PASS\n");
} finally { putenv('AWH_CONTROL_ORIGIN'); putenv('AWH_ARTIFACT_ROOT'); putenv('AWH_PROJECT_VAULT_ROOT'); putenv('AWH_TASK_WORKSPACE_ROOT'); m17_clean($root); }
