<?php

declare(strict_types=1);
foreach(['HubSchemaMigration','HubEnrollmentApiMigration','HubControlPlaneMigration','HubOwnerAuthMigration','HubAssistantWorkstreamMigration','HubWorkspaceContinuityMigration','HubUnifiedWorkspaceMigration','HubFinalProductMigration','HubFoundingMemoryMigration','HubSelfServiceMigration','HubCentralProjectAuthorityMigration','HubAnywhereExecutionMigration','HubCostAwareAiMigration','HubAutomationMigration','HubSelfSufficientAiMigration','HubAccountHostingMigration','HubEnrollmentService','HubOwnerAuthService','HubManagedHostingService'] as $class)require_once dirname(__DIR__).'/src/'.$class.'.php';
function m17a(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);}function m17u():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}function m17clean(string $r):void{if(!is_dir($r))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($r,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f)$f->isDir()&&!$f->isLink()?@rmdir($f->getPathname()):@unlink($f->getPathname());@rmdir($r);}function m17code(string $code,callable $fn):void{try{$fn();}catch(Throwable $e){m17a(property_exists($e,'codeName')&&$e->codeName===$code,'expected '.$code.' got '.(property_exists($e,'codeName')?$e->codeName:get_class($e)));return;}throw new RuntimeException('expected '.$code);}
if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){echo "AWH M17 Account Hosting: SKIP\n";exit(77);} $root=sys_get_temp_dir().'/awh-m17-'.bin2hex(random_bytes(6));$base=dirname(__DIR__);$now=gmdate('c');$owner=m17u();$project=m17u();
try{mkdir($root,0700,true);$db=$root.'/awh.sqlite';$pdo=new PDO('sqlite:'.$db,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec(file_get_contents($base.'/schema.sql'));foreach(['enrollment_rate_limits','device_project_memberships','device_tokens','pairing_projects','pairing_codes','user_project_memberships','device_enrollments','owner_bootstrap','hub_users'] as $table)$pdo->exec('DROP TABLE IF EXISTS '.$table);$pdo->prepare('INSERT INTO projects(project_id,name,type,created_at,source_revision,observed_at,provenance) VALUES(:id,\'Registration Site\',\'php\',:at,NULL,:at,\'m17\')')->execute(['id'=>$project,'at'=>$now]);
 m17a(HubSchemaMigration::apply($db,$base.'/migrations/001_m3e_enrollment.sql',$now,false,$base.'/schema.sql')==='applied','m3e');m17a(HubEnrollmentApiMigration::apply($db,$base.'/migrations/002_m3e2_enrollment_api.sql',$now)==='applied','m3e2');HubEnrollmentService::openExisting($db)->initializeOwner($owner,'Owner',[$project],$now);$chain=[[HubControlPlaneMigration::class,'003_m4_control_plane.sql'],[HubOwnerAuthMigration::class,'004_owner_auth.sql'],[HubAssistantWorkstreamMigration::class,'005_assistant_workstream.sql'],[HubWorkspaceContinuityMigration::class,'006_workspace_continuity.sql'],[HubUnifiedWorkspaceMigration::class,'007_unified_workspace.sql'],[HubFinalProductMigration::class,'008_final_product.sql'],[HubFoundingMemoryMigration::class,'009_founding_memory.sql'],[HubSelfServiceMigration::class,'010_self_service.sql'],[HubCentralProjectAuthorityMigration::class,'011_central_project_authority.sql'],[HubAnywhereExecutionMigration::class,'012_anywhere_execution_fabric.sql'],[HubCostAwareAiMigration::class,'013_cost_aware_ai.sql'],[HubAutomationMigration::class,'014_automations.sql'],[HubSelfSufficientAiMigration::class,'015_self_sufficient_ai.sql']];foreach($chain as[$c,$sql])m17a($c::apply($db,$base.'/migrations/'.$sql,$now)==='applied',$sql);
 m17a(HubAccountHostingMigration::apply($db,$base.'/migrations/016_account_hosting.sql',$now)==='applied','m17');m17a(HubAccountHostingMigration::apply($db,$base.'/migrations/016_account_hosting.sql',$now)==='already-applied','m17 idem');m17a((int)$pdo->query('PRAGMA user_version')->fetchColumn()===17,'version17');m17a($pdo->query('PRAGMA foreign_key_check')->fetchAll()===[],'fk');m17a($pdo->query('PRAGMA integrity_check')->fetchColumn()==='ok','integrity');m17a($pdo->query("SELECT system_role FROM control_user_profiles WHERE user_id='$owner'")->fetchColumn()==='OWNER','owner role preserved');
 $auth=HubOwnerAuthService::fromPdo($pdo);$auth->provisionInitial('owner','owner-password-123',$now);$ownerLogin=$auth->login('owner','owner-password-123',false,'fixture',$now);$token=$ownerLogin['sessionToken'];$csrf=$ownerLogin['csrfToken'];
 $request=$auth->registerAccessRequest(['schemaVersion'=>1,'displayName'=>'ครูทดสอบ','username'=>'teacher.test','password'=>'teacher-password-123','email'=>'teacher@example.test','phone'=>'0812345678','personType'=>'TEACHER','requestedArea'=>'AWH','note'=>'ขอใช้งาน'], $now,'registration-fixture');m17a($request['state']==='PENDING','pending');m17a((int)$pdo->query('SELECT COUNT(*) FROM hub_users')->fetchColumn()===1,'pending has no login authority');m17code('AUTH_FAILED',fn()=>$auth->login('teacher.test','teacher-password-123',false,'pending-login',$now));m17a(count($auth->accountRequests($token)['requests'])===1,'owner sees request');
 $approved=$auth->reviewAccountRequest($token,$csrf,$request['requestId'],['schemaVersion'=>1,'decision'=>'APPROVE','role'=>'TEACHER','projectIds'=>[$project]],$now);m17a($approved['state']==='APPROVED','approved');$teacher=$auth->login('teacher.test','teacher-password-123',false,'teacher-login',$now);m17a($teacher['role']==='TEACHER','applicant password works');$teacherEmail=$auth->login('teacher@example.test','teacher-password-123',false,'teacher-email-login',$now);m17a($teacherEmail['role']==='TEACHER','email login works');m17a($pdo->query("SELECT password_hash IS NULL FROM control_account_requests WHERE request_id='".$request['requestId']."'")->fetchColumn()==1,'request hash cleared');
 $direct=$auth->createUserDirect($token,$csrf,['schemaVersion'=>1,'displayName'=>'เจ้าหน้าที่','username'=>'staff.test','password'=>'staff-password-123','email'=>null,'phone'=>null,'personType'=>'STAFF','role'=>'STAFF','projectIds'=>[$project],'mustChangePassword'=>false],$now);m17a($direct['role']==='STAFF','direct role');m17a($auth->login('staff.test','staff-password-123',false,'staff-login',$now)['role']==='STAFF','direct login');
 $reject=$auth->registerAccessRequest(['schemaVersion'=>1,'displayName'=>'ผู้สมัคร','username'=>'reject.test','password'=>'reject-password-123','email'=>null,'phone'=>null,'personType'=>'OTHER','requestedArea'=>null,'note'=>null],$now,'reject-reg');$auth->reviewAccountRequest($token,$csrf,$reject['requestId'],['schemaVersion'=>1,'decision'=>'REJECT','role'=>'VIEWER','projectIds'=>[]],$now);m17code('AUTH_FAILED',fn()=>$auth->login('reject.test','reject-password-123',false,'reject-login',$now));m17a($pdo->query("SELECT password_hash IS NULL FROM control_account_requests WHERE request_id='".$reject['requestId']."'")->fetchColumn()==1,'rejected hash cleared');
 $hosting=HubManagedHostingService::fromPdo($pdo);$site=$hosting->createSite($token,$csrf,['schemaVersion'=>1,'name'=>'เว็บลงเรียน','slug'=>'registration','projectId'=>$project,'environment'=>'PRODUCTION','runtimeType'=>'AUTO','databaseMode'=>'AUTO','publicMode'=>'IP_PORT','healthPath'=>'/','backupEnabled'=>true],$now);m17a($site['state']==='QUEUED'&&$site['port']>=8400&&$site['port']<=8999,'site queued');$exec=$pdo->prepare('SELECT required_capability,checkpoint_json FROM control_task_executions WHERE task_id=:task');$exec->execute(['task'=>$site['taskId']]);$row=$exec->fetch();m17a(is_array($row)&&$row['required_capability']==='hosting.site.provision','canonical hosting execution');m17a((int)$pdo->query("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name LIKE '%hosting%queue%'")->fetchColumn()===0,'no hosting queue');m17a(count($hosting->sites($token)['sites'])===1,'site listed');m17code('PROJECT_SOURCE_NOT_READY',fn()=>$hosting->deploySite($token,$csrf,$site['siteId'],['schemaVersion'=>1],$now));
 m17code('INVITATION_DISABLED',fn()=>$auth->inviteUser($token,$csrf,[], $now));echo "AWH M17 Account Hosting: PASS\n";
}finally{m17clean($root);}
