<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/src/HubDatabaseStudioService.php';
require_once dirname(__DIR__) . '/src/HubDatabaseStudioRouter.php';

function m17_assert(bool $condition, string $message): void { if (!$condition) throw new RuntimeException($message); }
function m17_throws(callable $callback, string $code, string $message): void { try { $callback(); } catch (HubDatabaseStudioException $error) { m17_assert($error->codeName === $code, $message . ' (wrong code ' . $error->codeName . ')'); return; } throw new RuntimeException($message . ' (did not throw)'); }
function m17_clean(string $root): void { if (!is_dir($root)) return; $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST); foreach ($it as $file) { $path = $file->getPathname(); $file->isDir() && !$file->isLink() ? @rmdir($path) : @unlink($path); } @rmdir($root); }

if (!in_array('sqlite', PDO::getAvailableDrivers(), true)) { fwrite(STDOUT, "AWH M17 Database Studio: SKIP pdo_sqlite unavailable\n"); exit(77); }

$root = sys_get_temp_dir() . '/awh-m17-' . bin2hex(random_bytes(6)); $db = $root . '/awh.sqlite'; $migrations = $root . '/migrations';
$now = '2026-08-26T09:00:00+00:00'; $owner = '11111111-1111-4111-8111-111111111111'; $other = '22222222-2222-4222-8222-222222222222';
$ownerToken = 'owner-session-token-fixture-000000000001'; $otherToken = 'other-session-token-fixture-000000000001'; $staleToken = 'stale-session-token-fixture-000000000001'; $csrf = 'owner-csrf-fixture-000000000000000001';
try {
    mkdir($root, 0700, true); mkdir($migrations, 0700, true); file_put_contents($migrations . '/001_fixture.sql', "SELECT 1;\n"); file_put_contents($migrations . '/014_fixture.sql', "SELECT 14;\n");
    $pdo = new PDO('sqlite:' . $db, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]); $pdo->exec('PRAGMA foreign_keys = ON');
    $pdo->exec("CREATE TABLE hub_users(user_id TEXT PRIMARY KEY,display_name TEXT NOT NULL,created_at TEXT NOT NULL,revoked_at TEXT); CREATE TABLE owner_bootstrap(singleton_id INTEGER PRIMARY KEY,owner_user_id TEXT NOT NULL,initialized_at TEXT NOT NULL,bootstrap_closed INTEGER NOT NULL); CREATE TABLE control_sessions(session_id TEXT PRIMARY KEY,session_hash TEXT NOT NULL,user_id TEXT NOT NULL,csrf_hash TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,revoked_at TEXT,session_kind TEXT NOT NULL,remembered_until TEXT,step_up_at TEXT); CREATE TABLE safe_records(id INTEGER PRIMARY KEY,name TEXT NOT NULL,note TEXT,api_token TEXT); CREATE INDEX idx_safe_records_name ON safe_records(name); CREATE TABLE child_records(id INTEGER PRIMARY KEY,parent_id INTEGER NOT NULL,label TEXT,FOREIGN KEY(parent_id) REFERENCES safe_records(id) ON DELETE CASCADE); CREATE TABLE control_provider_credentials(provider_id TEXT PRIMARY KEY,ciphertext TEXT NOT NULL); CREATE TABLE auth_audit_events(event_id TEXT PRIMARY KEY,user_id TEXT,event_name TEXT NOT NULL,occurred_at TEXT NOT NULL,metadata_hash TEXT); CREATE TABLE awh_schema_migrations(migration_id TEXT PRIMARY KEY,schema_version INTEGER NOT NULL,checksum TEXT NOT NULL,applied_at TEXT NOT NULL); PRAGMA user_version=14;");
    $pdo->prepare('INSERT INTO hub_users VALUES(:id,:name,:at,NULL)')->execute(['id'=>$owner,'name'=>'Art','at'=>$now]); $pdo->prepare('INSERT INTO hub_users VALUES(:id,:name,:at,NULL)')->execute(['id'=>$other,'name'=>'Other','at'=>$now]); $pdo->prepare('INSERT INTO owner_bootstrap VALUES(1,:owner,:at,1)')->execute(['owner'=>$owner,'at'=>$now]);
    $session = $pdo->prepare("INSERT INTO control_sessions(session_id,session_hash,user_id,csrf_hash,created_at,expires_at,last_seen_at,revoked_at,session_kind,remembered_until,step_up_at) VALUES(:id,:hash,:user,:csrf,:created,:expires,:last,NULL,'password',NULL,:step)");
    $session->execute(['id'=>'31111111-1111-4111-8111-111111111111','hash'=>hash('sha256',$ownerToken),'user'=>$owner,'csrf'=>hash('sha256',$csrf),'created'=>$now,'expires'=>'2026-08-26T18:00:00+00:00','last'=>$now,'step'=>$now]);
    $session->execute(['id'=>'32222222-2222-4222-8222-222222222222','hash'=>hash('sha256',$otherToken),'user'=>$other,'csrf'=>hash('sha256',$csrf),'created'=>$now,'expires'=>'2026-08-26T18:00:00+00:00','last'=>$now,'step'=>$now]);
    $session->execute(['id'=>'33333333-3333-4333-8333-333333333333','hash'=>hash('sha256',$staleToken),'user'=>$owner,'csrf'=>hash('sha256',$csrf),'created'=>'2026-08-26T08:00:00+00:00','expires'=>'2026-08-26T18:00:00+00:00','last'=>$now,'step'=>'2026-08-26T08:00:00+00:00']);
    $insert = $pdo->prepare('INSERT INTO safe_records(id,name,note,api_token) VALUES(:id,:name,:note,:token)'); for ($i=1;$i<=250;$i++) $insert->execute(['id'=>$i,'name'=>'Row ' . str_pad((string)$i,3,'0',STR_PAD_LEFT),'note'=>$i%2===0?'even':'odd','token'=>'SECRET-TOKEN-' . $i]);
    $pdo->exec("INSERT INTO child_records VALUES(1,1,'child'); INSERT INTO control_provider_credentials VALUES('openai','SUPERSECRET-CIPHERTEXT'); INSERT INTO auth_audit_events VALUES('a1',NULL,'login_success','2026-08-26T08:59:00+00:00','HASH-MATERIAL'); INSERT INTO awh_schema_migrations VALUES('m14-cost-aware-ai',14,'abc123','2026-08-26T08:00:00+00:00');");

    $studio = HubDatabaseStudioService::openExisting($db, $migrations);
    $overview = $studio->overview($ownerToken, $now); m17_assert(($overview['database']['engine'] ?? null)==='SQLite' && ($overview['database']['schemaVersion'] ?? null)===14, 'overview uses real SQLite authority'); m17_assert(!str_contains((string) json_encode($overview), $root), 'overview never exposes database filesystem path');
    $tables = $studio->tables($ownerToken, $now)['tables']; $catalog = array_column($tables, null, 'name'); m17_assert(($catalog['safe_records']['locked'] ?? true)===false && ($catalog['control_provider_credentials']['locked'] ?? false)===true, 'credential tables are visible only as locked catalog entries');
    m17_throws(fn()=> $studio->overview($otherToken, $now), 'SESSION_EXPIRED', 'non-owner session is denied'); m17_throws(fn()=> $studio->browse($ownerToken,'control_provider_credentials',null,1,50,null,'ASC',$now), 'DATABASE_TABLE_RESTRICTED', 'credential rows cannot be browsed');

    $browse = $studio->browse($ownerToken,'safe_records','Row 02',1,10,'name','DESC',$now); m17_assert(($browse['pageSize']??null)===10 && count($browse['rows']??[])===10, 'browse is bounded and searchable'); m17_assert(($browse['rows'][0]['api_token']??null)==='[ซ่อนข้อมูลอ่อนไหว]', 'sensitive columns are redacted in browse'); m17_throws(fn()=> $studio->browse($ownerToken,'safe_records',null,1,10,'api_token','ASC',$now), 'DATABASE_REQUEST_INVALID', 'redacted columns cannot be used as sort side channel');
    $schema = $studio->schema($ownerToken,'child_records',$now); m17_assert(count($schema['foreignKeys']??[])===1 && ($schema['foreignKeys'][0]['table']??null)==='safe_records', 'schema exposes foreign-key structure');

    $select = $studio->runReadOnlySql($ownerToken,$csrf,'SELECT id,name FROM safe_records ORDER BY id',false,$now); m17_assert(($select['queryOnly']??false)===true && count($select['rows']??[])===200 && ($select['truncated']??false)===true, 'SQL console caps SELECT results at 200 rows');
    $plan = $studio->runReadOnlySql($ownerToken,$csrf,'SELECT id FROM safe_records WHERE name = \'Row 001\'',true,$now); m17_assert(($plan['mode']??null)==='EXPLAIN' && count($plan['rows']??[])>=1, 'query plan is available');
    m17_throws(fn()=> $studio->runReadOnlySql($ownerToken,$csrf,'DELETE FROM safe_records',false,$now), 'DATABASE_QUERY_REJECTED', 'write SQL is rejected');
    m17_throws(fn()=> $studio->runReadOnlySql($ownerToken,$csrf,'SELECT * FROM control_provider_credentials',false,$now), 'DATABASE_TABLE_RESTRICTED', 'SQL cannot read protected tables');
    m17_throws(fn()=> $studio->runReadOnlySql($ownerToken,$csrf,'SELECT api_token AS leaked FROM safe_records LIMIT 1',false,$now), 'DATABASE_TABLE_RESTRICTED', 'SQL cannot alias protected columns to bypass redaction');
    m17_throws(fn()=> $studio->runReadOnlySql($ownerToken,$csrf,'SELECT * FROM pragma_database_list',false,$now), 'DATABASE_QUERY_REJECTED', 'SQL cannot expose database paths through pragma table functions');
    m17_throws(fn()=> $studio->runReadOnlySql($staleToken,$csrf,'SELECT id FROM safe_records LIMIT 1',false,$now), 'STEP_UP_REQUIRED', 'SQL requires fresh password step-up');

    $csv = $studio->export($ownerToken,'safe_records','csv',null,'id','ASC',$now); m17_assert(($csv['rows']??0)===250 && !str_contains((string)$csv['content'],'SECRET-TOKEN-'), 'CSV export excludes protected columns'); $json = $studio->export($ownerToken,'safe_records','json','Row 001','id','ASC',$now); m17_assert(($json['rows']??0)===1 && !str_contains((string)$json['content'],'SECRET-TOKEN-1'), 'JSON export excludes protected columns');
    $health = $studio->health($ownerToken,$now); m17_assert(($health['integrity']['status']??null)==='PASS' && ($health['foreignKeys']['status']??null)==='PASS', 'integrity and foreign-key health checks pass'); $migration = $studio->migrations($ownerToken,$now); m17_assert(($migration['databaseUserVersion']??null)===14 && count($migration['ledger']??[])===1 && count($migration['files']??[])===2, 'migration center compares database ledger and release SQL files'); $audit = $studio->audit($ownerToken,10,$now); m17_assert(($audit['streams'][0]['table']??null)==='auth_audit_events' && ($audit['streams'][0]['rows'][0]['metadata_hash']??null)==='[ซ่อนข้อมูลอ่อนไหว]', 'audit is visible without exposing protected hash material');

    $server = ['HTTP_COOKIE'=>'__Host-awh_control_session=' . $ownerToken,'HTTP_SEC_FETCH_SITE'=>'same-origin','CONTENT_TYPE'=>'application/json','HTTP_X_AWH_CSRF'=>$csrf,'AWH_CONTROL_ORIGIN'=>'https://awh.test','HTTP_ORIGIN'=>'https://awh.test'];
    $route = HubDatabaseStudioRouter::dispatch('GET','/database-studio.php?action=overview',$server,$studio,''); m17_assert(($route['status']??0)===200 && str_contains((string) $route['body'], '"engine":"SQLite"'), 'router serves authenticated overview');
    $blocked = HubDatabaseStudioRouter::dispatch('POST','/database-studio.php?action=query',$server,$studio,json_encode(['schemaVersion'=>1,'sql'=>'UPDATE safe_records SET name=\'x\'','explain'=>false])); m17_assert(($blocked['status']??0)===400 && str_contains((string)$blocked['body'],'DATABASE_QUERY_REJECTED'), 'router fails closed on mutation SQL');
    $cross = $server; $cross['HTTP_ORIGIN']='https://evil.test'; $cross['HTTP_SEC_FETCH_SITE']='cross-site'; $denied = HubDatabaseStudioRouter::dispatch('GET','/database-studio.php?action=overview',$cross,$studio,''); m17_assert(($denied['status']??0)===403, 'cross-site Database Studio reads are denied');
    m17_assert((string)$pdo->query('SELECT name FROM safe_records WHERE id=1')->fetchColumn()==='Row 001' && (string)$pdo->query("SELECT ciphertext FROM control_provider_credentials WHERE provider_id='openai'")->fetchColumn()==='SUPERSECRET-CIPHERTEXT', 'Database Studio tests never mutate canonical rows');
    fwrite(STDOUT,"AWH M17 Database Studio: PASS\n");
} finally { m17_clean($root); }
