<?php

declare(strict_types=1);

foreach (['HubSchemaMigration','HubEnrollmentApiMigration','HubControlPlaneMigration','HubOwnerAuthMigration','HubAssistantWorkstreamMigration','HubWorkspaceContinuityMigration','HubUnifiedWorkspaceMigration','HubFinalProductMigration','HubFoundingMemoryMigration','HubSelfServiceMigration','HubCentralProjectAuthorityMigration','HubAnywhereExecutionMigration','HubCostAwareAiMigration','HubAutomationMigration','HubSelfSufficientAiMigration','HubAccountHostingMigration','HubCloudFirstMigration','HubCapabilityRegistryService','HubProviderCredentialStore','HubArtifactStore','HubCloudWorkflowService','HubEnrollmentService'] as $class) require_once dirname(__DIR__) . '/src/' . $class . '.php';
require_once dirname(__DIR__) . '/src/HubControlPlaneService.php';
require_once dirname(__DIR__) . '/src/HubControlPlaneRouter.php';

function m17c_assert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function m17c_uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
function m17c_clean(string $root):void{if(!is_dir($root))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$x=$f->getPathname();$f->isDir()&&!$f->isLink()?@rmdir($x):@unlink($x);}@rmdir($root);}
function m17c_json(array $value):string{return json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function m17c_response(HubControlPlaneService $service,string $method,string $uri,array $server,array $body=[]):array{return HubControlPlaneRouter::dispatch($method,$uri,$server,$service,m17c_json($body));}
function m17c_cookie(array $response,string $name):string{foreach(($response['headers']['Set-Cookie']??[]) as $line)if(str_starts_with($line,$name.'='))return explode(';',substr($line,strlen($name)+1),2)[0];throw new RuntimeException('cookie missing '.$name);}
function m17c_task(PDO $pdo,string $owner,string $project,string $capability,string $revision,string $at,string $profile='daily'):array{$task=m17c_uuid();$execution=m17c_uuid();$checkpoint=['revision'=>$revision];if($capability==='review.visual')$checkpoint['profile']=$profile;$pdo->prepare("INSERT INTO control_tasks(task_id,user_id,project_id,goal,state,assigned_device_id,lease_expires_at,progress,result_summary,failure_code,idempotency_key,conversation_id,created_at,updated_at,cancelled_at) VALUES(:task,:user,:project,:goal,'WAITING_FOR_WORKER',NULL,NULL,0,NULL,NULL,:key,NULL,:at,:at,NULL)")->execute(['task'=>$task,'user'=>$owner,'project'=>$project,'goal'=>'Cloud '.$capability,'key'=>'m17c-'.substr(hash('sha256',$task),0,28),'at'=>$at]);$pdo->prepare("INSERT INTO control_task_executions(execution_id,task_id,project_id,vault_revision_id,executor_kind,required_capability,state,lease_owner,lease_expires_at,attempt_count,cancellation_requested_at,checkpoint_json,last_error_code,created_at,updated_at) VALUES(:execution,:task,:project,NULL,'VPS',:capability,'WAITING_FOR_CAPABILITY',NULL,NULL,0,NULL,:checkpoint,NULL,:at,:at)")->execute(['execution'=>$execution,'task'=>$task,'project'=>$project,'capability'=>$capability,'checkpoint'=>json_encode($checkpoint,JSON_THROW_ON_ERROR),'at'=>$at]);return[$task,$execution];}

if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){fwrite(STDOUT,"AWH M18 Cloud-first Control: SKIP pdo_sqlite unavailable\n");exit(77);}

$root=rtrim(sys_get_temp_dir(),'/').'/awh-m17-cloud-'.bin2hex(random_bytes(6));$base=dirname(__DIR__);$now='2026-08-31T17:00:00+00:00';
$owner='223b45c0-23e1-408d-ae0f-ac5eca7f6900';$project='113b45c0-23e1-408d-ae0f-ac5eca7f6900';$revision=str_repeat('a',40);$secret='github-fixture-secret-1234567890';
try{
 mkdir($root,0700,true);$db=$root.'/awh.sqlite';$artifactRoot=$root.'/artifacts';$credentialRoot=$root.'/provider-credentials';mkdir($artifactRoot,0700,true);mkdir($credentialRoot,0700,true);
 putenv('AWH_ARTIFACT_ROOT='.$artifactRoot);putenv('AWH_PROVIDER_CREDENTIAL_ROOT='.$credentialRoot);putenv('AWH_GITHUB_REPOSITORY=fixture/awh');putenv('AWH_GITHUB_REF=awh/api-independence');
 $pdo=new PDO('sqlite:'.$db,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec(file_get_contents($base.'/schema.sql'));
 foreach(['enrollment_rate_limits','device_project_memberships','device_tokens','pairing_projects','pairing_codes','user_project_memberships','device_enrollments','owner_bootstrap','hub_users'] as $table)$pdo->exec('DROP TABLE IF EXISTS '.$table);
 $pdo->prepare('INSERT INTO projects(project_id,name,type,created_at,source_revision,observed_at,provenance) VALUES(:id,:name,:type,:at,NULL,:at,:p)')->execute(['id'=>$project,'name'=>'M17 Cloud Project','type'=>'awh-core','at'=>$now,'p'=>'m17-cloud-fixture']);
 m17c_assert(HubSchemaMigration::apply($db,$base.'/migrations/001_m3e_enrollment.sql',$now,false,$base.'/schema.sql')==='applied','M3E');m17c_assert(HubEnrollmentApiMigration::apply($db,$base.'/migrations/002_m3e2_enrollment_api.sql',$now)==='applied','M3E2');$enrollment=HubEnrollmentService::openExisting($db);$enrollment->initializeOwner($owner,'Art',[$project],$now);
 $chain=[[HubControlPlaneMigration::class,'003_m4_control_plane.sql'],[HubOwnerAuthMigration::class,'004_owner_auth.sql'],[HubAssistantWorkstreamMigration::class,'005_assistant_workstream.sql'],[HubWorkspaceContinuityMigration::class,'006_workspace_continuity.sql'],[HubUnifiedWorkspaceMigration::class,'007_unified_workspace.sql'],[HubFinalProductMigration::class,'008_final_product.sql'],[HubFoundingMemoryMigration::class,'009_founding_memory.sql'],[HubSelfServiceMigration::class,'010_self_service.sql'],[HubCentralProjectAuthorityMigration::class,'011_central_project_authority.sql'],[HubAnywhereExecutionMigration::class,'012_anywhere_execution_fabric.sql'],[HubCostAwareAiMigration::class,'013_cost_aware_ai.sql'],[HubAutomationMigration::class,'014_automations.sql'],[HubSelfSufficientAiMigration::class,'015_self_sufficient_ai.sql']];foreach($chain as[$migration,$sql])m17c_assert($migration::apply($db,$base.'/migrations/'.$sql,$now)==='applied',$sql);
 m17c_assert(HubAccountHostingMigration::apply($db,$base.'/migrations/016_account_hosting.sql',$now)==='applied','M17 account hosting prerequisite');
 $tablesBefore=$pdo->query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN);
 m17c_assert(HubCloudFirstMigration::apply($db,$base.'/migrations/017_cloud_first_control.sql',$now)==='applied','M18 cloud migration');m17c_assert(HubCloudFirstMigration::apply($db,$base.'/migrations/017_cloud_first_control.sql',$now)==='already-applied','M18 cloud migration idempotence');
 $tablesAfter=$pdo->query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN);m17c_assert($tablesAfter===$tablesBefore,'M18 must not create a shadow authority table');m17c_assert((int)$pdo->query('PRAGMA user_version')->fetchColumn()===18,'M18 user_version');
 foreach(['qa.cloud','review.visual'] as $cap)m17c_assert((int)$pdo->query("SELECT COUNT(*) FROM control_capability_catalog WHERE capability=".$pdo->quote($cap)." AND enabled=1") ->fetchColumn()===1,'M17 capability '.$cap);
 (new HubProviderCredentialStore($credentialRoot,'github-actions'))->replace($secret);
 putenv('AWH_CONTROL_ORIGIN=https://awh.test');$sessionNow=gmdate('c');$pairing=$enrollment->issuePairingCode($owner,[$project],$sessionNow);$sessionResponse=m17c_response(HubControlPlaneService::openExisting($db),'POST','/api/v1/control/session',['CONTENT_TYPE'=>'application/json','HTTP_ORIGIN'=>'https://awh.test'],['schemaVersion'=>1,'pairingCode'=>$pairing['pairingCode'],'displayName'=>'Art iPhone','appVersion'=>'1.0.0']);m17c_assert($sessionResponse['status']===200,'M17 owner session: '.(string)$sessionResponse['status'].' '.substr((string)$sessionResponse['body'],0,300));$sessionCookie=m17c_cookie($sessionResponse,'__Host-awh_control_session');$control=HubControlPlaneService::openExisting($db);$sessionState=m17c_response($control,'GET','/api/v1/control/session',['HTTP_ORIGIN'=>'https://awh.test','HTTP_COOKIE'=>'__Host-awh_control_session='.$sessionCookie]);$sessionPayload=json_decode($sessionState['body'],true,16,JSON_THROW_ON_ERROR);$csrf=(string)($sessionPayload['csrfToken']??'');m17c_assert($csrf!=='','M17 CSRF');$browser=['CONTENT_TYPE'=>'application/json','HTTP_ORIGIN'=>'https://awh.test','HTTP_COOKIE'=>'__Host-awh_control_session='.$sessionCookie,'HTTP_X_AWH_CSRF'=>$csrf];
 $cloudStatus=m17c_response($control,'GET','/api/v1/control/cloud',['HTTP_ORIGIN'=>'https://awh.test','HTTP_COOKIE'=>'__Host-awh_control_session='.$sessionCookie]);m17c_assert($cloudStatus['status']===200&&str_contains($cloudStatus['body'],'READY')&&!str_contains($cloudStatus['body'],$secret),'Owner Cloud status is safe and configured');
 $credentialAttempt=m17c_response($control,'POST','/api/v1/control/cloud/credential',$browser,['schemaVersion'=>1,'action'=>'SET','secret'=>'replacement-github-secret-1234567890']);m17c_assert($credentialAttempt['status']===403&&!str_contains($credentialAttempt['body'],'replacement-github-secret'),'Cloud credential write requires recent Owner step-up and never echoes secret');
 [$qaTask,$qaExecution]=m17c_task($pdo,$owner,$project,'qa.cloud',$revision,$now);[$reviewTask,$reviewExecution]=m17c_task($pdo,$owner,$project,'review.visual',$revision,$now,'final');
 $registry=new HubCapabilityRegistryService($pdo);$preEnvelope=$registry->ensureExecutionEnvelope($qaExecution,$now);m17c_assert(($preEnvelope['providerId']??null)===null,'envelope may exist before cloud provider advertisement');
 $requests=[];$runs=[101=>['id'=>101,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud QA '.$qaExecution.' '.$revision,'status'=>'in_progress','conclusion'=>null,'created_at'=>'2026-08-31T17:00:01Z'],202=>['id'=>202,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud Review '.$reviewExecution.' final '.$revision,'status'=>'in_progress','conclusion'=>null,'created_at'=>'2026-08-31T17:00:01Z']];
 $transport=function(array $request)use(&$requests,$runs,$qaExecution,$reviewExecution,$revision):array{$requests[]=$request;$url=(string)$request['url'];$path=(string)parse_url($url,PHP_URL_PATH);$query=(string)(parse_url($url,PHP_URL_QUERY)??'');if($request['method']==='POST'&&str_ends_with($path,'/dispatches'))return['status'=>204,'body'=>''];if($request['method']==='POST'&&str_ends_with($path,'/actions/runs/202/cancel'))return['status'=>202,'body'=>''];if($request['method']==='GET'&&str_contains($path,'/actions/workflows/awh-cloud-qa.yml/runs'))return['status'=>200,'body'=>json_encode(['workflow_runs'=>[['id'=>101,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud QA '.$qaExecution.' '.$revision,'status'=>'in_progress','conclusion'=>null,'created_at'=>'2026-08-31T17:00:01Z']]],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&str_contains($path,'/actions/workflows/awh-cloud-review.yml/runs'))return['status'=>200,'body'=>json_encode(['workflow_runs'=>[['id'=>202,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud Review '.$reviewExecution.' final '.$revision,'status'=>'in_progress','conclusion'=>null,'created_at'=>'2026-08-31T17:00:01Z']]],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&preg_match('#/actions/runs/(101|202)$#',$path,$m))return['status'=>200,'body'=>json_encode($runs[(int)$m[1]],JSON_THROW_ON_ERROR)];throw new RuntimeException('unexpected fixture request '.$request['method'].' '.$path.'?'.$query);};
 $cloud=HubCloudWorkflowService::fromEnvironment($pdo,$transport);m17c_assert($cloud->configured(),'cloud credential configured');$first=$cloud->tick($now);m17c_assert($first['processed']===2,'first tick claims both canonical cloud executions');
 $posts=array_values(array_filter($requests,static fn(array $r):bool=>$r['method']==='POST'));m17c_assert(count($posts)===2,'exactly one dispatch per execution');$byPath=[];foreach($posts as $post){$path=(string)parse_url((string)$post['url'],PHP_URL_PATH);$byPath[$path]=json_decode((string)$post['body'],true,16,JSON_THROW_ON_ERROR);m17c_assert(!str_contains((string)$post['body'],$secret),'credential never enters workflow inputs');}
 $qaPath='/repos/fixture/awh/actions/workflows/awh-cloud-qa.yml/dispatches';$reviewPath='/repos/fixture/awh/actions/workflows/awh-cloud-review.yml/dispatches';m17c_assert(($byPath[$qaPath]['inputs']['execution_id']??null)===$qaExecution&&($byPath[$qaPath]['inputs']['revision']??null)===$revision&&!isset($byPath[$qaPath]['inputs']['review_profile']),'qa.cloud dispatches only QA workflow');m17c_assert(($byPath[$reviewPath]['inputs']['execution_id']??null)===$reviewExecution&&($byPath[$reviewPath]['inputs']['revision']??null)===$revision&&($byPath[$reviewPath]['inputs']['review_profile']??null)==='final','review.visual dispatches only Review workflow');
 $rows=$pdo->query("SELECT execution_id,state,lease_owner,attempt_count,checkpoint_json FROM control_task_executions WHERE execution_id IN ('$qaExecution','$reviewExecution') ORDER BY execution_id")->fetchAll();foreach($rows as $row){m17c_assert($row['state']==='RUNNING'&&str_starts_with((string)$row['lease_owner'],'cloud:github-actions:'),'canonical execution owns cloud lease');m17c_assert((int)$row['attempt_count']===1,'first cloud claim increments bounded attempt');m17c_assert(!str_contains((string)$row['checkpoint_json'],$secret),'credential never enters checkpoint');}
 $postEnvelope=$registry->ensureExecutionEnvelope($qaExecution,$now);m17c_assert(($postEnvelope['providerId']??null)==='github-actions','waiting envelope binds provider only after Cloud becomes routable');
 $second=$cloud->tick('2026-08-31T17:00:05+00:00');m17c_assert($second['processed']===2,'second tick observes both running executions');$posts2=array_values(array_filter($requests,static fn(array $r):bool=>$r['method']==='POST'));m17c_assert(count($posts2)===2,'polling never redispatches a correlated execution');
 $checkpoint=[];$q=$pdo->query("SELECT execution_id,attempt_count,checkpoint_json FROM control_task_executions WHERE execution_id IN ('$qaExecution','$reviewExecution')");foreach($q->fetchAll() as $row){$checkpoint[$row['execution_id']]=json_decode((string)$row['checkpoint_json'],true,16,JSON_THROW_ON_ERROR);m17c_assert((int)$row['attempt_count']===1,'polling does not burn retry attempts');}m17c_assert(($checkpoint[$qaExecution]['workflow']??null)==='awh-cloud-qa.yml'&&($checkpoint[$qaExecution]['runId']??null)===101,'QA checkpoint correlates exact workflow run');m17c_assert(($checkpoint[$reviewExecution]['workflow']??null)==='awh-cloud-review.yml'&&($checkpoint[$reviewExecution]['runId']??null)===202,'Review checkpoint correlates exact workflow run');
 $cancelResponse=m17c_response($control,'POST','/api/v1/control/tasks/'.$reviewTask.'/cancel',$browser,['schemaVersion'=>1]);m17c_assert($cancelResponse['status']===200&&str_contains($cancelResponse['body'],'RUNNING'),'Owner cancellation requests Cloud stop without premature terminal state');$requested=$pdo->query("SELECT cancellation_requested_at FROM control_task_executions WHERE execution_id='$reviewExecution'")->fetchColumn();m17c_assert(is_string($requested)&&$requested!=='','canonical execution records cancellation request');
 $third=$cloud->tick('2026-08-31T17:00:10+00:00');m17c_assert(count(array_values(array_filter($requests,static fn(array $r):bool=>$r['method']==='POST'&&str_ends_with((string)parse_url((string)$r['url'],PHP_URL_PATH),'/dispatches'))))===2,'run-id polling remains idempotent');m17c_assert(count(array_values(array_filter($requests,static fn(array $r):bool=>$r['method']==='POST'&&str_ends_with((string)parse_url((string)$r['url'],PHP_URL_PATH),'/actions/runs/202/cancel'))))===1,'owner cancellation is forwarded to the correlated cloud run');
 $cancelled=$pdo->query("SELECT e.state AS execution_state,t.state AS task_state FROM control_task_executions e JOIN control_tasks t ON t.task_id=e.task_id WHERE e.execution_id='$reviewExecution'")->fetch();m17c_assert(is_array($cancelled)&&$cancelled['execution_state']==='CANCELLED'&&$cancelled['task_state']==='CANCELLED','late cloud result cannot resurrect a cancelled task');
 if(class_exists('ZipArchive')){
  $makeBundle=function(string $execution,string $verdict,array $findings,int $artifactId)use($root,$revision):array{
   $inner=$root.'/inner-'.$artifactId.'.zip';$z=new ZipArchive();m17c_assert($z->open($inner,ZipArchive::CREATE|ZipArchive::OVERWRITE)===true,'inner review zip create');$z->addFromString('VISUAL_EVIDENCE.json',json_encode(['schemaVersion'=>1,'commit'=>$revision,'dirty'=>false],JSON_THROW_ON_ERROR));$z->addFromString('screenshots/mobile.png','fixture-image-bytes');$z->close();
   $findingsJson=json_encode(['schemaVersion'=>1,'revision'=>$revision,'reviewer'=>'AIPass Fixture','verdict'=>$verdict,'scores'=>['chat'=>90,'mobile'=>90,'agentic'=>90,'artifact'=>90,'recovery'=>90],'findings'=>$findings],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);
   $outer=$root.'/outer-'.$artifactId.'.zip';$o=new ZipArchive();m17c_assert($o->open($outer,ZipArchive::CREATE|ZipArchive::OVERWRITE)===true,'outer review zip create');$o->addFile($inner,'AWH-AIPASS-REVIEW-'.$revision.'.zip');$o->addFromString('AWH-CLOUD-REVIEW.json',json_encode(['schemaVersion'=>1,'revision'=>$revision,'executionId'=>$execution,'profile'=>'final','workflow'=>'awh-cloud-review.yml'],JSON_THROW_ON_ERROR));$o->addFromString('AIPASS-FINDINGS.json',$findingsJson);$o->close();$bytes=file_get_contents($outer);m17c_assert(is_string($bytes)&&strlen($bytes)>100,'outer review zip bytes');return[$bytes,$inner,$outer];
  };
  $p2=[['id'=>'mobile-spacing','severity'=>'P2','scenario'=>'mobile review','problem'=>'Mobile spacing needs polish.','evidence'=>'Fixture evidence identifies bounded spacing.','expected'=>'Keep safe-area spacing comfortable.','fixLayer'=>'mobile-layout','confidence'=>0.9,'sourcePaths'=>['web/review.css']]];
  [$artifactTask,$artifactExecution]=m17c_task($pdo,$owner,$project,'review.visual',$revision,'2026-08-31T17:01:00+00:00','final');[$validBytes,$validInner,$validOuter]=$makeBundle($artifactExecution,'REVIEW',$p2,3030);
  $artifactRun=['id'=>303,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud Review '.$artifactExecution.' final '.$revision,'status'=>'completed','conclusion'=>'success','created_at'=>'2026-08-31T17:01:01Z'];
  $artifactTransport=function(array $request)use(&$requests,$qaExecution,$revision,$artifactExecution,$artifactRun,$validBytes):array{$requests[]=$request;$path=(string)parse_url((string)$request['url'],PHP_URL_PATH);if($request['method']==='POST'&&str_ends_with($path,'/dispatches'))return['status'=>204,'body'=>''];if($request['method']==='GET'&&str_contains($path,'/actions/workflows/awh-cloud-review.yml/runs'))return['status'=>200,'body'=>json_encode(['workflow_runs'=>[$artifactRun]],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&str_ends_with($path,'/actions/runs/303'))return['status'=>200,'body'=>json_encode($artifactRun,JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&str_ends_with($path,'/actions/runs/303/artifacts'))return['status'=>200,'body'=>json_encode(['artifacts'=>[['id'=>3030,'name'=>'AWH-AIPASS-REVIEW-'.$revision,'expired'=>false]]],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&str_ends_with($path,'/actions/artifacts/3030/zip'))return['status'=>200,'body'=>$validBytes];if($request['method']==='GET'&&str_ends_with($path,'/actions/runs/101'))return['status'=>200,'body'=>json_encode(['id'=>101,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud QA '.$qaExecution.' '.$revision,'status'=>'in_progress','conclusion'=>null,'created_at'=>'2026-08-31T17:00:01Z'],JSON_THROW_ON_ERROR)];throw new RuntimeException('unexpected artifact fixture request '.$request['method'].' '.$path);};
  $artifactCloud=HubCloudWorkflowService::fromEnvironment($pdo,$artifactTransport);$artifactCloud->tick('2026-08-31T17:01:00+00:00');$artifactCloud->tick('2026-08-31T17:01:05+00:00');
  $artifactRows=$pdo->query("SELECT a.kind,o.storage_key,o.mime_type FROM control_artifacts a JOIN control_artifact_objects o ON o.artifact_id=a.artifact_id WHERE a.task_id='$artifactTask' ORDER BY a.kind")->fetchAll();m17c_assert(count($artifactRows)===2&&array_column($artifactRows,'kind')===['aipass-findings','visual-review-pack'],'valid Review Pack + findings commit through canonical artifact authority');foreach($artifactRows as $artifactRow)m17c_assert(is_file($artifactRoot.'/'.$artifactRow['storage_key']),'canonical artifact bytes exist');
  [$badTask,$badExecution]=m17c_task($pdo,$owner,$project,'review.visual',$revision,'2026-08-31T17:02:00+00:00','final');$badFinding=[['id'=>'critical-blocker','severity'=>'P0','scenario'=>'critical review','problem'=>'Critical fixture problem requires block.','evidence'=>'Fixture reproduces a critical problem.','expected'=>'BLOCK verdict is required for P0.','fixLayer'=>'architecture','confidence'=>1.0]];[$badBytes,$badInner,$badOuter]=$makeBundle($badExecution,'PASS',$badFinding,4040);$badRun=['id'=>404,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud Review '.$badExecution.' final '.$revision,'status'=>'completed','conclusion'=>'success','created_at'=>'2026-08-31T17:02:01Z'];
  $badTransport=function(array $request)use($qaExecution,$revision,$badRun,$badBytes):array{$path=(string)parse_url((string)$request['url'],PHP_URL_PATH);if($request['method']==='POST'&&str_ends_with($path,'/dispatches'))return['status'=>204,'body'=>''];if($request['method']==='GET'&&str_contains($path,'/actions/workflows/awh-cloud-review.yml/runs'))return['status'=>200,'body'=>json_encode(['workflow_runs'=>[$badRun]],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&str_ends_with($path,'/actions/runs/404/artifacts'))return['status'=>200,'body'=>json_encode(['artifacts'=>[['id'=>4040,'name'=>'AWH-AIPASS-REVIEW-'.$revision,'expired'=>false]]],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&str_ends_with($path,'/actions/artifacts/4040/zip'))return['status'=>200,'body'=>$badBytes];if($request['method']==='GET'&&str_ends_with($path,'/actions/runs/101'))return['status'=>200,'body'=>json_encode(['id'=>101,'event'=>'workflow_dispatch','display_title'=>'AWH Cloud QA '.$qaExecution.' '.$revision,'status'=>'in_progress','conclusion'=>null,'created_at'=>'2026-08-31T17:00:01Z'],JSON_THROW_ON_ERROR)];throw new RuntimeException('unexpected invalid artifact fixture request '.$request['method'].' '.$path);};
  $badCloud=HubCloudWorkflowService::fromEnvironment($pdo,$badTransport);$badCloud->tick('2026-08-31T17:02:00+00:00');$badCloud->tick('2026-08-31T17:02:05+00:00');$badState=$pdo->query("SELECT e.state AS execution_state,t.state AS task_state,e.last_error_code FROM control_task_executions e JOIN control_tasks t ON t.task_id=e.task_id WHERE e.execution_id='$badExecution'")->fetch();m17c_assert(is_array($badState)&&$badState['execution_state']==='FAILED'&&$badState['task_state']==='FAILED'&&$badState['last_error_code']==='CLOUD_FINDINGS_INVALID','invalid findings fail closed');m17c_assert((int)$pdo->query("SELECT COUNT(*) FROM control_artifacts WHERE task_id='$badTask'")->fetchColumn()===0,'invalid findings cannot partially import Review Pack');
  foreach([$validInner,$validOuter,$badInner,$badOuter] as $fixtureFile)@unlink($fixtureFile);
 }else fwrite(STDOUT,"AWH M17 Cloud artifact import: SKIP ZipArchive unavailable\n");
 $apiTask=m17c_response($control,'POST','/api/v1/control/cloud/tasks',$browser,['schemaVersion'=>1,'projectId'=>$project,'kind'=>'QA','revision'=>$revision,'profile'=>null,'idempotencyKey'=>'m17-cloud-owner-api-0001']);m17c_assert($apiTask['status']===201,'Owner can materialize Cloud QA through canonical API');$apiPayload=json_decode($apiTask['body'],true,16,JSON_THROW_ON_ERROR);$apiTaskId=(string)($apiPayload['taskId']??'');$apiExecution=$pdo->prepare('SELECT required_capability,state,checkpoint_json FROM control_task_executions WHERE task_id=:task');$apiExecution->execute(['task'=>$apiTaskId]);$apiRow=$apiExecution->fetch();m17c_assert(is_array($apiRow)&&$apiRow['required_capability']==='qa.cloud'&&in_array($apiRow['state'],['QUEUED','WAITING_FOR_CAPABILITY'],true),'Owner API reuses canonical execution authority');$apiCheckpoint=json_decode((string)$apiRow['checkpoint_json'],true,16,JSON_THROW_ON_ERROR);m17c_assert(($apiCheckpoint['revision']??null)===$revision&&($apiCheckpoint['mode']??null)==='CLOUD_QA','Owner API locks exact revision in canonical checkpoint');$apiDuplicate=m17c_response($control,'POST','/api/v1/control/cloud/tasks',$browser,['schemaVersion'=>1,'projectId'=>$project,'kind'=>'QA','revision'=>$revision,'profile'=>null,'idempotencyKey'=>'m17-cloud-owner-api-0001']);m17c_assert($apiDuplicate['status']===201&&((json_decode($apiDuplicate['body'],true,16,JSON_THROW_ON_ERROR)['taskId']??null)===$apiTaskId),'Owner Cloud task API is idempotent');
 m17c_assert((int)$pdo->query("SELECT COUNT(*) FROM control_task_events WHERE message LIKE '%$secret%'")->fetchColumn()===0,'credential never enters task events');
 $executorSource=file_get_contents($base.'/bin/awh-native-executor.php');m17c_assert(is_string($executorSource)&&str_contains($executorSource,'HubCloudWorkflowService::fromEnvironment')&&strpos($executorSource,'$cloudService->tick()')<strpos($executorSource,'$execution->runBatch(4)'),'Cloud adapter shares the canonical one-shot executor and renews before generic lease recovery');
 m17c_assert($pdo->query('PRAGMA integrity_check')->fetchColumn()==='ok'&&$pdo->query('PRAGMA foreign_key_check')->fetchAll()===[],'M17 preserves DB integrity/FKs');
 fwrite(STDOUT,"AWH M18 Cloud-first Control: PASS\n");
}finally{putenv('AWH_ARTIFACT_ROOT');putenv('AWH_PROVIDER_CREDENTIAL_ROOT');putenv('AWH_GITHUB_REPOSITORY');putenv('AWH_GITHUB_REF');putenv('AWH_CONTROL_ORIGIN');m17c_clean($root);}
