<?php

declare(strict_types=1);

foreach (['HubSchemaMigration','HubEnrollmentApiMigration','HubControlPlaneMigration','HubOwnerAuthMigration','HubAssistantWorkstreamMigration','HubWorkspaceContinuityMigration','HubUnifiedWorkspaceMigration','HubFinalProductMigration','HubFoundingMemoryMigration','HubSelfServiceMigration','HubCentralProjectAuthorityMigration','HubAnywhereExecutionMigration','HubCostAwareAiMigration','HubAutomationMigration','HubSelfSufficientAiMigration','HubAccountHostingMigration','HubCloudFirstMigration','HubConversationLifecycleMigration','HubProjectSourceAuthorityMigration','HubCapabilityRegistryService','HubProviderCredentialStore','HubArtifactStore','HubCloudWorkflowService','HubProjectVault','HubProjectVaultService','HubProjectSourceAuthorityService','HubProjectSourceSyncService','HubAiPassProjectExportService','HubEnrollmentService'] as $class) require_once dirname(__DIR__) . '/src/' . $class . '.php';

function m20_assert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function m20_clean(string $root):void{if(!is_dir($root))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$x=$f->getPathname();$f->isDir()&&!$f->isLink()?@rmdir($x):@unlink($x);}@rmdir($root);}

if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){fwrite(STDOUT,"AWH M20 Project Source Authority: SKIP pdo_sqlite unavailable\n");exit(77);}
$root=rtrim(sys_get_temp_dir(),'/').'/awh-m20-source-'.bin2hex(random_bytes(6));$base=dirname(__DIR__);$now='2026-09-01T16:00:00+00:00';
$owner='223b45c0-23e1-408d-ae0f-ac5eca7f6900';$awh='113b45c0-23e1-408d-ae0f-ac5eca7f6900';$bay='123b45c0-23e1-408d-ae0f-ac5eca7f6900';$awhSha=str_repeat('a',40);$bayOld=str_repeat('b',40);$baySha=str_repeat('c',40);
try{
 mkdir($root,0700,true);$db=$root.'/awh.sqlite';$artifactRoot=$root.'/artifacts';$credentialRoot=$root.'/provider-credentials';$vaultRoot=$root.'/vault';foreach([$artifactRoot,$credentialRoot,$vaultRoot] as $dir)mkdir($dir,0700,true);
 putenv('AWH_ARTIFACT_ROOT='.$artifactRoot);putenv('AWH_PROVIDER_CREDENTIAL_ROOT='.$credentialRoot);putenv('AWH_PROJECT_VAULT_ROOT='.$vaultRoot);putenv('AWH_GITHUB_REPOSITORY=fixture/awh');putenv('AWH_GITHUB_REF=main');
 $pdo=new PDO('sqlite:'.$db,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec(file_get_contents($base.'/schema.sql'));
 foreach(['enrollment_rate_limits','device_project_memberships','device_tokens','pairing_projects','pairing_codes','user_project_memberships','device_enrollments','owner_bootstrap','hub_users'] as $table)$pdo->exec('DROP TABLE IF EXISTS '.$table);
 $insert=$pdo->prepare('INSERT INTO projects(project_id,name,type,created_at,source_revision,observed_at,provenance) VALUES(:id,:name,:type,:at,:revision,:at,:p)');
 $insert->execute(['id'=>$awh,'name'=>'Art’s Workspace Hub (AWH)','type'=>'awh-core','at'=>$now,'revision'=>$awhSha,'p'=>'m20-fixture']);
 $insert->execute(['id'=>$bay,'name'=>'BAY EXCUSE X','type'=>'school-system','at'=>$now,'revision'=>$bayOld,'p'=>'m20-fixture']);
 m20_assert(HubSchemaMigration::apply($db,$base.'/migrations/001_m3e_enrollment.sql',$now,false,$base.'/schema.sql')==='applied','M3E');m20_assert(HubEnrollmentApiMigration::apply($db,$base.'/migrations/002_m3e2_enrollment_api.sql',$now)==='applied','M3E2');$enrollment=HubEnrollmentService::openExisting($db);$enrollment->initializeOwner($owner,'Art',[$awh,$bay],$now);
 $chain=[[HubControlPlaneMigration::class,'003_m4_control_plane.sql'],[HubOwnerAuthMigration::class,'004_owner_auth.sql'],[HubAssistantWorkstreamMigration::class,'005_assistant_workstream.sql'],[HubWorkspaceContinuityMigration::class,'006_workspace_continuity.sql'],[HubUnifiedWorkspaceMigration::class,'007_unified_workspace.sql'],[HubFinalProductMigration::class,'008_final_product.sql'],[HubFoundingMemoryMigration::class,'009_founding_memory.sql'],[HubSelfServiceMigration::class,'010_self_service.sql'],[HubCentralProjectAuthorityMigration::class,'011_central_project_authority.sql'],[HubAnywhereExecutionMigration::class,'012_anywhere_execution_fabric.sql'],[HubCostAwareAiMigration::class,'013_cost_aware_ai.sql'],[HubAutomationMigration::class,'014_automations.sql'],[HubSelfSufficientAiMigration::class,'015_self_sufficient_ai.sql'],[HubAccountHostingMigration::class,'016_account_hosting.sql'],[HubCloudFirstMigration::class,'017_cloud_first_control.sql']];foreach($chain as[$migration,$sql])m20_assert($migration::apply($db,$base.'/migrations/'.$sql,$now)==='applied',$sql);
 m20_assert(HubConversationLifecycleMigration::apply($db,$base.'/migrations/018_conversation_lifecycle.sql',$now)==='applied','M19 conversation lifecycle');m20_assert(HubConversationLifecycleMigration::apply($db,$base.'/migrations/018_conversation_lifecycle.sql',$now)==='already-applied','M19 conversation lifecycle idempotence');m20_assert((int)$pdo->query('PRAGMA user_version')->fetchColumn()===19,'M19 user_version is preserved before M20');
 $tablesBefore=$pdo->query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN);
 m20_assert(HubProjectSourceAuthorityMigration::apply($db,$base.'/migrations/019_project_source_authority.sql',$now)==='applied','M20 migration');m20_assert(HubProjectSourceAuthorityMigration::apply($db,$base.'/migrations/019_project_source_authority.sql',$now)==='already-applied','M20 idempotence');
 $tablesAfter=$pdo->query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN);m20_assert($tablesAfter===$tablesBefore,'M20 must extend projects rather than create shadow authority tables');m20_assert((int)$pdo->query('PRAGMA user_version')->fetchColumn()===20,'M20 user_version');
 $columns=array_column($pdo->query('PRAGMA table_info(projects)')->fetchAll(),'name');foreach(['canonical_source_provider','canonical_source_repository','canonical_source_ref','canonical_source_revision','canonical_source_observed_at','canonical_source_vault_revision_id'] as $column)m20_assert(in_array($column,$columns,true),'M20 missing '.$column);
 (new HubProviderCredentialStore($credentialRoot,'github-actions'))->replace('github-fixture-secret-1234567890');
 $zipball=null;
 if(class_exists('ZipArchive')){
  $fixture=$root.'/bay-source.zip';$z=new ZipArchive();m20_assert($z->open($fixture,ZipArchive::CREATE|ZipArchive::OVERWRITE)===true,'zipball fixture');$z->addFromString('fixture-bay-root/app.php',"<?php\nconst API_KEY = 'ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ123456';\n// teacher contact test@example.com 0812345678\necho 'BAY EXCUSE X';\n");$lines=[];for($i=0;$i<2500;$i++)$lines[]=sprintf("function bayRule%04d(){ return 'document-authority-%s'; }",$i,hash('sha256','awh-m20-fixture-'.$i));$large=implode("\n",$lines)."\n";$z->addFromString('fixture-bay-root/src/a.js',$large);$z->addFromString('fixture-bay-root/src/b.js',str_replace('bayRule','bayPolicy',$large));$z->addFromString('fixture-bay-root/src/c.js',str_replace('bayRule','bayReport',$large));$z->close();$zipball=file_get_contents($fixture);m20_assert(is_string($zipball)&&strlen($zipball)>100,'zipball bytes');
 }
 $requests=[];$transport=function(array $request)use(&$requests,$awhSha,$baySha,$zipball):array{$requests[]=$request;$path=(string)parse_url((string)$request['url'],PHP_URL_PATH);if($request['method']==='GET'&&$path==='/repos/fixture/awh/commits/main')return['status'=>200,'body'=>json_encode(['sha'=>$awhSha],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&$path==='/repos/fixture/bay/commits/main')return['status'=>200,'body'=>json_encode(['sha'=>$baySha],JSON_THROW_ON_ERROR)];if($request['method']==='GET'&&$path==='/repos/fixture/bay/zipball/'.$baySha&&is_string($zipball))return['status'=>200,'body'=>$zipball];throw new RuntimeException('unexpected M20 fixture request '.$request['method'].' '.$path);};
 $cloud=new HubCloudWorkflowService($pdo,HubArtifactStore::fromEnvironment(),$transport);$sources=new HubProjectSourceAuthorityService($pdo,$cloud);
 $awhState=$sources->bindGitHub($awh,'fixture/awh','main',$now,true);m20_assert($awhState['canonicalRevision']===$awhSha&&$awhState['localRevision']===$awhSha&&$awhState['state']==='CURRENT'&&$awhState['workflowCompatible']===true,'AWH canonical source is bound to its own workflow');
 $bayState=$sources->bindGitHub($bay,'fixture/bay','main',$now,true);m20_assert($bayState['canonicalRevision']===$baySha&&$bayState['localRevision']===$bayOld&&$bayState['state']==='REMOTE_AHEAD_OR_DIFFERENT'&&$bayState['workflowCompatible']===false,'BAY stale local source is separated from canonical remote source');
 m20_assert((string)$pdo->query("SELECT source_revision FROM projects WHERE project_id='$bay'")->fetchColumn()===$bayOld,'canonical refresh never rewrites local observed revision');
 try{$sources->observeGitHub($bay,'fixture/other','main',$now);throw new RuntimeException('conflicting worker source must fail');}catch(HubProjectSourceAuthorityException $e){m20_assert($e->codeName==='PROJECT_SOURCE_CONFLICT','worker cannot override Owner source authority');}
 if(class_exists('ZipArchive')){
  $vaults=HubProjectVaultService::fromEnvironment($pdo);$synced=(new HubProjectSourceSyncService($pdo,$cloud,$sources,$vaults))->sync($bay,$now);m20_assert($synced['canonicalRevision']===$baySha&&is_string($synced['canonicalVaultRevisionId'])&&$synced['canonicalVaultReady']===true,'BAY exact remote SHA is cached as immutable Vault revision');
  $cached=(new HubProjectSourceSyncService($pdo,$cloud,$sources,$vaults))->sync($bay,$now);m20_assert($cached['synced']===false&&$cached['canonicalVaultRevisionId']===$synced['canonicalVaultRevisionId'],'canonical source sync is idempotent');
  $export=(new HubAiPassProjectExportService($vaults))->build($bay,$cached,$now);$manifest=$export['manifest'];m20_assert(str_starts_with($export['fileName'],'BAY-EXCUSE-X-AIPASS-')&&($manifest['canonicalRevision']??null)===$baySha,'AiPASS artifact identity is project-aware and exact-revision bound');m20_assert(($manifest['schemaVersion']??null)===2&&($manifest['format']??null)==='AIPASS_DIRECT_DOCX','AiPASS direct DOCX manifest is authoritative');m20_assert(($manifest['sourcePartCount']??0)>=2,'AiPASS source evidence is conservatively split below provider document limits');m20_assert(($manifest['redactions']??[])!==[],'AiPASS export redacts source secrets/PII');m20_assert(($manifest['fileTextByteCeiling']??null)===350000&&($manifest['batchTextByteCeiling']??null)===650000&&($manifest['maxFilesPerBatch']??null)===16,'AiPASS conservative delivery budgets are explicit');m20_assert(($manifest['tokenCountMode']??null)==='CONSERVATIVE_UTF8_BYTE_BOUND_NOT_EXACT_PROVIDER_TOKENS','AiPASS never mislabels byte bounds as exact provider token counts');
  foreach($manifest['files'] as $file)m20_assert(($file['mimeType']??null)===HubAiPassProjectExportService::DOCX_MIME&&str_ends_with(strtolower((string)$file['name']),'.docx')&&(int)$file['extractedTextBytes']>0&&(int)$file['extractedTextBytes']<=350000,'every user-facing AiPASS file is a bounded DOCX');
  foreach($manifest['batches'] as $batch)m20_assert((int)$batch['fileCount']<=16&&(int)$batch['extractedTextBytes']<=650000,'every AiPASS review batch stays inside the conservative aggregate budget');
  $package=$root.'/review.zip';file_put_contents($package,$export['bytes']);$delivery=HubAiPassBundleDelivery::manifest($package);m20_assert(($delivery['format']??null)==='AIPASS_DIRECT_DOCX'&&count($delivery['files'])===count($manifest['files']),'AiPASS internal bundle exposes a verified DOCX delivery manifest');
  $outer=new ZipArchive();m20_assert($outer->open($package,ZipArchive::RDONLY|ZipArchive::CHECKCONS)===true,'AiPASS internal artifact bundle is valid ZIP');$names=[];for($i=0;$i<$outer->numFiles;$i++)$names[]=(string)$outer->getNameIndex($i);m20_assert(in_array('01_AIPASS_REVIEW_CONTEXT.docx',$names,true)&&count(array_filter($names,static fn($n)=>str_contains($n,'AIPASS_SOURCE_EVIDENCE_PART_')))>=2,'AiPASS internal bundle contains context and every source part');m20_assert(count(array_filter($names,static fn($n)=>str_contains(strtolower($n),'visual')))===0,'AiPASS export never fabricates visual evidence');
  $sourceIndex=null;foreach($manifest['files'] as $i=>$file)if(($file['role']??null)==='SOURCE'){$sourceIndex=$i;break;}m20_assert(is_int($sourceIndex),'AiPASS delivery has source evidence');$delivered=HubAiPassBundleDelivery::document($package,$sourceIndex);m20_assert(($delivered['mimeType']??null)===HubAiPassProjectExportService::DOCX_MIME&&(int)$delivered['extractedTextBytes']<=350000,'direct AiPASS DOCX is re-verified at delivery time');
  $sourceDoc=$root.'/source.docx';file_put_contents($sourceDoc,$delivered['bytes']);$outer->close();$doc=new ZipArchive();m20_assert($doc->open($sourceDoc,ZipArchive::RDONLY|ZipArchive::CHECKCONS)===true,'source evidence is a real DOCX');$xml=(string)$doc->getFromName('word/document.xml');$doc->close();m20_assert(str_contains($xml,'BAY EXCUSE X')||str_contains($xml,'app.php'),'source evidence contains BAY source rather than AWH source');m20_assert(!str_contains($xml,'ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ123456')&&!str_contains($xml,'test@example.com')&&!str_contains($xml,'0812345678'),'secret/email/phone do not leave AWH');$plain=html_entity_decode(strip_tags(preg_replace('/<w:(?:br|cr)\s*\/?>/i',"\n",$xml)??$xml),ENT_QUOTES|ENT_XML1,'UTF-8');m20_assert(strlen($plain)<=350000,'final extracted DOCX text stays inside the conservative per-file byte ceiling');
 }else fwrite(STDOUT,"AWH M20 source sync/AiPASS export: SKIP ZipArchive unavailable\n");
 m20_assert($pdo->query('PRAGMA integrity_check')->fetchColumn()==='ok'&&$pdo->query('PRAGMA foreign_key_check')->fetchAll()===[],'M20 preserves DB integrity/FKs');
 fwrite(STDOUT,"AWH M20 Project Source Authority: PASS\n");
}finally{foreach(['AWH_ARTIFACT_ROOT','AWH_PROVIDER_CREDENTIAL_ROOT','AWH_PROJECT_VAULT_ROOT','AWH_GITHUB_REPOSITORY','AWH_GITHUB_REF'] as $key)putenv($key);m20_clean($root);}