<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/src/HubOperatorBridgeService.php';

function ob_assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);echo "PASS: {$message}\n";}
function ob_code(string $code,callable $fn):void{try{$fn();throw new RuntimeException('expected '.$code);}catch(HubOperatorBridgeException $e){ob_assert($e->codeName===$code,'blocked with '.$code);}}
if(!in_array('sqlite',PDO::getAvailableDrivers(),true)){fwrite(STDOUT,"AWH Operator Bridge: SKIP pdo_sqlite unavailable\n");exit(77);}
$root=rtrim(sys_get_temp_dir(),'/').'/awh-operator-bridge-'.bin2hex(random_bytes(6));
$project='7ee0b9ec-4d2e-435f-92da-fa949afb7c01';$revision='9007585d-87a2-400b-a382-a4bf3c03a5b6';$now='2026-09-17T12:00:00+00:00';
$targetSha=str_repeat('a',40);$packageSha=str_repeat('b',64);$calls=[];
try{
 mkdir($root,0700,true);$cred=$root.'/credentials';mkdir($cred,0700,true);$kp=sodium_crypto_sign_keypair();file_put_contents($cred.'/bay-remote-update-signing.key',base64_encode(sodium_crypto_sign_secretkey($kp))."\n");chmod($cred.'/bay-remote-update-signing.key',0600);putenv('AWH_PROVIDER_CREDENTIAL_ROOT='.$cred);
 $pdo=new PDO('sqlite:'.$root.'/awh.sqlite',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA foreign_keys=ON');$pdo->exec('PRAGMA user_version=21');
 $owner='223b45c0-23e1-408d-ae0f-ac5eca7f6900';
 $pdo->exec("CREATE TABLE hub_users(user_id TEXT PRIMARY KEY)");
 $pdo->exec("CREATE TABLE owner_bootstrap(singleton_id INTEGER PRIMARY KEY,owner_user_id TEXT NOT NULL,bootstrap_closed INTEGER NOT NULL)");
 $pdo->exec("CREATE TABLE projects(project_id TEXT PRIMARY KEY,name TEXT,type TEXT,canonical_source_authority TEXT,canonical_source_revision TEXT,canonical_source_vault_revision_id TEXT)");
 $pdo->exec("CREATE TABLE control_project_vaults(project_id TEXT PRIMARY KEY,storage_mode TEXT,active_revision_id TEXT,sync_state TEXT,content_bytes INTEGER,file_count INTEGER,updated_at TEXT)");
 $pdo->exec("CREATE TABLE control_workspace_leases(project_id TEXT PRIMARY KEY,owner_device_id TEXT,checkpoint_id TEXT,state TEXT,lease_expires_at TEXT,updated_at TEXT)");
 $pdo->exec("CREATE TABLE control_tasks(task_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,project_id TEXT NOT NULL,goal TEXT NOT NULL,state TEXT NOT NULL,assigned_device_id TEXT,lease_expires_at TEXT,progress INTEGER NOT NULL,result_summary TEXT,failure_code TEXT,idempotency_key TEXT NOT NULL,conversation_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,cancelled_at TEXT)");
 $pdo->exec("CREATE TABLE control_task_executions(execution_id TEXT PRIMARY KEY,task_id TEXT NOT NULL UNIQUE,project_id TEXT NOT NULL,vault_revision_id TEXT,executor_kind TEXT NOT NULL,required_capability TEXT NOT NULL,state TEXT NOT NULL,lease_owner TEXT,lease_expires_at TEXT,attempt_count INTEGER NOT NULL,cancellation_requested_at TEXT,checkpoint_json TEXT NOT NULL,last_error_code TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");
 $pdo->exec("CREATE TABLE control_execution_envelopes(envelope_id TEXT PRIMARY KEY,execution_id TEXT NOT NULL UNIQUE,task_id TEXT NOT NULL,project_id TEXT NOT NULL,conversation_id TEXT,base_revision_id TEXT,session_key TEXT NOT NULL,mutation_scope TEXT NOT NULL,state TEXT NOT NULL,provider_id TEXT,lease_expires_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");
 $pdo->exec("CREATE TABLE control_task_events(event_id TEXT PRIMARY KEY,task_id TEXT NOT NULL,state TEXT NOT NULL,progress INTEGER NOT NULL,message TEXT,occurred_at TEXT NOT NULL)");
 $pdo->exec("CREATE TABLE control_capability_sources(source_id TEXT PRIMARY KEY,display_name TEXT,version TEXT,license_id TEXT,source_url TEXT,enabled INTEGER,created_at TEXT,updated_at TEXT)");
 $pdo->exec("CREATE TABLE control_capability_catalog(capability TEXT PRIMARY KEY,source_id TEXT,category TEXT,display_name TEXT,description TEXT,mutation_kind TEXT,risk_class TEXT,maturity TEXT,user_visible INTEGER,enabled INTEGER,created_at TEXT,updated_at TEXT)");
 $pdo->exec("CREATE TABLE control_execution_providers(provider_id TEXT PRIMARY KEY,provider_kind TEXT,display_name TEXT,availability_mode TEXT,cost_class TEXT,priority INTEGER,enabled INTEGER,observed_at TEXT,expires_at TEXT,metadata_json TEXT)");
 $pdo->exec("CREATE TABLE control_execution_provider_capabilities(provider_id TEXT,capability TEXT,version TEXT,cost_rank INTEGER,quality_rank INTEGER,latency_rank INTEGER,enabled INTEGER,observed_at TEXT,expires_at TEXT,metadata_json TEXT)");
 $pdo->prepare('INSERT INTO hub_users VALUES(?)')->execute([$owner]);$pdo->prepare('INSERT INTO owner_bootstrap VALUES(1,?,1)')->execute([$owner]);
 $pdo->prepare('INSERT INTO projects VALUES(?,?,?,?,?,?)')->execute([$project,'BAY EXCUSE X','php','AWH_VAULT',$targetSha,$revision]);$pdo->prepare('INSERT INTO control_project_vaults VALUES(?,?,?,?,?,?,?)')->execute([$project,'VAULT',$revision,'SYNCED',123,12,$now]);
 $poster=function(string $endpoint,array $payload)use(&$calls,$targetSha,$packageSha):array{$calls[]=['endpoint'=>$endpoint,'payload'=>$payload];$command=$payload['command']??null;if($command==='STATUS')return ['ok'=>true,'currentVersion'=>'2.0.0-RC5.4.33','deployedSha'=>str_repeat('c',40),'preflight'=>['ready'=>true],'maintenance'=>['active'=>false],'packages'=>[['version'=>'6.0.0-rc.1','sourceSha'=>$targetSha,'packageSha256'=>$packageSha,'installable'=>true]]];if($command==='INSTALL')return ['ok'=>true,'state'=>'INSTALLED','version'=>'6.0.0-rc.1','deployedSha'=>$targetSha];throw new RuntimeException('unexpected command');};
 $service=new HubOperatorBridgeService($pdo,$poster);
 $status=$service->handle(['schemaVersion'=>1,'action'=>'system.status'],$now);ob_assert($status['state']==='READY'&&$status['activeMutationCount']===0&&$status['arbitraryShell']===false,'system status is bounded and shell-free');
 $gate=$service->handle(['schemaVersion'=>1,'action'=>'project.gate','project'=>'bay-excuse-x'],$now);ob_assert($gate['ready']===true&&$gate['source']['authority']==='AWH_VAULT','clean BAY project gate is ready');
 $pdo->prepare("INSERT INTO control_workspace_leases VALUES(?,?,?,'ACTIVE',?,?)")->execute([$project,'11111111-1111-4111-8111-111111111111',null,'2026-09-17T13:00:00+00:00',$now]);$blocked=$service->handle(['schemaVersion'=>1,'action'=>'project.gate','project'=>'BAY EXCUSE X'],$now);ob_assert($blocked['ready']===false&&$blocked['writer']['activeWorkspaceLeaseCount']===1,'active workspace lease blocks mutation gate');$pdo->exec('DELETE FROM control_workspace_leases');
 $task='22222222-2222-4222-8222-222222222222';$exec='33333333-3333-4333-8333-333333333333';$env='44444444-4444-4444-8444-444444444444';
 $pdo->prepare("INSERT INTO control_tasks VALUES(?,?,?,'other writer','RUNNING',NULL,NULL,0,NULL,NULL,'writer-key',NULL,?,?,NULL)")->execute([$task,$owner,$project,$now,$now]);
 $pdo->prepare("INSERT INTO control_task_executions VALUES(?,?,?,NULL,'VPS','project.mutate.deploy','RUNNING','writer',?,1,NULL,'{}',NULL,?,?)")->execute([$exec,$task,$project,'2026-09-17T13:00:00+00:00',$now,$now]);
 $pdo->prepare("INSERT INTO control_execution_envelopes VALUES(?,?,?,?,NULL,NULL,'task:writer','PROJECT_CANDIDATE','ACTIVE',NULL,?,?,?)")->execute([$env,$exec,$task,$project,'2026-09-17T13:00:00+00:00',$now,$now]);
 $blocked=$service->handle(['schemaVersion'=>1,'action'=>'project.gate','project'=>$project],$now);ob_assert($blocked['ready']===false&&$blocked['writer']['activeMutationCount']===1,'active mutation envelope blocks gate');$pdo->exec('DELETE FROM control_execution_envelopes; DELETE FROM control_task_executions; DELETE FROM control_tasks');
 $bay=$service->handle(['schemaVersion'=>1,'action'=>'bay.status'],$now);ob_assert(($bay['remote']['ok']??false)===true&&($bay['projectGate']['ready']??false)===true,'BAY status reuses signed remote authority');
 ob_code('OPERATOR_CONFIRMATION_REQUIRED',fn()=>$service->handle(['schemaVersion'=>1,'action'=>'bay.install','targetVersion'=>'6.0.0-rc.1','targetSha'=>$targetSha,'packageSha256'=>$packageSha],$now));
 $install=$service->handle(['schemaVersion'=>1,'action'=>'bay.install','targetVersion'=>'6.0.0-rc.1','targetSha'=>$targetSha,'packageSha256'=>$packageSha,'confirmation'=>'INSTALL_BAY_UPDATE'],$now);ob_assert($install['state']==='INSTALLED'&&($install['result']['version']??null)==='6.0.0-rc.1','BAY install uses exact staged package identity and PackageManager relay');
 $terminal=$pdo->query("SELECT e.state AS execution,t.state AS task,x.state AS envelope FROM control_task_executions e JOIN control_tasks t USING(task_id) JOIN control_execution_envelopes x USING(execution_id) WHERE e.required_capability='bay.remote_update.install' ORDER BY e.created_at DESC LIMIT 1")->fetch();ob_assert(is_array($terminal)&&$terminal['execution']==='COMPLETED'&&$terminal['task']==='COMPLETED'&&$terminal['envelope']==='RELEASED','BAY install holds then releases canonical mutation authority');
 ob_code('OPERATOR_BAY_PACKAGE_NOT_READY',fn()=>$service->handle(['schemaVersion'=>1,'action'=>'bay.install','targetVersion'=>'6.0.0-rc.2','targetSha'=>$targetSha,'packageSha256'=>$packageSha,'confirmation'=>'INSTALL_BAY_UPDATE'],$now));
 $failed=$pdo->query("SELECT e.state AS execution,t.state AS task,x.state AS envelope FROM control_task_executions e JOIN control_tasks t USING(task_id) JOIN control_execution_envelopes x USING(execution_id) WHERE e.required_capability='bay.remote_update.install' AND e.state='FAILED' LIMIT 1")->fetch();$activeAfterFailure=(int)$pdo->query("SELECT COUNT(*) FROM control_execution_envelopes x JOIN control_task_executions e USING(execution_id) WHERE e.required_capability='bay.remote_update.install' AND x.state='ACTIVE'")->fetchColumn();ob_assert(is_array($failed)&&$failed['execution']==='FAILED'&&$failed['task']==='FAILED'&&$failed['envelope']==='RELEASED'&&$activeAfterFailure===0,'failed BAY install releases canonical mutation authority without stale writer lock');
 ob_assert(count($calls)===4&&$calls[0]['payload']['command']==='STATUS'&&$calls[1]['payload']['command']==='STATUS'&&$calls[2]['payload']['command']==='INSTALL'&&$calls[3]['payload']['command']==='STATUS','remote relay stays bounded across success and failed package verification');
 ob_code('OPERATOR_ACTION_FORBIDDEN',fn()=>$service->handle(['schemaVersion'=>1,'action'=>'shell.exec','command'=>'id'],$now));
 $socket=(string)file_get_contents(dirname(__DIR__,2).'/deploy/systemd/awh-operator-bridge.socket');$unit=(string)file_get_contents(dirname(__DIR__,2).'/deploy/systemd/awh-operator-bridge@.service');$client=(string)file_get_contents(dirname(__DIR__,2).'/deploy/operator-bridge/awh-operator');
 ob_assert(str_contains($socket,'SocketMode=0600')&&str_contains($socket,'SocketUser=awh-remote')&&str_contains($socket,'Accept=yes'),'socket is private to awh-remote');
 ob_assert(str_contains($unit,'User=awh-hub')&&str_contains($unit,'NoNewPrivileges=true')&&str_contains($unit,"CapabilityBoundingSet=\n"),'handler stays unprivileged and capability-free');
 ob_assert(!str_contains($client,'sudo ')&&!str_contains((string)file_get_contents(dirname(__DIR__).'/src/HubOperatorBridgeService.php'),'shell_exec'),'client/service expose no sudo or arbitrary shell path');
 ob_assert($pdo->query('PRAGMA integrity_check')->fetchColumn()==='ok','fixture database integrity');echo "AWH Operator Bridge: PASS\n";
}finally{putenv('AWH_PROVIDER_CREDENTIAL_ROOT');if(is_dir($root)){foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST) as $f){$t=$f->getPathname();$f->isDir()&&!$f->isLink()?@rmdir($t):@unlink($t);}@rmdir($root);}}
