<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/src/HubSchemaMigration.php';
require_once dirname(__DIR__) . '/src/HubEnrollmentApiMigration.php';
require_once dirname(__DIR__) . '/src/HubControlPlaneMigration.php';
require_once dirname(__DIR__) . '/src/HubOwnerAuthMigration.php';
require_once dirname(__DIR__) . '/src/HubEnrollmentService.php';
require_once dirname(__DIR__) . '/src/HubControlPlaneService.php';
require_once dirname(__DIR__) . '/src/HubOwnerAuthService.php';
require_once dirname(__DIR__) . '/src/HubOwnerAuthRouter.php';
require_once dirname(__DIR__) . '/src/HubControlPlaneRouter.php';

function auth_assert(bool $condition, string $message): void { if (!$condition) throw new RuntimeException($message); }
function auth_json(array $body): string { return json_encode($body, JSON_THROW_ON_ERROR); }
function auth_cookie(array $response, string $name): string { foreach (($response['headers']['Set-Cookie'] ?? []) as $line) if (str_starts_with($line, $name . '=')) return explode(';', substr($line, strlen($name) + 1), 2)[0]; throw new RuntimeException('cookie missing'); }
function auth_response(HubOwnerAuthService $service, string $method, string $uri, array $server, array $body): array { return HubOwnerAuthRouter::dispatch($method, $uri, $server, $service, auth_json($body)); }
function auth_control(HubControlPlaneService $service, string $method, string $uri, array $server, array $body = []): array { return HubControlPlaneRouter::dispatch($method, $uri, $server, $service, auth_json($body)); }
function auth_setup_helper(string $database, string $username, string $password): array {
    $pipes = [];
    $process = proc_open([PHP_BINARY, dirname(__DIR__) . '/bin/setup-owner-auth.php', $username], [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes, null, ['AWH_HUB_DB_PATH' => $database]);
    if (!is_resource($process)) throw new RuntimeException('setup helper did not start');
    fwrite($pipes[0], $password . "\n"); fclose($pipes[0]);
    $stdout = stream_get_contents($pipes[1]); $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[1]); fclose($pipes[2]); $exit = proc_close($process);
    return ['exit' => $exit, 'stdout' => is_string($stdout) ? $stdout : '', 'stderr' => is_string($stderr) ? $stderr : ''];
}

if (!in_array('sqlite', PDO::getAvailableDrivers(), true)) { fwrite(STDOUT, "AWH owner auth: SKIP pdo_sqlite unavailable\n"); exit(77); }
$root = sys_get_temp_dir() . '/awh-owner-auth-' . bin2hex(random_bytes(5)); mkdir($root, 0700, true); $db = $root . '/awh.sqlite';
$schema = dirname(__DIR__) . '/schema.sql'; $m3e = dirname(__DIR__) . '/migrations/001_m3e_enrollment.sql'; $m3e2 = dirname(__DIR__) . '/migrations/002_m3e2_enrollment_api.sql'; $m4 = dirname(__DIR__) . '/migrations/003_m4_control_plane.sql'; $m5 = dirname(__DIR__) . '/migrations/004_owner_auth.sql';
$project = '113b45c0-23e1-408d-ae0f-ac5eca7f6900'; $owner = '223b45c0-23e1-408d-ae0f-ac5eca7f6900'; $device = '423b45c0-23e1-408d-ae0f-ac5eca7f6900'; $now = '2026-08-22T00:00:00Z'; putenv('AWH_CONTROL_ORIGIN=https://awh.test');
try {
    $pdo = new PDO('sqlite:' . $db, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]); $pdo->exec(file_get_contents($schema)); foreach (['enrollment_rate_limits','device_project_memberships','device_tokens','pairing_projects','pairing_codes','user_project_memberships','device_enrollments','owner_bootstrap','hub_users'] as $table) $pdo->exec('DROP TABLE IF EXISTS ' . $table); $pdo->exec("INSERT INTO projects VALUES('$project','Auth Project','node','$now',NULL,'$now','auth-test')");
    auth_assert(HubSchemaMigration::apply($db, $m3e, $now, false, $schema) === 'applied', 'm3e1'); auth_assert(HubEnrollmentApiMigration::apply($db, $m3e2, $now) === 'applied', 'm3e2'); $enrollment = HubEnrollmentService::openExisting($db); $bootstrap = $enrollment->initializeOwner($owner, 'Art Owner', [$project], $now); $enrollment->enrollDevice(['schemaVersion' => 1, 'pairingCode' => $bootstrap['initialPairingCode'], 'deviceId' => $device, 'displayName' => 'Mac', 'platform' => 'darwin', 'arch' => 'arm64', 'appVersion' => '1.0.0'], $now); auth_assert(HubControlPlaneMigration::apply($db, $m4, $now) === 'applied', 'm4'); auth_assert(HubOwnerAuthMigration::apply($db, $m5, $now) === 'applied', 'm5'); auth_assert(HubOwnerAuthMigration::apply($db, $m5, $now) === 'already-applied', 'm5 idempotent');
    $auth = HubOwnerAuthService::openExisting($db); $setup = auth_setup_helper($db, 'art', 'correct horse battery staple'); auth_assert($setup['exit'] === 0, 'owner setup helper exit'); auth_assert($setup['stdout'] === "OWNER_AUTH_PROVISIONED=PASS\nOWNER_AUTH_USERNAME=art\nRECOVERY_CODES=LOCAL_OPERATOR_BOUNDARY\n", 'owner setup helper contract'); auth_assert($setup['stderr'] === '', 'owner setup helper stderr'); auth_assert((int) $pdo->query('SELECT COUNT(*) FROM owner_passwords')->fetchColumn() === 1, 'one owner password');
    $base = ['CONTENT_TYPE' => 'application/json', 'HTTP_ORIGIN' => 'https://awh.test', 'REMOTE_ADDR' => '192.0.2.10', 'HTTP_USER_AGENT' => 'AWH test'];
    $bad = auth_response($auth, 'POST', '/api/v1/auth/login', $base, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'wrong', 'remember' => false]); auth_assert($bad['status'] === 401 && !str_contains($bad['body'], 'password_hash'), 'wrong password denied');
    $rateBase = $base; $rateBase['REMOTE_ADDR'] = '198.51.100.20'; for ($i = 0; $i < 5; $i++) { $rateFailure = auth_response($auth, 'POST', '/api/v1/auth/login', $rateBase, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'wrong', 'remember' => false]); auth_assert($rateFailure['status'] === 401, 'rate attempt denied'); } $rateLimited = auth_response($auth, 'POST', '/api/v1/auth/login', $rateBase, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'wrong', 'remember' => false]); auth_assert($rateLimited['status'] === 429, 'login rate limit');
    $invalidUser = auth_response($auth, 'POST', '/api/v1/auth/login', $base, ['schemaVersion' => 1, 'username' => 'not valid', 'password' => 'wrong', 'remember' => false]); auth_assert($invalidUser['status'] === 401, 'invalid username is generic');
    $login = auth_response($auth, 'POST', '/api/v1/auth/login', $base, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'correct horse battery staple', 'remember' => true]); auth_assert($login['status'] === 200 && !str_contains($login['body'], 'sessionToken'), 'owner login'); $cookie = auth_cookie($login, '__Host-awh_control_session'); $csrf = auth_cookie($login, 'awh_csrf');
    $control = auth_control(HubControlPlaneService::openExisting($db), 'GET', '/api/v1/control/projects', ['HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie]); auth_assert($control['status'] === 200 && str_contains($control['body'], $project), 'G1 control projects');
    $sessions = auth_response($auth, 'GET', '/api/v1/auth/sessions', ['HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie], []); auth_assert($sessions['status'] === 200 && str_contains($sessions['body'], '"current":true'), 'session listing');
    $taskServer = ['CONTENT_TYPE' => 'application/json', 'HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie, 'HTTP_X_AWH_CSRF' => $csrf]; $task = auth_control(HubControlPlaneService::openExisting($db), 'POST', '/api/v1/control/tasks', $taskServer, ['schemaVersion' => 1, 'projectId' => $project, 'goal' => 'Inspect the current project safely', 'idempotencyKey' => 'owner-auth-task-001']); auth_assert($task['status'] === 201 && str_contains($task['body'], 'WAITING_FOR_WORKER'), 'G6 canonical task ' . $task['status'] . ' ' . $task['body']);
    $step = auth_response($auth, 'POST', '/api/v1/auth/step-up', ['CONTENT_TYPE' => 'application/json', 'HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie, 'HTTP_X_AWH_CSRF' => $csrf], ['schemaVersion' => 1, 'password' => 'correct horse battery staple']); auth_assert($step['status'] === 200, 'step-up'); $recoveryCodes = $auth->createRecoveryCodesForSession($cookie, $csrf); auth_assert(count($recoveryCodes) === 8, 'recovery codes');
    $logout = auth_response($auth, 'POST', '/api/v1/auth/logout', ['CONTENT_TYPE' => 'application/json', 'HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie, 'HTTP_X_AWH_CSRF' => $csrf], ['schemaVersion' => 1]); auth_assert($logout['status'] === 200, 'logout'); $denied = auth_control(HubControlPlaneService::openExisting($db), 'GET', '/api/v1/control/projects', ['HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie]); auth_assert($denied['status'] === 401, 'logout revokes session');
    $login2 = auth_response($auth, 'POST', '/api/v1/auth/login', $base, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'correct horse battery staple', 'remember' => false]); $cookie2 = auth_cookie($login2, '__Host-awh_control_session'); $csrf2 = auth_cookie($login2, 'awh_csrf'); $login3 = auth_response($auth, 'POST', '/api/v1/auth/login', $base, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'correct horse battery staple', 'remember' => false]); $cookie3 = auth_cookie($login3, '__Host-awh_control_session'); $sessions2 = json_decode(auth_response($auth, 'GET', '/api/v1/auth/sessions', ['HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie2], [])['body'], true, 32, JSON_THROW_ON_ERROR); $other = array_values(array_filter($sessions2['sessions'] ?? [], static fn (array $row): bool => $row['current'] === false))[0] ?? null; auth_assert(is_array($other), 'second session listed'); $revoke = auth_response($auth, 'POST', '/api/v1/auth/sessions/' . $other['sessionId'] . '/revoke', ['CONTENT_TYPE' => 'application/json', 'HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie2, 'HTTP_X_AWH_CSRF' => $csrf2], ['schemaVersion' => 1]); auth_assert($revoke['status'] === 200, 'session revoke'); auth_assert(auth_control(HubControlPlaneService::openExisting($db), 'GET', '/api/v1/control/projects', ['HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie3])['status'] === 401, 'revoked session denied'); $new = 'new correct horse battery staple'; $change = auth_response($auth, 'POST', '/api/v1/auth/password', ['CONTENT_TYPE' => 'application/json', 'HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . $cookie2, 'HTTP_X_AWH_CSRF' => $csrf2], ['schemaVersion' => 1, 'oldPassword' => 'correct horse battery staple', 'newPassword' => $new]); auth_assert($change['status'] === 200, 'password change'); $oldLogin = auth_response($auth, 'POST', '/api/v1/auth/login', $base, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'correct horse battery staple', 'remember' => false]); auth_assert($oldLogin['status'] === 401, 'old password rejected');
    $recovery = $recoveryCodes[0]; $recovered = auth_response($auth, 'POST', '/api/v1/auth/recover', $base, ['schemaVersion' => 1, 'username' => 'art', 'recoveryCode' => $recovery, 'newPassword' => 'recovered correct horse staple']); auth_assert($recovered['status'] === 200, 'recovery ' . $recovered['body']); $replay = auth_response($auth, 'POST', '/api/v1/auth/recover', $base, ['schemaVersion' => 1, 'username' => 'art', 'recoveryCode' => $recovery, 'newPassword' => 'another recovered password']); auth_assert($replay['status'] === 401, 'recovery replay denied');
    $newLogin = auth_response($auth, 'POST', '/api/v1/auth/login', $base, ['schemaVersion' => 1, 'username' => 'art', 'password' => 'recovered correct horse staple', 'remember' => false]); auth_assert($newLogin['status'] === 200, 'recovered login'); $empty = $pdo->prepare('DELETE FROM user_project_memberships WHERE user_id = :user'); $empty->execute(['user' => $owner]); $emptyControl = auth_control(HubControlPlaneService::openExisting($db), 'GET', '/api/v1/control/projects', ['HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . auth_cookie($newLogin, '__Host-awh_control_session')]); auth_assert($emptyControl['status'] === 200 && str_contains($emptyControl['body'], '"projects":[]'), 'G10 empty project state'); $emptyTask = auth_control(HubControlPlaneService::openExisting($db), 'POST', '/api/v1/control/tasks', ['CONTENT_TYPE' => 'application/json', 'HTTP_ORIGIN' => 'https://awh.test', 'HTTP_COOKIE' => '__Host-awh_control_session=' . auth_cookie($newLogin, '__Host-awh_control_session'), 'HTTP_X_AWH_CSRF' => auth_cookie($newLogin, 'awh_csrf')], ['schemaVersion' => 1, 'projectId' => $project, 'goal' => 'Must not submit without membership', 'idempotencyKey' => 'owner-auth-empty-001']); auth_assert($emptyTask['status'] === 403, 'G10 task disabled by project authorization'); auth_assert(!str_contains(file_get_contents($db), 'correct horse'), 'plaintext password not in database'); auth_assert($pdo->query('PRAGMA foreign_key_check')->fetchAll() === [], 'foreign keys'); fwrite(STDOUT, "AWH owner auth: PASS\n");
} finally { putenv('AWH_CONTROL_ORIGIN'); @unlink($db); @rmdir($root); }
