<?php

declare(strict_types=1);

require_once __DIR__ . '/HubAccountHostingMigration.php';
require_once __DIR__ . '/HubProjectVault.php';

final class HubManagedHostingOperatorException extends RuntimeException
{
    public function __construct(string $message, public readonly string $codeName='HOSTING_OPERATOR_FAILED') { parent::__construct($message); }
}

/**
 * Root-only typed hosting operator. It consumes only canonical hosting
 * executions with allowlisted modes and fixed binaries; user text is never a
 * command and no arbitrary shell surface exists.
 */
final class HubManagedHostingOperator
{
    private const EXECUTOR='vps-hosting';
    private const CAPABILITIES=['hosting.site.provision','hosting.site.deploy','hosting.site.rollback','hosting.site.disable'];
    private const LEASE_SECONDS=300;
    /** @var Closure(list<string>,?string):array{code:int,out:string,err:string} */
    private readonly Closure $runner;

    public function __construct(private readonly PDO $pdo,private readonly HubProjectVault $vault,private readonly string $siteRoot,private readonly string $nginxAvailable,private readonly string $nginxEnabled,private readonly string $siteConfigRoot,?callable $runner=null)
    {
        foreach([$siteRoot,$nginxAvailable,$nginxEnabled,$siteConfigRoot] as $path) if($path===''||str_contains($path,"\0")||!str_starts_with($path,'/'))throw new HubManagedHostingOperatorException('Hosting path is invalid','HOSTING_CONFIG_INVALID');
        $this->runner=$runner===null?Closure::fromCallable([$this,'runFixed']):Closure::fromCallable($runner);
    }
    public static function fromEnvironment(PDO $pdo): self
    {
        return new self($pdo,HubProjectVault::fromEnvironment(),getenv('AWH_MANAGED_SITE_ROOT')?:'/srv/awh-sites',getenv('AWH_NGINX_SITES_AVAILABLE')?:'/etc/nginx/sites-available',getenv('AWH_NGINX_SITES_ENABLED')?:'/etc/nginx/sites-enabled',getenv('AWH_SITE_CONFIG_ROOT')?:'/etc/awh-sites');
    }

    public function tick(?string $now=null): array
    {
        $this->ready();$at=self::time($now??gmdate('c'));$this->advertise($at);$this->recover($at);$this->reconcileSource($at);$row=$this->claim($at);if($row===null)return ['schemaVersion'=>1,'state'=>'IDLE'];
        try{$checkpoint=json_decode((string)$row['checkpoint_json'],true,16,JSON_THROW_ON_ERROR);if(!is_array($checkpoint)||!is_string($checkpoint['mode']??null)||!is_string($checkpoint['siteId']??null))throw new HubManagedHostingOperatorException('Hosting checkpoint is invalid','HOSTING_CHECKPOINT_INVALID');$site=$this->site((string)$checkpoint['siteId']);
            $mode=(string)$checkpoint['mode'];$result=match($mode){'HOSTING_PROVISION','HOSTING_DEPLOY'=>$this->deploy($row,$site,$at),'HOSTING_ROLLBACK'=>$this->rollbackSite($row,$site,$checkpoint,$at),'HOSTING_DISABLE'=>$this->disable($row,$site,$at),default=>throw new HubManagedHostingOperatorException('Hosting mode is not allowed','HOSTING_CHECKPOINT_INVALID')};$this->complete($row,$site,$result,$at);return ['schemaVersion'=>1,'state'=>'COMPLETED','taskId'=>$row['task_id'],'siteId'=>$site['site_id'],'result'=>$result];
        }catch(HubManagedHostingOperatorException|HubProjectVaultException $error){$this->fail($row,$error instanceof HubManagedHostingOperatorException?$error->codeName:$error->codeName,$at);return ['schemaVersion'=>1,'state'=>'FAILED','taskId'=>$row['task_id'],'code'=>$error instanceof HubManagedHostingOperatorException?$error->codeName:$error->codeName];}
        catch(Throwable){$this->fail($row,'HOSTING_OPERATOR_FAILED',$at);return ['schemaVersion'=>1,'state'=>'FAILED','taskId'=>$row['task_id'],'code'=>'HOSTING_OPERATOR_FAILED'];}
    }

    private function deploy(array $execution,array $site,string $at): array
    {
        $revision=is_string($execution['vault_revision_id']??null)?(string)$execution['vault_revision_id']:$this->activeRevision((string)$site['project_id']);
        if($revision===null)throw new HubManagedHostingOperatorException('Project source is not ready','PROJECT_SOURCE_NOT_READY');
        $sitePath=$this->sitePath((string)$site['site_id']);$releaseId=self::uuid();$releaseDir=$sitePath.'/releases/'.$releaseId;
        $this->ensureDirectory($sitePath.'/releases',0750);$this->ensureDirectory($sitePath.'/shared',0750);$this->vault->materialize((string)$site['project_id'],$revision,$releaseDir);
        $runtime=$this->detectRuntime($releaseDir,(string)$site['runtime_type']);$database=$this->detectDatabase($releaseDir,$runtime,(string)$site['database_mode']);
        $relativeWebRoot=is_dir($releaseDir.'/public')&&(is_file($releaseDir.'/public/index.php')||is_file($releaseDir.'/public/index.html'))?'/public':'';
        $current=$sitePath.'/current';$stableRoot=$current.$relativeWebRoot;$identity=$this->ensureSiteIdentity((string)$site['site_id']);
        $this->run(['/bin/chown','-R',$identity.':'.$identity,$releaseDir]);$this->run(['/bin/chmod','-R','u=rwX,g=rX,o=',$releaseDir]);
        [$host,$cert,$key]=$this->serverIdentity();$port=(int)$site['listen_port'];if($port<8400||$port>8999)throw new HubManagedHostingOperatorException('Hosting port is invalid','HOSTING_CONFIG_INVALID');
        $db=$this->ensureDatabase($site,$database,$identity,$at);$previous=is_link($current)?readlink($current):null;$hadPrevious=is_string($previous)&&$previous!=='';
        $tmp=$current.'.next-'.bin2hex(random_bytes(4));if(!@symlink($releaseDir,$tmp)||!@rename($tmp,$current)){@unlink($tmp);throw new HubManagedHostingOperatorException('Release pointer could not be switched','HOSTING_RELEASE_FAILED');}
        $config=$this->nginxAvailable.'/awh-site-'.(string)$site['slug'].'.conf';$enabled=$this->nginxEnabled.'/awh-site-'.(string)$site['slug'].'.conf';$hadEnabled=is_link($enabled)||is_file($enabled);$oldConfig=is_file($config)&&!is_link($config)?@file_get_contents($config):null;
        try {
            $runtimeInfo=$this->configureRuntime($site,$runtime,$current,$stableRoot,$identity,$db,$port);
            $nginx=$this->renderNginx($site,$runtime,$stableRoot,$runtimeInfo,$port,$cert,$key);$this->atomicWrite($config,$nginx,0644);
            if(is_link($enabled)||file_exists($enabled))@unlink($enabled);if(!@symlink($config,$enabled))throw new HubManagedHostingOperatorException('Nginx site could not be enabled','HOSTING_NGINX_FAILED');
            $this->run(['/usr/sbin/nginx','-t']);$this->run(['/bin/systemctl','reload','nginx']);$this->restartRuntime($runtimeInfo);$health=$this->health($port,(string)$site['health_path'],$host);
        } catch(Throwable $error) {
            if($hadPrevious){$restore=$current.'.restore-'.bin2hex(random_bytes(4));if(@symlink($previous,$restore))@rename($restore,$current);}else @unlink($current);
            if(is_string($oldConfig))$this->atomicWrite($config,$oldConfig,0644);elseif(!$hadEnabled){@unlink($enabled);@unlink($config);} if($hadEnabled&&!is_link($enabled)&&is_file($config))@symlink($config,$enabled);
            $this->runOptional(['/usr/sbin/nginx','-t']);$this->runOptional(['/bin/systemctl','reload','nginx']);if(isset($runtimeInfo)&&is_array($runtimeInfo))$this->restartRuntimeOptional($runtimeInfo);
            throw $error;
        }
        $manifest=$this->vault->manifest((string)$site['project_id'],$revision);$contentSha=hash('sha256',json_encode($manifest,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));
        try{$this->pdo->exec('BEGIN IMMEDIATE');$previousRelease=$site['current_release_id'];if(is_string($site['rollback_release_id'])&&$site['rollback_release_id']!=='')$this->pdo->prepare("UPDATE control_site_releases SET state='RETIRED',retired_at=:at WHERE release_id=:id AND state='ROLLBACK'")->execute(['at'=>$at,'id'=>$site['rollback_release_id']]);if(is_string($previousRelease)&&$previousRelease!=='')$this->pdo->prepare("UPDATE control_site_releases SET state='ROLLBACK' WHERE release_id=:id AND state='ACTIVE'")->execute(['id'=>$previousRelease]);$this->pdo->prepare("INSERT INTO control_site_releases(release_id,site_id,vault_revision_id,content_sha256,state,created_at,activated_at,retired_at) VALUES(:release,:site,:revision,:sha,'ACTIVE',:at,:at,NULL)")->execute(['release'=>$releaseId,'site'=>$site['site_id'],'revision'=>$revision,'sha'=>$contentSha,'at'=>$at]);$this->pdo->prepare("UPDATE control_managed_sites SET runtime_type=:runtime,runtime_version=:version,database_mode=:db,state='READY',primary_host=:host,current_release_id=:release,rollback_release_id=:rollback,updated_at=:at WHERE site_id=:site")->execute(['runtime'=>$runtime,'version'=>$runtimeInfo['version'],'db'=>$database,'host'=>$host,'release'=>$releaseId,'rollback'=>is_string($previousRelease)&&$previousRelease!==''?$previousRelease:null,'at'=>$at,'site'=>$site['site_id']]);$this->pdo->prepare("UPDATE control_site_bindings SET is_primary=0 WHERE site_id=:site")->execute(['site'=>$site['site_id']]);$existing=$this->pdo->prepare("SELECT binding_id FROM control_site_bindings WHERE site_id=:site AND binding_kind='IP_PORT' AND host=:host AND port=:port ORDER BY created_at LIMIT 1");$existing->execute(['site'=>$site['site_id'],'host'=>$host,'port'=>$port]);$binding=$existing->fetchColumn();if(is_string($binding))$this->pdo->prepare("UPDATE control_site_bindings SET tls_mode='REUSE_EXISTING',state='ACTIVE',is_primary=1,updated_at=:at WHERE binding_id=:id")->execute(['at'=>$at,'id'=>$binding]);else $this->pdo->prepare("INSERT INTO control_site_bindings(binding_id,site_id,binding_kind,host,port,tls_mode,state,is_primary,created_at,updated_at) VALUES(:id,:site,'IP_PORT',:host,:port,'REUSE_EXISTING','ACTIVE',1,:at,:at)")->execute(['id'=>self::uuid(),'site'=>$site['site_id'],'host'=>$host,'port'=>$port,'at'=>$at]);$this->siteEvent((string)$site['site_id'],(string)$execution['task_id'],'SITE_READY','READY','เว็บไซต์ผ่าน health check และพร้อมใช้งาน',$at);$this->pdo->exec('COMMIT');}catch(Throwable $error){$this->rollbackDb();throw $error;}
        return ['url'=>'https://'.$host.':'.$port.'/','runtime'=>$runtime,'database'=>$database,'releaseId'=>$releaseId,'health'=>$health];
    }

    private function rollbackSite(array $execution,array $site,array $checkpoint,string $at): array
    {
        $target=$checkpoint['releaseId']??null;if(!is_string($target)||!self::validUuid($target))throw new HubManagedHostingOperatorException('Rollback release is invalid','ROLLBACK_NOT_READY');
        $q=$this->pdo->prepare("SELECT * FROM control_site_releases WHERE release_id=:release AND site_id=:site AND state='ROLLBACK'");$q->execute(['release'=>$target,'site'=>$site['site_id']]);$release=$q->fetch();if(!is_array($release))throw new HubManagedHostingOperatorException('Rollback point is not ready','ROLLBACK_NOT_READY');
        $dir=$this->sitePath((string)$site['site_id']).'/releases/'.$target;if(!is_dir($dir)||is_link($dir))throw new HubManagedHostingOperatorException('Rollback files are unavailable','ROLLBACK_NOT_READY');$current=$this->sitePath((string)$site['site_id']).'/current';$old=is_link($current)?readlink($current):null;$tmp=$current.'.rollback-'.bin2hex(random_bytes(4));if(!@symlink($dir,$tmp)||!@rename($tmp,$current)){@unlink($tmp);throw new HubManagedHostingOperatorException('Rollback pointer could not be switched','HOSTING_RELEASE_FAILED');}
        $unit=$this->nodeUnit((string)$site['site_id']);$this->runOptional(['/bin/systemctl','restart',$unit]);$this->run(['/usr/sbin/nginx','-t']);$this->run(['/bin/systemctl','reload','nginx']);
        try { [$host]=$this->serverIdentity();$this->health((int)$site['listen_port'],(string)$site['health_path'],$host); }
        catch(Throwable $error){if(is_string($old)&&$old!==''){$restore=$current.'.undo-'.bin2hex(random_bytes(4));if(@symlink($old,$restore))@rename($restore,$current);}$this->runOptional(['/bin/systemctl','restart',$unit]);$this->runOptional(['/bin/systemctl','reload','nginx']);throw $error;}
        try{$this->pdo->exec('BEGIN IMMEDIATE');$active=$site['current_release_id'];if(is_string($active)&&$active!=='')$this->pdo->prepare("UPDATE control_site_releases SET state='ROLLBACK' WHERE release_id=:id")->execute(['id'=>$active]);$this->pdo->prepare("UPDATE control_site_releases SET state='ACTIVE',activated_at=:at WHERE release_id=:id")->execute(['at'=>$at,'id'=>$target]);$this->pdo->prepare("UPDATE control_managed_sites SET current_release_id=:current,rollback_release_id=:rollback,state='READY',updated_at=:at WHERE site_id=:site")->execute(['current'=>$target,'rollback'=>is_string($active)?$active:null,'at'=>$at,'site'=>$site['site_id']]);$this->siteEvent((string)$site['site_id'],(string)$execution['task_id'],'ROLLBACK_COMPLETED','READY','กลับไปยังรุ่นก่อนหน้าเรียบร้อย',$at);$this->pdo->exec('COMMIT');}catch(Throwable $error){$this->rollbackDb();throw $error;}return ['releaseId'=>$target,'state'=>'READY'];
    }

    private function disable(array $execution,array $site,string $at): array
    {
        $enabled=$this->nginxEnabled.'/awh-site-'.(string)$site['slug'].'.conf';if(is_link($enabled)||file_exists($enabled))@unlink($enabled);$this->run(['/usr/sbin/nginx','-t']);$this->run(['/bin/systemctl','reload','nginx']);$unit=$this->nodeUnit((string)$site['site_id']);$this->runOptional(['/bin/systemctl','disable','--now',$unit]);try{$this->pdo->exec('BEGIN IMMEDIATE');$this->pdo->prepare("UPDATE control_managed_sites SET state='DISABLED',updated_at=:at WHERE site_id=:site")->execute(['at'=>$at,'site'=>$site['site_id']]);$this->pdo->prepare("UPDATE control_site_bindings SET state='DISABLED',is_primary=0,updated_at=:at WHERE site_id=:site")->execute(['at'=>$at,'site'=>$site['site_id']]);$this->siteEvent((string)$site['site_id'],(string)$execution['task_id'],'SITE_DISABLED','DISABLED','ปิด public route แล้ว โดยยังเก็บ release และข้อมูลไว้',$at);$this->pdo->exec('COMMIT');}catch(Throwable $error){$this->rollbackDb();throw $error;}return ['state'=>'DISABLED'];
    }

    private function detectRuntime(string $release,string $requested): string { if($requested!=='AUTO')return $requested;if(is_file($release.'/package.json'))return 'NODE';if(is_file($release.'/composer.json')||is_file($release.'/index.php')||is_file($release.'/public/index.php'))return 'PHP';return 'STATIC'; }
    private function detectDatabase(string $release,string $runtime,string $requested): string { if($requested!=='AUTO')return $requested;if($runtime==='PHP'){foreach(['config','app','src','public','index.php'] as $name){$path=$release.'/'.$name;if(is_file($path)&&$this->textLooksDb($path))return 'MARIADB';if(is_dir($path)){foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path,FilesystemIterator::SKIP_DOTS)) as $f){if($f instanceof SplFileInfo&&$f->isFile()&&$f->getSize()<262144&&preg_match('/\.(?:php|env\.example|ini)$/i',$f->getFilename())&&$this->textLooksDb($f->getPathname()))return 'MARIADB';}}}}if($runtime==='NODE'&&is_file($release.'/package.json')){$raw=@file_get_contents($release.'/package.json');if(is_string($raw)&&preg_match('/"(?:mysql2?|mariadb|sequelize|typeorm)"\s*:/i',$raw))return 'MARIADB';}return 'NONE'; }
    private function textLooksDb(string $path): bool { $raw=@file_get_contents($path,false,null,0,262144);return is_string($raw)&&preg_match('/(?:mysqli|mysql:|DB_HOST|DB_DATABASE|DATABASE_URL)/i',$raw)===1; }
    private function webRoot(string $release,string $runtime): string { if(is_dir($release.'/public')&&(is_file($release.'/public/index.php')||is_file($release.'/public/index.html')))return $release.'/public';return $release; }
    private function configureRuntime(array $site,string $runtime,string $release,string $webRoot,string $identity,array $db,int $publicPort): array { if($runtime==='STATIC')return ['kind'=>'STATIC','version'=>null];if($runtime==='PHP')return $this->configurePhp($site,$webRoot,$identity,$db);if($runtime==='NODE')return $this->configureNode($site,$release,$identity,$db,$publicPort);throw new HubManagedHostingOperatorException('Runtime is not supported','HOSTING_RUNTIME_UNAVAILABLE'); }
    private function configurePhp(array $site,string $webRoot,string $identity,array $db): array { $versions=glob('/etc/php/*/fpm/pool.d')?:[];usort($versions,static fn($a,$b)=>version_compare(basename(dirname(dirname($b))),basename(dirname(dirname($a)))));if($versions===[])throw new HubManagedHostingOperatorException('PHP-FPM is not installed','HOSTING_RUNTIME_UNAVAILABLE');$poolDir=$versions[0];$version=basename(dirname(dirname($poolDir)));if(!preg_match('/^\d+\.\d+$/',$version))throw new HubManagedHostingOperatorException('PHP-FPM version is invalid','HOSTING_RUNTIME_UNAVAILABLE');$short=substr(str_replace('-','',(string)$site['site_id']),0,10);$pool='awhsite_'.$short;$socket='/run/php/'.$pool.'.sock';$runtimeFile=$this->siteConfigRoot.'/'.$site['site_id'].'.php';$this->atomicWrite($runtimeFile,$this->phpRuntimePrelude($db),0640);$this->run(['/bin/chown','root:'.$identity,$runtimeFile]);$config="[{$pool}]\nuser = {$identity}\ngroup = {$identity}\nlisten = {$socket}\nlisten.owner = www-data\nlisten.group = www-data\nlisten.mode = 0660\npm = ondemand\npm.max_children = 6\npm.process_idle_timeout = 20s\nclear_env = yes\nphp_admin_value[open_basedir] = {$this->sitePath((string)$site['site_id'])}:/tmp\nphp_admin_value[auto_prepend_file] = {$runtimeFile}\nphp_admin_flag[log_errors] = on\n";$poolFile=$poolDir.'/'.$pool.'.conf';$this->atomicWrite($poolFile,$config,0644);$service='php'.$version.'-fpm';$this->run(['/bin/systemctl','reload',$service]);return ['kind'=>'PHP','version'=>$version,'socket'=>$socket,'service'=>$service]; }
    private function configureNode(array $site,string $release,string $identity,array $db,int $publicPort): array { $entry=$this->nodeEntry($release);if($entry===null)throw new HubManagedHostingOperatorException('Node project needs a built server entrypoint','NODE_BUILD_REQUIRED');$node='/usr/bin/node';if(!is_executable($node))throw new HubManagedHostingOperatorException('Node runtime is unavailable','HOSTING_RUNTIME_UNAVAILABLE');$internal=10000+($publicPort-8400);$env=$this->siteConfigRoot.'/'.$site['site_id'].'.env';$values=$db['env'];$values['PORT']=(string)$internal;$values['HOST']='127.0.0.1';$this->atomicWrite($env,$this->envFile($values),0640);$this->run(['/bin/chown','root:'.$identity,$env]);$unit=$this->nodeUnit((string)$site['site_id']);$unitPath='/etc/systemd/system/'.$unit;$content="[Unit]\nDescription=AWH managed site {$site['slug']}\nAfter=network.target\n\n[Service]\nType=simple\nUser={$identity}\nGroup={$identity}\nWorkingDirectory={$release}\nEnvironmentFile={$env}\nExecStart={$node} {$release}/{$entry}\nRestart=on-failure\nRestartSec=3\nNoNewPrivileges=true\nPrivateTmp=true\nProtectHome=true\nProtectSystem=strict\nReadWritePaths={$this->sitePath((string)$site['site_id'])}/shared\n\n[Install]\nWantedBy=multi-user.target\n";$this->atomicWrite($unitPath,$content,0644);$this->run(['/bin/systemctl','daemon-reload']);$this->run(['/bin/systemctl','enable','--now',$unit]);$version=trim($this->run(['/usr/bin/node','--version'])['out']);return ['kind'=>'NODE','version'=>$version,'upstream'=>'http://127.0.0.1:'.$internal,'service'=>$unit]; }
    private function nodeEntry(string $release): ?string { foreach(['dist/server.js','build/server.js','server.js','index.js'] as $entry)if(is_file($release.'/'.$entry)&&!is_link($release.'/'.$entry))return $entry;$raw=@file_get_contents($release.'/package.json');if(is_string($raw)){try{$j=json_decode($raw,true,16,JSON_THROW_ON_ERROR);$main=$j['main']??null;if(is_string($main)&&preg_match('#^[A-Za-z0-9._/-]{1,160}$#',$main)&&!str_contains($main,'..')&&is_file($release.'/'.$main))return $main;}catch(Throwable){}}return null; }
    private function restartRuntime(array $runtime): void { if(is_string($runtime['service']??null))$this->run(['/bin/systemctl','restart',(string)$runtime['service']]); }
    private function restartRuntimeOptional(array $runtime): void { if(is_string($runtime['service']??null))$this->runOptional(['/bin/systemctl','restart',(string)$runtime['service']]); }
    private function renderNginx(array $site,string $runtime,string $root,array $runtimeInfo,int $port,string $cert,string $key): string { $base="server {\n    listen {$port} ssl;\n    server_name _;\n    ssl_certificate {$cert};\n    ssl_certificate_key {$key};\n    client_max_body_size 64m;\n    add_header X-Content-Type-Options nosniff always;\n";if($runtime==='NODE')return $base."    location / { proxy_pass {$runtimeInfo['upstream']}; proxy_http_version 1.1; proxy_set_header Host \\$host; proxy_set_header X-Forwarded-Proto https; proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for; }\n}\n";$base.="    root {$root};\n    index index.php index.html index.htm;\n";if($runtime==='PHP')$base.="    location / { try_files \\$uri \\$uri/ /index.php?\\$query_string; }\n    location ~ \\.php$ { try_files \\$uri =404; include fastcgi_params; fastcgi_param SCRIPT_FILENAME \\$document_root\\$fastcgi_script_name; fastcgi_pass unix:{$runtimeInfo['socket']}; }\n    location ~ /\\. { deny all; }\n";else $base.="    location / { try_files \\$uri \\$uri/ =404; }\n";return $base."}\n"; }
    private function serverIdentity(): array
    {
        $output=$this->run(['/usr/sbin/nginx','-T'])['out'];
        $host=getenv('AWH_PUBLIC_HOST');
        if(!is_string($host)||!self::validHost($host)){
            preg_match_all('/server_name\s+([^;]+);/',$output,$matches);$host=null;
            foreach($matches[1]??[] as $chunk)foreach(preg_split('/\s+/',trim($chunk))?:[] as $candidate){
                if(self::validHost($candidate)&&$candidate!=='_'&&$candidate!=='localhost'&&!str_starts_with($candidate,'*.')){$host=$candidate;break 2;}
            }
        }
        if(!is_string($host))throw new HubManagedHostingOperatorException('Public VPS address is unavailable','HOSTING_PUBLIC_HOST_UNAVAILABLE');
        $cert=null;$key=null;
        if(filter_var($host,FILTER_VALIDATE_IP)!==false){
            $ipCert='/etc/letsencrypt/live/'.$host.'/fullchain.pem';$ipKey='/etc/letsencrypt/live/'.$host.'/privkey.pem';
            if(is_file($ipCert)&&!is_link($ipCert)&&is_file($ipKey)&&!is_link($ipKey)){$cert=$ipCert;$key=$ipKey;}
        }
        if($cert===null||$key===null){
            if(!preg_match('/ssl_certificate\s+([^;\s]+);/',$output,$c)||!preg_match('/ssl_certificate_key\s+([^;\s]+);/',$output,$k))throw new HubManagedHostingOperatorException('Existing HTTPS identity is unavailable','HOSTING_TLS_UNAVAILABLE');
            $cert=$c[1];$key=$k[1];
        }
        if(!str_starts_with($cert,'/')||!str_starts_with($key,'/'))throw new HubManagedHostingOperatorException('HTTPS identity is unsafe','HOSTING_TLS_UNAVAILABLE');
        $check=filter_var($host,FILTER_VALIDATE_IP)!==false?['/usr/bin/openssl','x509','-in',$cert,'-noout','-checkip',$host]:['/usr/bin/openssl','x509','-in',$cert,'-noout','-checkhost',$host];
        $verified=$this->runOptional($check);
        if($verified['code']!==0||!str_contains($verified['out'],'does match certificate'))throw new HubManagedHostingOperatorException('HTTPS certificate does not cover the public VPS address','HOSTING_TLS_UNAVAILABLE');
        return [$host,$cert,$key];
    }
    private function ensureDatabase(array $site,string $mode,string $identity,string $at): array
    {
        $env=[];if($mode==='NONE'){$this->pdo->prepare("UPDATE control_site_database_bindings SET engine='NONE',database_name=NULL,credential_ref=NULL,state='NOT_REQUIRED',updated_at=:at WHERE site_id=:site")->execute(['at'=>$at,'site'=>$site['site_id']]);return ['engine'=>'NONE','env'=>$env];}
        $short=substr(str_replace('-','',(string)$site['site_id']),0,12);if($mode==='SQLITE'){$dir=$this->sitePath((string)$site['site_id']).'/shared/data';$this->ensureDirectory($dir,0750);$file=$dir.'/app.sqlite';if(!file_exists($file)){$db=new PDO('sqlite:'.$file);$db=null;@chmod($file,0640);$this->run(['/bin/chown',$identity.':'.$identity,$file]);}$env=['DB_CONNECTION'=>'sqlite','DB_DATABASE'=>$file];$this->pdo->prepare("UPDATE control_site_database_bindings SET engine='SQLITE',database_name=:name,credential_ref=NULL,state='READY',updated_at=:at WHERE site_id=:site")->execute(['name'=>'app.sqlite','at'=>$at,'site'=>$site['site_id']]);return ['engine'=>'SQLITE','env'=>$env];}
        if($mode!=='MARIADB')throw new HubManagedHostingOperatorException('Database mode is unavailable','HOSTING_DATABASE_UNAVAILABLE');if(!is_executable('/usr/bin/mariadb'))throw new HubManagedHostingOperatorException('MariaDB is not installed','HOSTING_DATABASE_UNAVAILABLE');
        $secret=$this->siteConfigRoot.'/'.$site['site_id'].'.db.env';$existing=$this->readEnvFile($secret);$name='awh_'.$short;$user='awh_'.$short;$password=$existing['DB_PASSWORD']??null;if(!is_string($password)||!preg_match('/^[A-Za-z0-9_-]{32,96}$/',$password))$password=rtrim(strtr(base64_encode(random_bytes(30)),'+/','-_'),'=');
        $escaped=str_replace("'","''",$password);$sql="CREATE DATABASE IF NOT EXISTS `{$name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; CREATE USER IF NOT EXISTS '{$user}'@'localhost' IDENTIFIED BY '{$escaped}'; GRANT ALL PRIVILEGES ON `{$name}`.* TO '{$user}'@'localhost'; FLUSH PRIVILEGES;";$this->run(['/usr/bin/mariadb','--protocol=socket','--batch','--skip-column-names'],$sql);
        $env=['DB_CONNECTION'=>'mysql','DB_HOST'=>'localhost','DB_PORT'=>'3306','DB_DATABASE'=>$name,'DB_USERNAME'=>$user,'DB_USER'=>$user,'DB_PASSWORD'=>$password];if($existing===[])$this->atomicWrite($secret,$this->envFile($env),0600);$ref='site-db:'.(string)$site['site_id'];$this->pdo->prepare("UPDATE control_site_database_bindings SET engine='MARIADB',database_name=:name,credential_ref=:ref,state='READY',updated_at=:at WHERE site_id=:site")->execute(['name'=>$name,'ref'=>$ref,'at'=>$at,'site'=>$site['site_id']]);return ['engine'=>'MARIADB','env'=>$env];
    }
    private function readEnvFile(string $path): array { if(!is_file($path)||is_link($path))return [];$raw=@file_get_contents($path);if(!is_string($raw)||strlen($raw)>16384)return [];$out=[];foreach(preg_split('/\R/',$raw)?:[] as $line){if(!preg_match('/^([A-Z][A-Z0-9_]{0,63})=(.*)$/',$line,$m))continue;$out[$m[1]]=$m[2];}return $out; }

    private function phpRuntimePrelude(array $db): string { $rows=["<?php","// AWH managed runtime values; file is outside web root and root-owned."];foreach($db['env'] as $k=>$v){$q=var_export((string)$v,true);$rows[]="putenv('{$k}=' . {$q});";$rows[]="\$_ENV['{$k}'] = {$q};";$rows[]="\$_SERVER['{$k}'] = {$q};";}return implode("\n",$rows)."\n"; }
    private function envFile(array $values): string { $out='';foreach($values as $k=>$v){if(!preg_match('/^[A-Z][A-Z0-9_]{0,63}$/',$k))continue;$out.=$k.'='.str_replace(["\\","\n","\r","\""],["\\\\",'','','\\"'],(string)$v)."\n";}return $out; }
    private function health(int $port,string $path,string $host): string { $result=$this->run(['/usr/bin/curl','-kfsS','--max-time','12','-o','/dev/null','-w','%{http_code}','-H','Host: '.$host,'https://127.0.0.1:'.$port.$path]);$code=trim($result['out']);if(!preg_match('/^[23]\d\d$/',$code))throw new HubManagedHostingOperatorException('Website health check failed','HOSTING_HEALTH_FAILED');return $code; }
    private function ensureSiteIdentity(string $site): string { $short=substr(str_replace('-','',$site),0,10);$user='awhsite-'.$short;$check=$this->runOptional(['/usr/bin/id','-u',$user]);if($check['code']!==0)$this->run(['/usr/sbin/useradd','--system','--no-log-init','--home-dir',$this->sitePath($site),'--shell','/usr/sbin/nologin','--user-group',$user]);$this->ensureDirectory($this->sitePath($site),0750);$this->ensureDirectory($this->sitePath($site).'/shared',0750);$this->run(['/bin/chown','-R',$user.':'.$user,$this->sitePath($site).'/shared']);return $user; }
    private function sitePath(string $site): string { if(!self::validUuid($site))throw new HubManagedHostingOperatorException('Site identity is invalid','HOSTING_CHECKPOINT_INVALID');return rtrim($this->siteRoot,'/').'/'.strtolower($site); }
    private function nodeUnit(string $site): string { return 'awh-site-'.substr(str_replace('-','',$site),0,12).'.service'; }
    private function site(string $id): array { if(!self::validUuid($id))throw new HubManagedHostingOperatorException('Site identity is invalid','HOSTING_CHECKPOINT_INVALID');$q=$this->pdo->prepare('SELECT * FROM control_managed_sites WHERE site_id=:site');$q->execute(['site'=>strtolower($id)]);$row=$q->fetch();if(!is_array($row))throw new HubManagedHostingOperatorException('Site was not found','SITE_NOT_FOUND');return $row; }
    private function activeRevision(string $project): ?string { $q=$this->pdo->prepare("SELECT active_revision_id FROM control_project_vaults WHERE project_id=:project AND sync_state='SYNCED'");$q->execute(['project'=>$project]);$v=$q->fetchColumn();return is_string($v)&&self::validUuid($v)?strtolower($v):null; }
    private function advertise(string $at): void { $expires=gmdate('c',strtotime($at)+180);foreach(self::CAPABILITIES as $cap)$this->pdo->prepare("INSERT INTO control_executor_capabilities(executor_id,executor_kind,capability,version,observed_at,expires_at) VALUES(:id,'VPS',:cap,'m17',:at,:expires) ON CONFLICT(executor_id,capability) DO UPDATE SET version='m17',observed_at=excluded.observed_at,expires_at=excluded.expires_at")->execute(['id'=>self::EXECUTOR,'cap'=>$cap,'at'=>$at,'expires'=>$expires]); }
    private function claim(string $at): ?array { $expires=gmdate('c',strtotime($at)+self::LEASE_SECONDS);try{$this->pdo->exec('BEGIN IMMEDIATE');$caps="'".implode("','",self::CAPABILITIES)."'";$q=$this->pdo->query("SELECT e.*,t.goal FROM control_task_executions e JOIN control_tasks t ON t.task_id=e.task_id WHERE e.state='QUEUED' AND e.executor_kind='VPS' AND e.required_capability IN ({$caps}) AND t.state IN ('QUEUED','WAITING_FOR_WORKER') ORDER BY e.created_at,e.execution_id LIMIT 1");$row=$q->fetch();if(!is_array($row)){$this->pdo->exec('COMMIT');return null;}$u=$this->pdo->prepare("UPDATE control_task_executions SET state='RUNNING',lease_owner=:owner,lease_expires_at=:expires,attempt_count=attempt_count+1,updated_at=:at WHERE execution_id=:id AND state='QUEUED'");$u->execute(['owner'=>self::EXECUTOR,'expires'=>$expires,'at'=>$at,'id'=>$row['execution_id']]);if($u->rowCount()!==1){$this->pdo->exec('ROLLBACK');return null;}$this->pdo->prepare("UPDATE control_tasks SET state='RUNNING',progress=20,updated_at=:at WHERE task_id=:task")->execute(['at'=>$at,'task'=>$row['task_id']]);$this->pdo->exec('COMMIT');return $row;}catch(Throwable $e){$this->rollbackDb();throw new HubManagedHostingOperatorException('Hosting execution could not be claimed','HOSTING_CLAIM_FAILED');} }
    private function complete(array $row,array $site,array $result,string $at): void { $summary=($result['state']??null)==='DISABLED'?'ปิดเว็บไซต์แล้ว โดยเก็บข้อมูลและ release ไว้สำหรับกู้คืน':'เว็บไซต์พร้อมใช้งาน'.(is_string($result['url']??null)?' · '.$result['url']:'');try{$this->pdo->exec('BEGIN IMMEDIATE');$this->pdo->prepare("UPDATE control_task_executions SET state='COMPLETED',lease_owner=NULL,lease_expires_at=NULL,last_error_code=NULL,updated_at=:at WHERE execution_id=:id AND lease_owner=:owner")->execute(['at'=>$at,'id'=>$row['execution_id'],'owner'=>self::EXECUTOR]);$this->pdo->prepare("UPDATE control_tasks SET state='COMPLETED',progress=100,result_summary=:summary,failure_code=NULL,updated_at=:at WHERE task_id=:task")->execute(['summary'=>$summary,'at'=>$at,'task'=>$row['task_id']]);$this->pdo->prepare("INSERT INTO control_task_events(event_id,task_id,state,progress,message,occurred_at) VALUES(:id,:task,'COMPLETED',100,:message,:at)")->execute(['id'=>self::uuid(),'task'=>$row['task_id'],'message'=>$summary,'at'=>$at]);$this->pdo->exec('COMMIT');}catch(Throwable){$this->rollbackDb();} }
    private function fail(array $row,string $code,string $at): void { $human=match($code){'PROJECT_SOURCE_NOT_READY'=>'AWH กำลังรอ Source ของโปรเจกต์ก่อนเตรียมเว็บไซต์','HOSTING_TLS_UNAVAILABLE'=>'ยังไม่พบ HTTPS identity ที่ใช้กับ VPS ได้','NODE_BUILD_REQUIRED'=>'โปรเจกต์ Node ยังไม่มี server build ที่พร้อมรัน','HOSTING_HEALTH_FAILED'=>'เว็บไซต์เริ่มทำงานแล้วแต่ health check ยังไม่ผ่าน',default=>'AWH ยังเตรียมเว็บไซต์ไม่สำเร็จ และเก็บรายละเอียดไว้ให้ Owner ตรวจ'};$waiting=in_array($code,['PROJECT_SOURCE_NOT_READY'],true);try{$this->pdo->exec('BEGIN IMMEDIATE');$this->pdo->prepare('UPDATE control_task_executions SET state=:state,lease_owner=NULL,lease_expires_at=NULL,last_error_code=:code,updated_at=:at WHERE execution_id=:id')->execute(['state'=>$waiting?'WAITING_FOR_CAPABILITY':'FAILED','code'=>$code,'at'=>$at,'id'=>$row['execution_id']]);$this->pdo->prepare('UPDATE control_tasks SET state=:state,progress=0,failure_code=:code,result_summary=:summary,updated_at=:at WHERE task_id=:task')->execute(['state'=>$waiting?'WAITING_FOR_WORKER':'FAILED','code'=>$code,'summary'=>$human,'at'=>$at,'task'=>$row['task_id']]);$checkpoint=json_decode((string)$row['checkpoint_json'],true);if(is_array($checkpoint)&&is_string($checkpoint['siteId']??null)){$this->pdo->prepare("UPDATE control_managed_sites SET state=:state,updated_at=:at WHERE site_id=:site")->execute(['state'=>$waiting?'DRAFT':'FAILED','at'=>$at,'site'=>$checkpoint['siteId']]);$this->siteEvent((string)$checkpoint['siteId'],(string)$row['task_id'],'SITE_BLOCKED',$waiting?'WAITING':'FAILED',$human,$at);}$this->pdo->exec('COMMIT');}catch(Throwable){$this->rollbackDb();} }
    private function recover(string $at): void { $q=$this->pdo->prepare("SELECT execution_id,task_id FROM control_task_executions WHERE executor_kind='VPS' AND required_capability LIKE 'hosting.%' AND state='RUNNING' AND lease_expires_at<=:at");$q->execute(['at'=>$at]);foreach($q->fetchAll() as $r){$this->pdo->prepare("UPDATE control_task_executions SET state='QUEUED',lease_owner=NULL,lease_expires_at=NULL,last_error_code='LEASE_EXPIRED',updated_at=:at WHERE execution_id=:id")->execute(['at'=>$at,'id'=>$r['execution_id']]);$this->pdo->prepare("UPDATE control_tasks SET state='WAITING_FOR_WORKER',failure_code='LEASE_EXPIRED',updated_at=:at WHERE task_id=:task")->execute(['at'=>$at,'task'=>$r['task_id']]);} }
    private function reconcileSource(string $at): void { $q=$this->pdo->query("SELECT e.execution_id,e.task_id,e.project_id,t.goal FROM control_task_executions e JOIN control_tasks t ON t.task_id=e.task_id WHERE e.executor_kind='VPS' AND e.required_capability IN ('hosting.site.provision','hosting.site.deploy') AND e.state='WAITING_FOR_CAPABILITY' AND e.last_error_code='PROJECT_SOURCE_NOT_READY' LIMIT 25");foreach($q->fetchAll() as $r){$revision=$this->activeRevision((string)$r['project_id']);if($revision===null)continue;$this->pdo->prepare("UPDATE control_task_executions SET vault_revision_id=:revision,state='QUEUED',last_error_code=NULL,updated_at=:at WHERE execution_id=:id")->execute(['revision'=>$revision,'at'=>$at,'id'=>$r['execution_id']]);$this->pdo->prepare("UPDATE control_tasks SET state='QUEUED',failure_code=NULL,updated_at=:at WHERE task_id=:task")->execute(['at'=>$at,'task'=>$r['task_id']]);} }
    private function siteEvent(string $site,?string $task,string $name,string $state,string $message,string $at): void { $this->pdo->prepare('INSERT INTO control_site_events(event_id,site_id,task_id,event_name,state,message,occurred_at) VALUES(:id,:site,:task,:name,:state,:message,:at)')->execute(['id'=>self::uuid(),'site'=>$site,'task'=>$task,'name'=>$name,'state'=>$state,'message'=>$message,'at'=>$at]); }
    private function ready(): void { HubAccountHostingMigration::assertCapabilityReady($this->pdo,dirname(__DIR__).'/migrations/016_account_hosting.sql'); }
    private function ensureDirectory(string $path,int $mode): void { if(is_link($path))throw new HubManagedHostingOperatorException('Hosting directory is unsafe','HOSTING_STORAGE_UNSAFE');if(!is_dir($path)&&!@mkdir($path,$mode,true)&&!is_dir($path))throw new HubManagedHostingOperatorException('Hosting directory is unavailable','HOSTING_STORAGE_UNAVAILABLE');@chmod($path,$mode); }
    private function atomicWrite(string $path,string $content,int $mode): void { $dir=dirname($path);$this->ensureDirectory($dir,0750);if(is_link($path))throw new HubManagedHostingOperatorException('Hosting config path is unsafe','HOSTING_STORAGE_UNSAFE');$tmp=$path.'.tmp-'.bin2hex(random_bytes(6));if(@file_put_contents($tmp,$content,LOCK_EX)!==strlen($content)){@unlink($tmp);throw new HubManagedHostingOperatorException('Hosting config could not be written','HOSTING_STORAGE_UNAVAILABLE');}@chmod($tmp,$mode);if(!@rename($tmp,$path)){@unlink($tmp);throw new HubManagedHostingOperatorException('Hosting config could not be activated','HOSTING_STORAGE_UNAVAILABLE');} }
    private function run(array $command,?string $stdin=null): array { $result=($this->runner)($command,$stdin);if(($result['code']??1)!==0)throw new HubManagedHostingOperatorException('Typed hosting operation failed','HOSTING_SYSTEM_OPERATION_FAILED');return $result; }
    private function runOptional(array $command,?string $stdin=null): array { return ($this->runner)($command,$stdin); }
    private function runFixed(array $command,?string $stdin=null): array { $allowed=['/bin/chown','/bin/chmod','/bin/systemctl','/usr/bin/id','/usr/sbin/useradd','/usr/sbin/nginx','/usr/bin/node','/usr/bin/curl','/usr/bin/mariadb','/usr/bin/openssl'];if($command===[]||!in_array($command[0],$allowed,true))return ['code'=>126,'out'=>'','err'=>'blocked'];$spec=[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']];$proc=proc_open($command,$spec,$pipes,null,['PATH'=>'/usr/sbin:/usr/bin:/sbin:/bin']);if(!is_resource($proc))return ['code'=>127,'out'=>'','err'=>'unavailable'];if($stdin!==null)fwrite($pipes[0],$stdin);fclose($pipes[0]);$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($proc);return ['code'=>$code,'out'=>is_string($out)?substr($out,0,1048576):'','err'=>is_string($err)?substr($err,0,65536):'']; }
    private function rollbackDb(): void { try{$this->pdo->exec('ROLLBACK');}catch(Throwable){} }
    private static function validHost(string $v): bool { return filter_var($v,FILTER_VALIDATE_IP)!==false||preg_match('/^[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?$/i',$v)===1; }
    private static function validUuid(string $v): bool { return preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',$v)===1; }
    private static function uuid(): string { $b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4)); }
    private static function time(string $v): string { if(strtotime($v)===false)throw new HubManagedHostingOperatorException('Time is invalid','HOSTING_CHECKPOINT_INVALID');return gmdate('c',strtotime($v)); }
}
