<?php

declare(strict_types=1);

require_once __DIR__ . '/HubBrowserOriginPolicy.php';

final class HubOwnerAuthRouter
{
    private const MAX_BODY = 16384;

    public static function dispatch(string $method, string $uri, array $server, HubOwnerAuthService $service, string $body): array
    {
        $requestId = bin2hex(random_bytes(16)); $headers = ['Content-Type' => 'application/json; charset=utf-8', 'Cache-Control' => 'no-store', 'X-Content-Type-Options' => 'nosniff', 'Referrer-Policy' => 'no-referrer', 'Content-Security-Policy' => "default-src 'none'"];
        $path = (string) (parse_url($uri, PHP_URL_PATH) ?: '');
        if (strlen($body) > self::MAX_BODY) return self::response(413, self::error('BODY_TOO_LARGE', $requestId), $headers);
        try {
            if ($method === 'GET' && $path === '/api/v1/auth/session') { self::sameOriginIfBrowser($server); $session = $service->session(self::cookie($server)); $headers['Set-Cookie'] = ['awh_csrf=' . $session['csrfToken'] . '; Path=/; Secure; SameSite=Strict; Max-Age=28800']; return self::response(200, ['schemaVersion' => 1, 'authenticated' => true, 'expiresAt' => $session['expiresAt'], 'remembered' => $session['remembered'], 'csrfToken' => $session['csrfToken'], 'userId' => $session['userId'], 'requestId' => $requestId], $headers); }
            if ($method === 'GET' && $path === '/api/v1/auth/sessions') { self::sameOriginIfBrowser($server); return self::response(200, $service->sessions(self::cookie($server)) + ['requestId' => $requestId], $headers); }
            if ($method !== 'POST') return self::response(405, self::error('METHOD_NOT_ALLOWED', $requestId), $headers + ['Allow' => 'GET, POST']);
            self::jsonContent($server); $payload = self::json($body);
            if ($path === '/api/v1/auth/login') { self::sameOrigin($server); self::keys($payload, ['password', 'remember', 'schemaVersion', 'username']); if (($payload['schemaVersion'] ?? null) !== 1 || !is_bool($payload['remember'] ?? null)) throw new HubOwnerAuthException('Login request is invalid', 'PAYLOAD_INVALID'); $session = $service->login((string) ($payload['username'] ?? ''), (string) ($payload['password'] ?? ''), $payload['remember'], self::rateKey($server)); $headers['Set-Cookie'] = self::cookies($session); return self::response(200, ['schemaVersion' => 1, 'authenticated' => true, 'expiresAt' => $session['expiresAt'], 'remembered' => $session['remembered'], 'userId' => $session['userId'], 'requestId' => $requestId], $headers); }
            if ($path === '/api/v1/auth/recover') { self::sameOrigin($server); self::keys($payload, ['newPassword', 'recoveryCode', 'schemaVersion', 'username']); if (($payload['schemaVersion'] ?? null) !== 1) throw new HubOwnerAuthException('Recovery request is invalid', 'PAYLOAD_INVALID'); $service->recover((string) $payload['username'], (string) $payload['recoveryCode'], (string) $payload['newPassword'], null, self::rateKey($server)); return self::response(200, ['schemaVersion' => 1, 'authenticated' => false, 'requestId' => $requestId], $headers); }
            $token = self::cookie($server); $csrf = self::csrf($server); self::sameOrigin($server);
            if ($path === '/api/v1/auth/logout') { self::keys($payload, ['schemaVersion']); $service->logout($token); return self::response(200, ['schemaVersion' => 1, 'authenticated' => false, 'requestId' => $requestId], $headers + ['Set-Cookie' => self::expiredCookies()]); }
            if ($path === '/api/v1/auth/logout-all') { self::keys($payload, ['schemaVersion']); $service->logoutAll($token); return self::response(200, ['schemaVersion' => 1, 'authenticated' => false, 'requestId' => $requestId], $headers + ['Set-Cookie' => self::expiredCookies()]); }
            if ($path === '/api/v1/auth/password') { self::keys($payload, ['newPassword', 'oldPassword', 'schemaVersion']); if (($payload['schemaVersion'] ?? null) !== 1) throw new HubOwnerAuthException('Password request is invalid', 'PAYLOAD_INVALID'); $service->changePassword($token, $csrf, (string) $payload['oldPassword'], (string) $payload['newPassword']); return self::response(200, ['schemaVersion' => 1, 'reauthenticate' => true, 'requestId' => $requestId], $headers + ['Set-Cookie' => self::expiredCookies()]); }
            if ($path === '/api/v1/auth/identity') { self::keys($payload, ['currentPassword', 'schemaVersion', 'username']); if (($payload['schemaVersion'] ?? null) !== 1) throw new HubOwnerAuthException('Identity request is invalid', 'PAYLOAD_INVALID'); $service->changeUsername($token, $csrf, (string) $payload['currentPassword'], (string) $payload['username']); return self::response(200, ['schemaVersion' => 1, 'reauthenticate' => true, 'requestId' => $requestId], $headers + ['Set-Cookie' => self::expiredCookies()]); }
            if ($path === '/api/v1/auth/recovery-codes') { self::keys($payload, ['schemaVersion']); return self::response(200, ['schemaVersion' => 1, 'recoveryCodes' => $service->createRecoveryCodesForSession($token, $csrf), 'requestId' => $requestId], $headers); }
            if ($path === '/api/v1/auth/step-up') { self::keys($payload, ['password', 'schemaVersion']); if (($payload['schemaVersion'] ?? null) !== 1) throw new HubOwnerAuthException('Step-up request is invalid', 'PAYLOAD_INVALID'); return self::response(200, ['schemaVersion' => 1] + $service->stepUp($token, $csrf, (string) $payload['password']) + ['requestId' => $requestId], $headers); }
            if (preg_match('#^/api/v1/auth/sessions/([0-9a-f-]{36})/revoke$#i', $path, $match) === 1) { self::keys($payload, ['schemaVersion']); if (($payload['schemaVersion'] ?? null) !== 1) throw new HubOwnerAuthException('Session request is invalid', 'PAYLOAD_INVALID'); $service->revokeSession($token, $csrf, $match[1]); return self::response(200, ['schemaVersion' => 1, 'revoked' => true, 'requestId' => $requestId], $headers); }
            return self::response(404, self::error('NOT_FOUND', $requestId), $headers);
        } catch (Throwable $error) { $code = $error instanceof HubOwnerAuthException ? $error->codeName : 'AUTH_UNAVAILABLE'; $status = match ($code) { 'AUTH_FAILED', 'RECOVERY_FAILED' => 401, 'RATE_LIMITED' => 429, 'CSRF_REJECTED', 'ORIGIN_FORBIDDEN' => 403, 'SESSION_INVALID', 'SESSION_EXPIRED', 'AUTH_SCHEMA_NOT_READY' => 401, 'SESSION_NOT_FOUND' => 404, 'USERNAME_UNAVAILABLE' => 409, 'PASSWORD_INVALID', 'USERNAME_INVALID', 'PAYLOAD_INVALID', 'SCHEMA_FIELDS' => 400, default => 503 }; return self::response($status, self::error($code, $requestId), $headers); }
    }

    private static function cookies(array $session): array { $max = max(1, strtotime((string) $session['expiresAt']) - time()); return ['__Host-awh_control_session=' . $session['sessionToken'] . '; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=' . $max, 'awh_csrf=' . $session['csrfToken'] . '; Path=/; Secure; SameSite=Strict; Max-Age=' . $max]; }
    private static function expiredCookies(): array { return ['__Host-awh_control_session=; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=0', 'awh_csrf=; Path=/; Secure; SameSite=Strict; Max-Age=0']; }
    private static function jsonContent(array $server): void { if (!isset($server['CONTENT_TYPE']) || !is_string($server['CONTENT_TYPE']) || stripos($server['CONTENT_TYPE'], 'application/json') !== 0) throw new HubOwnerAuthException('JSON content type is required', 'PAYLOAD_INVALID'); }
    private static function json(string $body): array { try { $value = json_decode($body, true, 32, JSON_THROW_ON_ERROR); } catch (JsonException) { throw new HubOwnerAuthException('Payload is invalid', 'PAYLOAD_INVALID'); } if (!is_array($value) || array_is_list($value)) throw new HubOwnerAuthException('Payload is invalid', 'PAYLOAD_INVALID'); return $value; }
    private static function keys(array $value, array $allowed): void { $actual = array_keys($value); sort($actual); sort($allowed); if ($actual !== $allowed) throw new HubOwnerAuthException('Payload fields are invalid', 'SCHEMA_FIELDS'); }
    private static function cookie(array $server): string { $raw = $server['HTTP_COOKIE'] ?? ''; if (!is_string($raw)) throw new HubOwnerAuthException('Session is required', 'SESSION_INVALID'); foreach (explode(';', $raw) as $part) { [$key, $value] = array_pad(explode('=', trim($part), 2), 2, ''); if ($key === '__Host-awh_control_session' && preg_match('/^[A-Za-z0-9_-]{32,128}$/', $value)) return $value; } throw new HubOwnerAuthException('Session is required', 'SESSION_INVALID'); }
    private static function csrf(array $server): string { $value = $server['HTTP_X_AWH_CSRF'] ?? ''; if (!is_string($value) || !preg_match('/^[A-Za-z0-9_-]{32,128}$/', $value)) throw new HubOwnerAuthException('Request could not be verified', 'CSRF_REJECTED'); return $value; }
    private static function rateKey(array $server): string { $ip = isset($server['REMOTE_ADDR']) && is_string($server['REMOTE_ADDR']) ? $server['REMOTE_ADDR'] : 'unknown'; $agent = isset($server['HTTP_USER_AGENT']) && is_string($server['HTTP_USER_AGENT']) ? substr($server['HTTP_USER_AGENT'], 0, 160) : 'unknown'; return $ip . "\n" . $agent; }
    private static function sameOrigin(array $server): void { if (!HubBrowserOriginPolicy::mutationAllowed($server)) throw new HubOwnerAuthException('Origin is not authorized', 'ORIGIN_FORBIDDEN'); }
    private static function sameOriginIfBrowser(array $server): void { if (!HubBrowserOriginPolicy::safeReadAllowed($server)) throw new HubOwnerAuthException('Origin is not authorized', 'ORIGIN_FORBIDDEN'); }
    private static function error(string $code, string $id): array { return ['schemaVersion' => 1, 'error' => 'ERROR', 'code' => $code, 'requestId' => $id, 'message' => $code === 'AUTH_FAILED' || $code === 'RECOVERY_FAILED' ? 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง' : 'AWH ไม่สามารถดำเนินการได้']; }
    private static function response(int $status, array $body, array $headers): array { return ['status' => $status, 'headers' => $headers, 'body' => json_encode($body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . "\n"]; }
}
