export const DESKTOP_WEB_PREFERENCES = Object.freeze({
  nodeIntegration: false,
  contextIsolation: true,
  sandbox: true,
  webviewTag: false,
});

export const DESKTOP_IPC = Object.freeze({
  overview: 'art-agent:overview',
  projects: 'art-agent:projects',
  projectContext: 'art-agent:project-context',
  registerProject: 'art-agent:register-project',
  initializeProject: 'art-agent:initialize-project',
  initializeProjectMemory: 'art-agent:initialize-project-memory',
  selectProject: 'art-agent:select-project',
  locateProject: 'art-agent:locate-project',
  chooseWorkspace: 'art-agent:choose-workspace',
  setPermissions: 'art-agent:set-permissions',
  remoteConnect: 'art-agent:remote-connect',
  remoteStop: 'art-agent:remote-stop',
  enrollmentState: 'art-agent:enrollment-state',
  enrollmentLogin: 'art-agent:enrollment-login',
  enrollmentPair: 'art-agent:enrollment-pair',
  enrollmentIssuePairing: 'art-agent:enrollment-issue-pairing',
  enrollmentRotate: 'art-agent:enrollment-rotate',
  enrollmentRevoke: 'art-agent:enrollment-revoke',
  ownerPasswordReset: 'art-agent:owner-password-reset',
  firstRun: 'art-agent:first-run',
  trustOwner: 'art-agent:trust-owner',
  autopilotOverview: 'art-agent:autopilot-overview',
  autopilotStart: 'art-agent:autopilot-start',
  autopilotTasks: 'art-agent:autopilot-tasks',
  autopilotArtifacts: 'art-agent:autopilot-artifacts',
  autopilotRemoteResults: 'art-agent:autopilot-remote-results',
  autopilotContinuity: 'art-agent:autopilot-continuity',
  autopilotCheckpointMemory: 'art-agent:autopilot-checkpoint-memory',
  workConversation: 'art-agent:work-conversation',
  workSubmit: 'art-agent:work-submit',
  workspaceContinuity: 'art-agent:workspace-continuity',
  workspaceSync: 'art-agent:workspace-sync',
  workspaceTakeover: 'art-agent:workspace-takeover',
  workerState: 'art-agent:worker-state',
  workerRunOnce: 'art-agent:worker-run-once',
  restart: 'art-agent:restart',
  openDataDir: 'art-agent:open-data-dir',
});
