import { bindManagedSiteDomain, createManagedSite, listManagedSites, loadAuthSession, loadControlData, managedSiteAction } from './control-plane-adapter.js?release=__AWH_WEB_RELEASE_ID__';

const $=(id)=>document.getElementById(id);
const CANONICAL_DOMAIN='kruart.online';
let control=null;let sites=[];let policies={};let dnsPlan=null;let ecosystem=null;let pendingConfirm=null;

const statusLabel=(state)=>({READY:'พร้อมใช้งาน',PROVISIONING:'กำลังเตรียม',QUEUED:'รอดำเนินการ',FAILED:'ต้องตรวจสอบ',DISABLED:'ปิดการเผยแพร่',DRAFT:'รอ Source'})[state]||state||'ไม่ทราบ';
const runtimeLabel=(value)=>({AUTO:'อัตโนมัติ',PHP:'PHP',NODE:'Node',STATIC:'Static'})[value]||value||'—';
function slugify(value){return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48);}
function desiredHost(slug){return slug?`${slug}.${CANONICAL_DOMAIN}`:`ชื่อเว็บ.${CANONICAL_DOMAIN}`;}
function renderUrlPreview(){const slug=$('site-slug').value.trim();$('site-url-preview').textContent=`https://${desiredHost(slug)}`;}
async function mutate(action,retried=false){try{return await action();}catch(error){if(error?.code==='CSRF_REJECTED'&&!retried){await loadAuthSession();return mutate(action,true);}throw error;}}
function policy(action){return policies[`hosting.site.${action}`]||{risk:'MEDIUM',confirmationRequired:true,stepUpRequired:false};}
function confirmationCopy(site,action){return ({deploy:`Deploy รุ่นล่าสุดของ “${site.name}” ไป Production โดย AWH จะเก็บ rollback point ก่อนสลับรุ่น`,rollback:`ย้อน “${site.name}” กลับไปยังรุ่นก่อนหน้าที่ตรวจสอบแล้ว โดยไม่ลบข้อมูลถาวร`,disable:`ปิดการเผยแพร่ “${site.name}” ชั่วคราว โดยยังเก็บ Source, Database, Release และ Backup ไว้`,bind_domain:`เชื่อม https://${desiredHost(site.slug||'')} กับ “${site.name}” AWH จะรอ DNS แล้วเปิด HTTPS ให้อัตโนมัติ`})[action]||`ดำเนินการกับ “${site.name}”`;}
function confirmAction(site,action,handler){const rule=policy(action);if(!rule.confirmationRequired)return mutate(handler);return new Promise((resolve,reject)=>{pendingConfirm={handler,resolve,reject};$('hosting-confirm-title').textContent=action==='rollback'?'ยืนยัน Rollback':action==='disable'?'ยืนยันปิดการเผยแพร่':action==='bind_domain'?'ยืนยันเชื่อมโดเมน':'ยืนยัน Deploy';$('hosting-confirm-copy').textContent=confirmationCopy(site,action);$('hosting-confirm-message').textContent='';$('hosting-confirm').hidden=false;setTimeout(()=>$('hosting-confirm-submit').focus(),0);});}
function renderEcosystem(){const host=$('hosting-ecosystem');if(!host)return;host.replaceChildren();const operator=ecosystem?.operator||{};const tasks=ecosystem?.tasks||{};const cards=[['Hosting Operator',operator.state==='ONLINE'?'พร้อม':'ออฟไลน์',operator.state==='ONLINE'?`capability ${operator.freshCapabilities||0}/${operator.requiredCapabilities||0}`:'งานใหม่จะรอจน operator กลับมา'],['DNS',dnsPlan?.provider||'MANUAL',dnsPlan?.automatic?'จัดการอัตโนมัติ':'แสดงค่าที่ต้องตั้งให้ชัดเจน'],['HTTPS',ecosystem?.tls?.mode==='LETS_ENCRYPT'?'Let’s Encrypt':'ตรวจอัตโนมัติ','เปิดหลัง DNS + health check ผ่าน'],['งาน Hosting',`${tasks.running||0} กำลังทำ · ${tasks.waiting||0} รอ`,`${tasks.queued||0} เข้าคิว · ${tasks.failed||0} ต้องตรวจสอบ`]];for(const [label,value,note] of cards){const card=document.createElement('div');card.className='ecosystem-card';const small=document.createElement('span');small.textContent=label;const strong=document.createElement('strong');strong.textContent=value;const detail=document.createElement('small');detail.textContent=note;card.append(small,strong,detail);host.append(card);}}
function renderProjects(){const select=$('site-project');select.replaceChildren();for(const project of control?.projects||[]){const option=document.createElement('option');option.value=project.projectId;option.textContent=project.name;select.append(option)}if(!select.childElementCount){const option=document.createElement('option');option.value='';option.textContent='ยังไม่มี Project';select.append(option)}}
function button(text,className,site,action){const node=document.createElement('button');node.type='button';node.className=className;node.textContent=text;node.addEventListener('click',async()=>{node.disabled=true;try{await confirmAction(site,action,()=>managedSiteAction(site.siteId,action));await refresh();}catch(error){$('hosting-message').textContent=error instanceof Error?error.message:'AWH ยังดำเนินการไม่ได้'}finally{node.disabled=false}});return node}
function statusChip(text){const span=document.createElement('span');span.textContent=text;return span;}
function dnsInstruction(host){if(!dnsPlan?.target)return `DNS: สร้าง A record ของ ${host} ให้ชี้มายัง VPS`;return `DNS: A · ${host} → ${dnsPlan.target}`;}
function domainButton(site){const node=document.createElement('button');node.type='button';node.className='primary-button';node.textContent=site.domainState==='REQUESTED'?'กำลังรอ DNS':'เชื่อมโดเมน';node.disabled=site.domainState==='REQUESTED';if(!node.disabled)node.addEventListener('click',async()=>{node.disabled=true;try{const result=await confirmAction(site,'bind_domain',()=>bindManagedSiteDomain(site.siteId,desiredHost(site.slug||'')));const plan=result?.dnsPlan;$('hosting-message').textContent=plan?.target?`ตั้ง DNS: A · ${result.hostname} → ${plan.target} แล้ว AWH จะทำต่ออัตโนมัติ`:'รับคำขอแล้ว AWH จะตรวจ DNS และเปิด HTTPS ต่ออัตโนมัติ';await refresh();}catch(error){$('hosting-message').textContent=error instanceof Error?error.message:'ยังเชื่อมโดเมนไม่ได้'}finally{node.disabled=false}});return node;}
function renderSites(){const host=$('site-list');host.replaceChildren();const ready=sites.filter(s=>s.state==='READY').length;$('hosting-summary').textContent=`${ready} พร้อมใช้ · ${sites.length} เว็บไซต์`;
for(const site of sites){const card=document.createElement('article');card.className='site-card';const head=document.createElement('div');head.className='site-head';const title=document.createElement('h3');title.textContent=site.name;const state=document.createElement('span');state.className='site-state';state.textContent=statusLabel(site.state);head.append(title,state);card.append(head);
const desired=document.createElement('div');desired.className='site-url';const currentHost=site.domainHost||desiredHost(site.slug||'');const domainLabel=site.domainState==='ACTIVE'?'โดเมนพร้อมใช้':site.domainState==='REQUESTED'?'รอ DNS':site.domainState==='FAILED'?'โดเมนต้องตรวจสอบ':'ยังไม่เชื่อมโดเมน';desired.textContent=`${domainLabel} · https://${currentHost}`;card.append(desired);if(site.domainState==='REQUESTED'){const dns=document.createElement('div');dns.className='site-url';dns.textContent=dnsInstruction(currentHost);card.append(dns);}
if(site.lastEvent?.message){const event=document.createElement('div');event.className='site-event';event.textContent=site.lastEvent.message;card.append(event);}if(site.url){const link=document.createElement('a');link.className='site-url';link.href=site.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=`เปิดเว็บจริง · ${site.url}`;card.append(link)}else{const copy=document.createElement('div');copy.className='site-url';copy.textContent=site.state==='FAILED'?'ยังไม่มี Public URL ที่ผ่านการตรวจ':'AWH กำลังเตรียม Public URL';card.append(copy)}
const meta=document.createElement('div');meta.className='site-meta';meta.append(statusChip(site.projectName||'Project'),statusChip(`${runtimeLabel(site.runtimeType)}${site.runtimeVersion?` ${site.runtimeVersion}`:''}`),statusChip(site.databaseMode||'Database อัตโนมัติ'),statusChip(site.backupEnabled?'Backup เปิด':'Backup ปิด'));if(site.port)meta.append(statusChip(`Internal port ${site.port}`));card.append(meta);
const actions=document.createElement('div');actions.className='site-actions';if(site.state==='READY'&&site.domainState!=='ACTIVE')actions.append(domainButton(site));if(site.state!=='DISABLED')actions.append(button('Deploy รุ่นล่าสุด','secondary-button',site,'deploy'));if(site.rollbackReleaseId&&site.state!=='DISABLED')actions.append(button('Rollback','secondary-button',site,'rollback'));if(site.state!=='DISABLED')actions.append(button('ปิดการเผยแพร่','danger-button',site,'disable'));card.append(actions);host.append(card)}
if(!host.childElementCount){const empty=document.createElement('div');empty.className='site-empty';empty.textContent='ยังไม่มีเว็บไซต์ กรอกชื่อเว็บ เลือก Project แล้วกด “สร้างเว็บไซต์”';host.append(empty)}}
async function refresh(){try{control=await loadControlData();if(control.role!=='OWNER')throw new Error('เฉพาะ Owner เท่านั้นที่จัดการเว็บและโดเมนได้');const result=await listManagedSites();sites=Array.isArray(result.sites)?result.sites:[];policies=result.policy&&typeof result.policy==='object'?result.policy:{};dnsPlan=result.dns&&typeof result.dns==='object'?result.dns:null;ecosystem=result.ecosystem&&typeof result.ecosystem==='object'?result.ecosystem:null;renderEcosystem();renderProjects();renderSites();$('hosting-state').textContent='ระบบพร้อม'}catch(error){$('hosting-state').textContent='ระบบยังไม่พร้อม';$('hosting-message').textContent=error instanceof Error?error.message:'AWH ยังโหลดข้อมูลไม่ได้'}}
$('site-name').addEventListener('input',()=>{if(!$('site-slug').dataset.edited)$('site-slug').value=slugify($('site-name').value);renderUrlPreview();});
$('site-slug').addEventListener('input',()=>{$('site-slug').dataset.edited='1';$('site-slug').value=slugify($('site-slug').value);renderUrlPreview();});
$('hosting-create-form').addEventListener('submit',async(event)=>{event.preventDefault();const submit=event.currentTarget.querySelector('button[type="submit"]');submit.disabled=true;$('hosting-message').textContent='กำลังเตรียมเว็บไซต์…';try{await mutate(()=>createManagedSite({name:$('site-name').value.trim(),slug:$('site-slug').value.trim(),projectId:$('site-project').value,runtimeType:$('site-runtime').value,databaseMode:$('site-database').value,backupEnabled:$('site-backup').checked}));event.currentTarget.reset();$('site-backup').checked=true;$('site-slug').dataset.edited='';renderUrlPreview();$('hosting-message').textContent='สร้างเว็บไซต์แล้ว AWH กำลังเตรียม runtime และ public route จาก Source ที่พร้อม';await refresh()}catch(error){$('hosting-message').textContent=error instanceof Error?error.message:'ยังสร้างเว็บไซต์ไม่ได้'}finally{submit.disabled=false}});
$('hosting-confirm-submit').addEventListener('click',async()=>{if(!pendingConfirm)return;const current=pendingConfirm;const submit=$('hosting-confirm-submit');submit.disabled=true;$('hosting-confirm-message').textContent='กำลังดำเนินการ…';try{const result=await mutate(current.handler);pendingConfirm=null;$('hosting-confirm').hidden=true;current.resolve(result);}catch(error){$('hosting-confirm-message').textContent=error instanceof Error?error.message:'ยังดำเนินการไม่ได้';}finally{submit.disabled=false;}});
$('hosting-confirm-cancel').addEventListener('click',()=>{if(pendingConfirm){pendingConfirm.reject(new Error('ยกเลิกรายการแล้ว'));pendingConfirm=null;}$('hosting-confirm').hidden=true;});
$('hosting-refresh').addEventListener('click',()=>void refresh());
renderUrlPreview();void refresh();
