import { createManagedSite, listManagedSites, loadAuthSession, loadControlData, managedSiteAction } from './control-plane-adapter.js?release=__AWH_WEB_RELEASE_ID__';
const $=(id)=>document.getElementById(id);let control=null;let sites=[];let policies={};let pendingConfirm=null;
const statusLabel=(state)=>({READY:'พร้อมใช้งาน',PROVISIONING:'กำลังเตรียม',QUEUED:'รอดำเนินการ',FAILED:'ต้องตรวจสอบ',DISABLED:'ปิดการเผยแพร่'})[state]||state||'ไม่ทราบ';
const runtimeLabel=(value)=>({AUTO:'อัตโนมัติ',PHP:'PHP',NODE:'Node',STATIC:'Static'})[value]||value||'—';
function slugify(value){return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48);}
function previewBase(){const origin=window.location.origin&&window.location.origin!=='null'?window.location.origin:'https://157-85-108-142.sslip.io';return origin.replace(/\/$/,'');}
function renderUrlPreview(){const slug=$('site-slug').value.trim();$('site-url-preview').textContent=slug?`${previewBase()}/${slug}/`:`${previewBase()}/ชื่อย่อ/`;}
async function mutate(action,retried=false){try{return await action();}catch(error){if(error?.code==='CSRF_REJECTED'&&!retried){await loadAuthSession();return mutate(action,true);}throw error;}}
function policy(action){return policies[`hosting.site.${action}`]||{risk:'MEDIUM',confirmationRequired:true,stepUpRequired:false};}
function confirmationCopy(site,action){return ({deploy:`Deploy รุ่นล่าสุดของ “${site.name}” ไป Production โดย AWH จะเก็บ rollback point ที่ตรวจสอบได้ก่อนสลับรุ่น`,rollback:`ย้อน “${site.name}” กลับไปยังรุ่นก่อนหน้าที่ตรวจสอบแล้ว ข้อมูลถาวรจะไม่ถูกลบ`,disable:`ปิดการเผยแพร่ “${site.name}” ชั่วคราว โดย Source, Database, Release และ Backup จะยังถูกเก็บไว้`})[action]||`ดำเนินการกับ “${site.name}”`;}
function confirmAction(site,action,handler){const rule=policy(action);if(!rule.confirmationRequired)return mutate(handler);return new Promise((resolve,reject)=>{pendingConfirm={handler,resolve,reject};$('hosting-confirm-title').textContent=action==='rollback'?'ยืนยัน Rollback':action==='disable'?'ยืนยันปิดการเผยแพร่':'ยืนยัน Deploy';$('hosting-confirm-copy').textContent=confirmationCopy(site,action);$('hosting-confirm-message').textContent='';$('hosting-confirm').hidden=false;setTimeout(()=>$('hosting-confirm-submit').focus(),0);});}
function renderProjects(){const select=$('site-project');select.replaceChildren();for(const project of control?.projects||[]){const option=document.createElement('option');option.value=project.projectId;option.textContent=project.name;select.append(option)}if(!select.childElementCount){const option=document.createElement('option');option.value='';option.textContent='ยังไม่มี Project';select.append(option)}}
function button(text,className,site,action){const node=document.createElement('button');node.type='button';node.className=className;node.textContent=text;node.addEventListener('click',async()=>{node.disabled=true;try{await confirmAction(site,action,()=>managedSiteAction(site.siteId,action));await refresh();}catch(error){$('hosting-message').textContent=error instanceof Error?error.message:'AWH ยังดำเนินการไม่ได้'}finally{node.disabled=false}});return node}
function renderSites(){const host=$('site-list');host.replaceChildren();$('hosting-summary').textContent=`${sites.filter(s=>s.state==='READY').length} พร้อมใช้ · ${sites.length} เว็บไซต์`;
for(const site of sites){const card=document.createElement('article');card.className='site-card';const head=document.createElement('div');head.className='site-head';const title=document.createElement('h3');title.textContent=site.name;const state=document.createElement('span');state.className='site-state';state.textContent=statusLabel(site.state);head.append(title,state);const meta=document.createElement('div');meta.className='site-meta';for(const value of [site.projectName,`${runtimeLabel(site.runtimeType)}${site.runtimeVersion?` ${site.runtimeVersion}`:''}`,site.databaseMode,site.port?`Port ${site.port}`:null,site.backupEnabled?'Backup เปิด':'Backup ปิด'])if(value){const span=document.createElement('span');span.textContent=value;meta.append(span)}card.append(head,meta);if(site.url){const link=document.createElement('a');link.className='site-url';link.href=site.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=site.url;card.append(link)}else{const copy=document.createElement('div');copy.className='site-url';copy.textContent=site.state==='FAILED'?'ยังไม่เปิด Public URL — ตรวจสถานะก่อน':'AWH กำลังเตรียม Public URL';card.append(copy)}const actions=document.createElement('div');actions.className='site-actions';if(site.state!=='DISABLED')actions.append(button('Deploy รุ่นล่าสุด','secondary-button',site,'deploy'));if(site.rollbackReleaseId&&site.state!=='DISABLED')actions.append(button('Rollback','secondary-button',site,'rollback'));if(site.state!=='DISABLED')actions.append(button('ปิดการเผยแพร่','danger-button',site,'disable'));card.append(actions);host.append(card)}if(!host.childElementCount){const empty=document.createElement('div');empty.className='site-empty';empty.textContent='ยังไม่มีเว็บไซต์ กรอกข้อมูลด้านบนแล้วกด “สร้างเว็บไซต์”';host.append(empty)}}
async function refresh(){try{control=await loadControlData();if(control.role!=='OWNER')throw new Error('เฉพาะ Owner เท่านั้นที่จัดการ Hosting ได้');const result=await listManagedSites();sites=Array.isArray(result.sites)?result.sites:[];policies=result.policy&&typeof result.policy==='object'?result.policy:{};renderProjects();renderSites();$('hosting-state').textContent='Hosting เชื่อมต่อแล้ว'}catch(error){$('hosting-state').textContent='Hosting ยังไม่พร้อม';$('hosting-message').textContent=error instanceof Error?error.message:'AWH ยังโหลด Hosting ไม่ได้'}}
$('site-name').addEventListener('input',()=>{if(!$('site-slug').dataset.edited)$('site-slug').value=slugify($('site-name').value);renderUrlPreview();});$('site-slug').addEventListener('input',()=>{$('site-slug').dataset.edited='1';$('site-slug').value=slugify($('site-slug').value);renderUrlPreview();});
$('hosting-create-form').addEventListener('submit',async(event)=>{event.preventDefault();const submit=event.currentTarget.querySelector('button[type="submit"]');submit.disabled=true;$('hosting-message').textContent='กำลังสร้างเว็บไซต์…';try{await mutate(()=>createManagedSite({name:$('site-name').value.trim(),slug:$('site-slug').value.trim(),projectId:$('site-project').value,runtimeType:$('site-runtime').value,databaseMode:$('site-database').value,backupEnabled:$('site-backup').checked}));event.currentTarget.reset();$('site-backup').checked=true;$('site-slug').dataset.edited='';renderUrlPreview();$('hosting-message').textContent='สร้างเว็บไซต์แล้ว AWH จะเตรียม Production จาก Source ที่พร้อม';await refresh()}catch(error){$('hosting-message').textContent=error instanceof Error?error.message:'ยังสร้างเว็บไซต์ไม่ได้'}finally{submit.disabled=false}});
$('hosting-confirm-submit').addEventListener('click',async()=>{if(!pendingConfirm)return;const current=pendingConfirm;const submit=$('hosting-confirm-submit');submit.disabled=true;$('hosting-confirm-message').textContent='กำลังดำเนินการ…';try{const result=await mutate(current.handler);pendingConfirm=null;$('hosting-confirm').hidden=true;current.resolve(result);}catch(error){$('hosting-confirm-message').textContent=error instanceof Error?error.message:'ยังดำเนินการไม่ได้';}finally{submit.disabled=false;}});
$('hosting-confirm-cancel').addEventListener('click',()=>{if(pendingConfirm){pendingConfirm.reject(new Error('ยกเลิกรายการแล้ว'));pendingConfirm=null;}$('hosting-confirm').hidden=true;});
$('hosting-refresh').addEventListener('click',()=>void refresh());renderUrlPreview();void refresh();
