const $=(id)=>document.getElementById(id);
const bytes=(value)=>{const n=Number(value||0);if(!Number.isFinite(n)||n<1)return '—';if(n<1024**2)return `${Math.round(n/1024)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(1)} GB`;};
const percent=(value)=>Number.isFinite(Number(value))?`${Number(value).toFixed(Number(value)%1?1:0)}%`:'—';
const duration=(seconds)=>{let s=Math.max(0,Number(seconds)||0);const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);const m=Math.floor((s%3600)/60);return d?`${d} วัน ${h} ชม.`:h?`${h} ชม. ${m} นาที`:`${m} นาที`;};
const date=(value)=>{const t=Date.parse(value||'');return Number.isFinite(t)?new Date(t).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):'—';};
const goodState=(state)=>['ACTIVE','READY','HEALTHY','VERIFIED'].includes(String(state||'').toUpperCase());
const badState=(state)=>['FAILED','CRITICAL','INVALID','UNAVAILABLE'].includes(String(state||'').toUpperCase());
function chip(label,state=''){const node=document.createElement('span');node.className=`state-chip ${goodState(state)?'good':badState(state)?'bad':state?'warn':''}`.trim();node.textContent=label;return node;}
function row(title,detail,label,state=''){const item=document.createElement('div');item.className='entity-row';const copy=document.createElement('span');copy.className='entity-copy';const strong=document.createElement('strong');strong.textContent=title;const small=document.createElement('small');small.textContent=detail;copy.append(strong,small);item.append(copy,chip(label,state));return item;}
function empty(host,text){host.replaceChildren();const node=document.createElement('div');node.className='empty';node.textContent=text;host.append(node);}
function attention(text){const node=document.createElement('div');node.className='attention-item';node.textContent=text;$('attention-list').append(node);$('attention-section').hidden=false;}
function renderServices(server){const host=$('service-list');host.replaceChildren();const services=Array.isArray(server?.services)?server.services:[];if(!services.length)return empty(host,'ยังไม่มี service telemetry');for(const service of services){const active=service.state==='ACTIVE';const startup=service.startup==='ENABLED'?'เริ่มพร้อมระบบ':service.startup==='DISABLED'?'ไม่ได้เปิดอัตโนมัติ':service.startup;host.append(row(service.label,`${active?'กำลังทำงาน':'สถานะ '+service.state} · ${startup}`,active?'Online':service.state,service.state));if(service.key==='backup'&&(!active||service.startup!=='ENABLED'))attention('Automatic Backup ยังไม่ได้เปิดทำงานอัตโนมัติ');else if(['nginx','php-fpm','native-executor'].includes(service.key)&&!active)attention(`${service.label} ต้องตรวจสอบ`);}}
function renderSecurity(server){const host=$('security-list');host.replaceChildren();const security=server?.security||{};host.append(row('Login Protection','Fail2ban ช่วยบล็อกการลองรหัสผ่านผิดซ้ำ',security.fail2ban==='ACTIVE'?'Protected':security.fail2ban,security.fail2ban));host.append(row('Automatic Updates','อัปเดต security package ของ Ubuntu อัตโนมัติ',security.automaticUpdates==='ACTIVE'?'Enabled':security.automaticUpdates,security.automaticUpdates));}
function renderProjects(data){const host=$('project-grid');host.replaceChildren();const projects=Array.isArray(data.projects)?data.projects:[];if(!projects.length)return empty(host,'ยังไม่มีโปรเจกต์ที่ลงทะเบียนใน AWH');for(const project of projects){const card=document.createElement('article');card.className='project-card';const title=document.createElement('strong');title.textContent=project.name||'Project';const meta=document.createElement('span');meta.textContent=`${project.type||'general'} · ${project.memoryReady?'Memory พร้อม':'พร้อมใช้งาน'}`;card.append(title,meta);host.append(card);}}
function renderDomains(server){const host=$('domain-list');host.replaceChildren();const domains=Array.isArray(server?.domains)?server.domains:[];if(!domains.length)return empty(host,'ยังไม่พบ custom domain จาก Nginx · เมื่อจดโดเมนแล้ว AWH จะแสดงที่นี่');for(const domain of domains){let detail=domain.tls?'HTTPS เปิดอยู่':'ยังไม่มี HTTPS';if(Number.isInteger(domain.certificateDaysRemaining))detail+=` · SSL เหลือ ${domain.certificateDaysRemaining} วัน`;host.append(row(domain.name,detail,domain.tls?'HTTPS':'HTTP',domain.tls?'ACTIVE':'INACTIVE'));if(!domain.tls)attention(`${domain.name} ยังไม่มี HTTPS`);else if(Number.isInteger(domain.certificateDaysRemaining)&&domain.certificateDaysRemaining<21)attention(`SSL ของ ${domain.name} ใกล้หมดอายุ`);}}
function renderRecovery(data){const host=$('recovery-list');host.replaceChildren();const db=data.database||{};const backup=data.backup||{};const storage=data.storage||{};host.append(row('Database',`Schema ${db.schemaVersion??'—'} · Integrity ${db.state==='HEALTHY'?'ผ่าน':'ต้องตรวจ'}`,db.state==='HEALTHY'?'Healthy':db.state,db.state));const latest=backup.latest;host.append(row('Backup',latest?`ล่าสุด ${date(latest.verifiedAt)} · ${bytes(latest.sizeBytes)}`:'ยังไม่มี backup ที่ยืนยันแล้ว',backup.state==='VERIFIED'?'Verified':backup.state,backup.state));host.append(row('Storage',`${bytes(storage.freeBytes)} ว่างจาก ${bytes(storage.totalBytes)}`,percent(storage.usedPercent),storage.state));if(db.state!=='HEALTHY')attention('Database integrity ต้องตรวจสอบ');if(backup.state!=='VERIFIED')attention('Backup ล่าสุดยังไม่อยู่ในสถานะ Verified');if(['WARNING','CRITICAL'].includes(storage.state))attention('พื้นที่ VPS เริ่มเหลือน้อย');}
function renderRuntime(data){const host=$('runtime-list');host.replaceChildren();const queue=data.queue||{};const workers=data.workerSummary||{};const ai=data.aiBudget||{};host.append(row('Task Queue',`${Number(queue.activeTaskCount||0)} งานกำลังทำ · ${Number(queue.waitingCapabilityCount||0)} งานรอความสามารถ`,Number(queue.activeTaskCount||0)?'Working':'Ready',Number(queue.waitingCapabilityCount||0)?'INACTIVE':'ACTIVE'));host.append(row('Mac / Windows Workers',`${Number(workers.ready||0)} จาก ${Number(workers.total||0)} เครื่องพร้อมรับงาน`,`${Number(workers.ready||0)}/${Number(workers.total||0)}`,Number(workers.ready||0)>0?'ACTIVE':'INACTIVE'));let aiDetail='ยังไม่ได้เชื่อม AI';if(ai.state==='READY'){const total=Number(ai.monthlyMicrounits||0),used=Number(ai.usedMicrounits||0);aiDetail=total>0?`ใช้งบประมาณ ${Math.min(100,Math.round(used/total*100))}% ของวงเงินเดือนนี้`:'AI พร้อม';}host.append(row('AI & Usage',aiDetail,ai.state==='READY'?'Ready':ai.state,ai.state));}
function renderServer(data){const telemetry=data.telemetry||{};const server=telemetry.server;const overall=$('infra-overall');$('attention-list').replaceChildren();$('attention-section').hidden=true;if(!server){$('server-dot').className='health-dot warn';$('server-os').textContent=telemetry.state==='NOT_CONFIGURED'?'Telemetry ยังไม่ได้เปิดบน VPS':'Telemetry ต้องตรวจสอบ';$('infra-freshness').textContent='ยังไม่มี VPS snapshot';overall.textContent='AWH Online · VPS telemetry รอเปิด';overall.className='overall-state';attention('Infrastructure telemetry ยังไม่ได้เปิดใช้งานบน VPS');renderServices(null);renderSecurity(null);renderDomains(null);return;}$('server-name').textContent=server.host?.name||'ReadyIDC VPS';$('server-os').textContent=server.host?.os||'Ubuntu';$('server-uptime').textContent=`เปิดมาแล้ว ${duration(server.host?.uptimeSeconds)}`;$('metric-cpu').textContent=percent(server.cpu?.usedPercent);$('metric-load').textContent=`Load ${server.cpu?.load1??'—'}`;$('metric-memory').textContent=percent(server.memory?.usedPercent);$('metric-memory-detail').textContent=`เหลือ ${bytes(server.memory?.availableBytes)}`;$('metric-storage').textContent=percent(server.storage?.usedPercent);$('metric-storage-detail').textContent=`เหลือ ${bytes(server.storage?.freeBytes)}`;$('metric-release').textContent=data.deployment?.releaseId||'Current';$('infra-freshness').textContent=`อัปเดต ${date(telemetry.generatedAt)}`;if(telemetry.state!=='READY')attention('ข้อมูลสถานะ VPS เก่ากว่าช่วงเวลาที่กำหนด ควรตรวจ AWH Agent Runtime');renderServices(server);renderSecurity(server);renderDomains(server);overall.textContent=telemetry.state==='READY'?'VPS Online · กำลังประเมิน':'VPS Online · Telemetry ต้องตรวจ';}
function finalizeOverall(data){const count=$('attention-list').children.length;const overall=$('infra-overall');const dbOk=data.database?.state==='HEALTHY';if(count===0&&dbOk){overall.textContent='ระบบทั้งหมดทำงานปกติ';overall.className='overall-state';$('server-dot').className='health-dot';}else{overall.textContent=`ระบบทำงานได้ · ${count} รายการควรดู`;overall.className='overall-state';$('server-dot').className='health-dot warn';}}
function showFatal(message){const main=document.querySelector('.infra-main');if(!(main instanceof HTMLElement))return;main.replaceChildren();const card=document.createElement('div');card.className='fatal';const title=document.createElement('strong');title.textContent='ยังเปิด Infrastructure ไม่ได้';const copy=document.createElement('p');copy.textContent=String(message||'AWH ไม่สามารถอ่านสถานะ VPS ได้');const back=document.createElement('a');back.className='action-link';back.href='./';back.textContent='กลับ AWH';card.append(title,copy,back);main.append(card);}
async function load(){const button=$('infra-refresh');button.disabled=true;try{const response=await fetch('/api/v1/control/infrastructure',{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}});if(response.status===401){location.assign('./');return;}const data=await response.json();if(!response.ok||data?.schemaVersion!==1)throw new Error(data?.message||'Infrastructure data ไม่พร้อม');renderServer(data);renderProjects(data);renderRecovery(data);renderRuntime(data);finalizeOverall(data);}catch(error){showFatal(error?.message);}finally{button.disabled=false;}}
$('infra-refresh').addEventListener('click',load);load();
