const $=(id)=>document.getElementById(id);
const fmt=(n)=>new Intl.NumberFormat('th-TH').format(Number(n||0));
const bytes=(n)=>{const v=Number(n||0);if(v<1024)return `${v} B`;if(v<1024**2)return `${(v/1024).toFixed(1)} KB`;if(v<1024**3)return `${(v/1024**2).toFixed(1)} MB`;return `${(v/1024**3).toFixed(1)} GB`;};
const date=(v)=>{const t=Date.parse(v||'');return Number.isFinite(t)?new Date(t).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'}):'—';};
function chip(text,state=''){const n=document.createElement('span');n.className=`chip ${state}`.trim();n.textContent=text;return n;}
function entity(title,detail,label,state=''){const row=document.createElement('div');row.className='entity-row';const copy=document.createElement('div');copy.className='entity-copy';const strong=document.createElement('strong');strong.textContent=title;const small=document.createElement('small');small.textContent=detail;copy.append(strong,small);row.append(copy,chip(label,state));return row;}
function eventRow(name,at){const row=document.createElement('div');row.className='event-row';const label=document.createElement('span');label.textContent=name;const time=document.createElement('time');time.textContent=date(at);row.append(label,time);return row;}
function attention(text){const row=document.createElement('div');row.className='event-row';row.textContent=text;$('attention-list').append(row);$('attention').hidden=false;}
function render(data){const s=data.summary||{};$('metric-tasks').textContent=fmt(s.taskEventCount);$('metric-approvals').textContent=fmt(s.pendingApprovalCount);$('metric-artifacts').textContent=fmt(s.artifactCount);$('metric-artifact-size').textContent=`${bytes(s.artifactBytes)} ใน 24 ชม.`;$('metric-undo').textContent=fmt(s.checkpointEventCount);$('auth-count').textContent=`${fmt(s.authEventCount)} เหตุการณ์ใน 24 ชม.`;
 const ds=$('data-safety');ds.replaceChildren(entity('Database',`Schema ${data.health?.database?.schemaVersion??'—'} · integrity ${data.health?.database?.state==='HEALTHY'?'ผ่าน':'ต้องตรวจ'}`,data.health?.database?.state||'Unknown',data.health?.database?.state==='HEALTHY'?'good':'bad'),entity('Backup',data.health?.backup?.latest?`ตรวจล่าสุด ${date(data.health.backup.latest.verifiedAt)}`:'ยังไม่มีหลักฐาน backup ล่าสุด',data.health?.backup?.state||'Unknown',data.health?.backup?.state==='VERIFIED'?'good':'warn'),entity('Secret boundary','Trust API ไม่ส่ง secret, raw path หรือ metadata hash ออก browser','Protected','good'));
 const es=$('execution-safety');es.replaceChildren(entity('Failed executions',`${fmt(s.failedExecutionCount)} งานใน 24 ชั่วโมง`,s.failedExecutionCount?'Review':'Clear',s.failedExecutionCount?'warn':'good'),entity('Approval gate',`${fmt(s.pendingApprovalCount)} รายการกำลังรอการตัดสินใจ`,s.pendingApprovalCount?'Pending':'Clear',s.pendingApprovalCount?'warn':'good'),entity('Undo evidence',`${fmt(s.checkpointEventCount)} checkpoint events ใน 24 ชั่วโมง`,s.checkpointEventCount?'Ready':'On mutation',s.checkpointEventCount?'good':''));
 const auth=$('auth-events');auth.replaceChildren();const events=Array.isArray(data.recentAuthEvents)?data.recentAuthEvents:[];if(events.length){for(const item of events)auth.append(eventRow(item.eventName,item.occurredAt));}else auth.append(eventRow('ไม่มี security event ใหม่',''));
 $('attention-list').replaceChildren();$('attention').hidden=true;if(s.failedExecutionCount>0)attention(`มี execution ล้มเหลว ${fmt(s.failedExecutionCount)} รายการใน 24 ชั่วโมง`);if(data.health?.database?.state!=='HEALTHY')attention('Database integrity ต้องตรวจสอบ');if(data.health?.backup?.state!=='VERIFIED')attention('Backup ล่าสุดยังไม่อยู่ในสถานะ Verified');
 const review=$('attention-list').children.length>0;$('trust-overall').textContent=review?'ระบบทำงานได้ · มีรายการควรดู':'หลักฐานสำคัญอยู่ในสถานะปกติ';$('trust-dot').className=review?'':'good';$('trust-freshness').textContent=`อัปเดต ${date(data.generatedAt)}`;
}
async function load(){const button=$('trust-refresh');button.disabled=true;try{const response=await fetch('/api/v1/control/trust',{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}});if(response.status===401){location.assign('./');return;}const data=await response.json();if(!response.ok||data?.schemaVersion!==1)throw new Error('Trust data ไม่พร้อม');render(data);}catch(error){$('trust-overall').textContent='ยังตรวจ Trust Center ไม่ได้';$('trust-dot').className='bad';$('trust-freshness').textContent=String(error?.message||'Unknown error');}finally{button.disabled=false;}}
$('trust-refresh').addEventListener('click',load);load();
