const { contextBridge, ipcRenderer } = require('electron');

const CHANNELS = Object.freeze({
  enrollmentState: 'art-agent:enrollment-state',
  enrollmentLogin: 'art-agent:enrollment-login',
  workerState: 'art-agent:worker-state',
  runtimeMode: 'art-agent:runtime-mode',
  runtimeModeSet: 'art-agent:runtime-mode-set',
  emergencyStop: 'art-agent:emergency-stop',
  activity: 'art-agent:activity',
  health: 'art-agent:health',
  diagnosticsExport: 'art-agent:diagnostics-export',
  updateCheck: 'art-agent:update-check',
  updateInstall: 'art-agent:update-install',
  reinstallRuntime: 'art-agent:reinstall-runtime',
  resetDevice: 'art-agent:reset-device',
  permissionState: 'art-agent:permission-state',
  permissionAuthorize: 'art-agent:permission-authorize',
  permissionSettings: 'art-agent:permission-settings',
  openAwhWeb: 'art-agent:open-awh-web',
});

contextBridge.exposeInMainWorld('awhConnect', Object.freeze({
  getEnrollmentState: () => ipcRenderer.invoke(CHANNELS.enrollmentState),
  login: (username, password) => ipcRenderer.invoke(
    CHANNELS.enrollmentLogin,
    typeof username === 'string' ? username.slice(0, 64) : '',
    typeof password === 'string' ? password.slice(0, 512) : '',
  ),
  getWorkerState: () => ipcRenderer.invoke(CHANNELS.workerState),
  getRuntimeMode: () => ipcRenderer.invoke(CHANNELS.runtimeMode),
  setRuntimeMode: (mode) => ipcRenderer.invoke(CHANNELS.runtimeModeSet, typeof mode === 'string' ? mode : ''),
  emergencyStop: () => ipcRenderer.invoke(CHANNELS.emergencyStop),
  getActivity: () => ipcRenderer.invoke(CHANNELS.activity),
  getHealth: () => ipcRenderer.invoke(CHANNELS.health),
  exportDiagnostics: () => ipcRenderer.invoke(CHANNELS.diagnosticsExport),
  checkUpdate: () => ipcRenderer.invoke(CHANNELS.updateCheck),
  installUpdate: () => ipcRenderer.invoke(CHANNELS.updateInstall),
  reinstallRuntime: () => ipcRenderer.invoke(CHANNELS.reinstallRuntime),
  resetDevice: () => ipcRenderer.invoke(CHANNELS.resetDevice),
  getPermissionState: () => ipcRenderer.invoke(CHANNELS.permissionState),
  authorizePermissions: () => ipcRenderer.invoke(CHANNELS.permissionAuthorize),
  openPermissionSettings: (kind = '') => ipcRenderer.invoke(CHANNELS.permissionSettings, typeof kind === 'string' ? kind : ''),
  openAwhWeb: (target = 'home') => ipcRenderer.invoke(CHANNELS.openAwhWeb, target === 'devices' ? 'devices' : 'home'),
}));
