const { contextBridge, ipcRenderer } = require('electron');

const CHANNELS = Object.freeze({
  overview: 'art-agent:overview',
  projects: 'art-agent:projects',
  projectContext: 'art-agent:project-context',
  registerProject: 'art-agent:register-project',
  initializeProject: 'art-agent:initialize-project',
  initializeProjectMemory: 'art-agent:initialize-project-memory',
  selectProject: 'art-agent:select-project',
  locateProject: 'art-agent:locate-project',
  chooseWorkspace: 'art-agent:choose-workspace',
  setPermissions: 'art-agent:set-permissions',
  remoteConnect: 'art-agent:remote-connect',
  remoteStop: 'art-agent:remote-stop',
  enrollmentState: 'art-agent:enrollment-state',
  enrollmentPair: 'art-agent:enrollment-pair',
  enrollmentRotate: 'art-agent:enrollment-rotate',
  enrollmentRevoke: 'art-agent:enrollment-revoke',
  firstRun: 'art-agent:first-run',
  trustOwner: 'art-agent:trust-owner',
  autopilotOverview: 'art-agent:autopilot-overview',
  autopilotStart: 'art-agent:autopilot-start',
  autopilotTasks: 'art-agent:autopilot-tasks',
  autopilotArtifacts: 'art-agent:autopilot-artifacts',
  autopilotContinuity: 'art-agent:autopilot-continuity',
  autopilotCheckpointMemory: 'art-agent:autopilot-checkpoint-memory',
  restart: 'art-agent:restart',
  openDataDir: 'art-agent:open-data-dir',
});

contextBridge.exposeInMainWorld('artAgent', Object.freeze({
  getOverview: () => ipcRenderer.invoke(CHANNELS.overview),
  getProjects: () => ipcRenderer.invoke(CHANNELS.projects),
  getProjectContext: (projectId) => ipcRenderer.invoke(CHANNELS.projectContext, typeof projectId === 'string' ? projectId.slice(0, 64) : ''),
  registerProject: () => ipcRenderer.invoke(CHANNELS.registerProject),
  initializeProject: () => ipcRenderer.invoke(CHANNELS.initializeProject),
  initializeProjectMemory: (projectId) => ipcRenderer.invoke(CHANNELS.initializeProjectMemory, typeof projectId === 'string' ? projectId.slice(0, 64) : ''),
  selectProject: (projectId) => ipcRenderer.invoke(CHANNELS.selectProject, typeof projectId === 'string' ? projectId.slice(0, 64) : ''),
  locateProject: (projectId) => ipcRenderer.invoke(CHANNELS.locateProject, typeof projectId === 'string' ? projectId.slice(0, 64) : ''),
  chooseWorkspace: () => ipcRenderer.invoke(CHANNELS.chooseWorkspace),
  setPermissions: (permissions) => ipcRenderer.invoke(CHANNELS.setPermissions, {
    write: permissions?.write === true,
    execute: permissions?.execute === true,
    codex: permissions?.codex === true,
  }),
  remoteConnect: () => ipcRenderer.invoke(CHANNELS.remoteConnect),
  remoteStop: () => ipcRenderer.invoke(CHANNELS.remoteStop),
  getEnrollmentState: () => ipcRenderer.invoke(CHANNELS.enrollmentState),
  pairDevice: (pairingCode) => ipcRenderer.invoke(CHANNELS.enrollmentPair, typeof pairingCode === 'string' ? pairingCode.slice(0, 128) : ''),
  rotateDeviceCredential: () => ipcRenderer.invoke(CHANNELS.enrollmentRotate),
  revokeDeviceCredential: () => ipcRenderer.invoke(CHANNELS.enrollmentRevoke),
  getFirstRun: () => ipcRenderer.invoke(CHANNELS.firstRun),
  trustOwner: (ownerDisplayName, deviceName) => ipcRenderer.invoke(CHANNELS.trustOwner,
    typeof ownerDisplayName === 'string' ? ownerDisplayName.slice(0, 80) : '',
    typeof deviceName === 'string' ? deviceName.slice(0, 80) : ''),
  getAutopilotOverview: () => ipcRenderer.invoke(CHANNELS.autopilotOverview),
  startAutopilot: (goal) => ipcRenderer.invoke(CHANNELS.autopilotStart, typeof goal === 'string' ? goal.slice(0, 2_000) : ''),
  getAutopilotTasks: () => ipcRenderer.invoke(CHANNELS.autopilotTasks),
  getAutopilotArtifacts: () => ipcRenderer.invoke(CHANNELS.autopilotArtifacts),
  getAutopilotContinuity: () => ipcRenderer.invoke(CHANNELS.autopilotContinuity),
  checkpointAutopilotMemory: (taskId) => ipcRenderer.invoke(CHANNELS.autopilotCheckpointMemory, typeof taskId === 'string' ? taskId.slice(0, 128) : ''),
  restart: () => ipcRenderer.invoke(CHANNELS.restart),
  openDataDir: () => ipcRenderer.invoke(CHANNELS.openDataDir),
}));
